### ISSUE TITLE
Setting user avatar doesnt do anything

### ISSUE THREAD

**Issue by jcalonso** [vector-im/riot-web#10175]
### Description

Setting user avatar doesn't not do anything (on the UI).

Looking at the dev tools / Network requests, there is a successful `POST` to the upload endpoint
followed by a `PUT` to the `_matrix/client/r0/profile/@user:server/avatar_url` address with a `404` response code.
The request payload contains the following:
```
{"avatar_url":"mxc://my-matrix-server.com/xxxxxxxxxxxx"}
```
and the response:
```
{"errcode":"M_UNKNOWN","error":"No row found (profiles)"}
```

### Steps to reproduce

- Login into self hosted Riot instance
- Click profile
- Set avatar (preview loads)
- Click save
- Nothing happens

Describe how what happens differs from what you expected.

Log: sent/not sent?    
- It show display the new avatar

### Version information

- web and desktop

For the web app:

- **Browser**: Firefox 67
- **OS**:  Arch Linux
- **URL**:  self-hosted, version riot-web version: 1.2.1

For the desktop app:

- **OS**: Arch Linux
- **Version**: riot-web version: 1.2.2

**Comment by jryans** [comment]
Hmm, it could be a homeserver issue... Do you see anything in the HS logs?

**Comment by jcalonso** [comment]
Only this:
```
Jun 28 13:18:30 matrix synapse[2349]: synapse.access.http.8008: [OPTIONS-45407] 172.16.16.15 - 8008 - Received request: OPTIONS /_matrix/media/v1/upload?filename=myavatar.jpeg
Jun 28 13:18:30 matrix synapse[2349]: synapse.access.http.8008: [OPTIONS-45407] 172.16.16.15 - 8008 - {None} Processed request: 0.001sec/-0.000sec (0.000sec, 0.000sec) (0.000sec/0.000sec/0) 2B 200 "OPTIONS /_matrix/media/v1/upload?filename=myavatar.jpeg HTTP/1.0" "Mozilla/5.0 (X11; Linux x86_64; rv:67.0) Gecko/20100101 Firefox/67.0" [0 dbevts]
Jun 28 13:18:30 matrix synapse[2349]: synapse.access.http.8008: [POST-45408] 172.16.16.15 - 8008 - Received request: POST /_matrix/media/v1/upload?filename=myavatar.jpeg
Jun 28 13:18:30 matrix synapse[2349]: synapse.rest.media.v1.media_repository: [POST-45408] Stored local media in file '/home/synapse/.synapse/media_store/local_content/dQ/VN/zFvpgFIVlIolQRDCslDK'
Jun 28 13:18:30 matrix synapse[2349]: synapse.metrics: [] Collecting gc 0
Jun 28 13:18:30 matrix synapse[2349]: synapse.rest.media.v1.upload_resource: [POST-45408] Uploaded content with URI 'mxc://mydomain.com/xxxxxxxxxxxxxxxxxxxxxxxx'
Jun 28 13:18:30 matrix synapse[2349]: synapse.access.http.8008: [POST-45408] 172.16.16.15 - 8008 - {@jcalonso:mydomain.com} Processed request: 0.016sec/0.000sec (0.006sec, 0.000sec) (0.001sec/0.005sec/4) 61B 200 "POST /_matrix/media/v1/upload?filename=myavatar.jpeg HTTP/1.0" "Mozilla/5.0 (X11; Linux x86_64; rv:67.0) Gecko/20100101 Firefox/67.0" [0 dbevts]
Jun 28 13:18:31 matrix synapse[2349]: synapse.access.http.8008: [OPTIONS-45409] 172.16.16.15 - 8008 - Received request: OPTIONS /_matrix/client/r0/profile/@jcalonso:mydomain.com/avatar_url
Jun 28 13:18:31 matrix synapse[2349]: synapse.access.http.8008: [OPTIONS-45409] 172.16.16.15 - 8008 - {None} Processed request: 0.000sec/0.000sec (0.000sec, 0.000sec) (0.000sec/0.000sec/0) 22B 200 "OPTIONS /_matrix/client/r0/profile/@jcalonso:mydomain.com/avatar_url HTTP/1.0" "Mozilla/5.0 (X11; Linux x86_64; rv:67.0) Gecko/20100101 Firefox/67.0" [0 dbevts]
Jun 28 13:18:31 matrix synapse[2349]: synapse.access.http.8008: [PUT-45410] 172.16.16.15 - 8008 - Received request: PUT /_matrix/client/r0/profile/@jcalonso:mydomain.com/avatar_url
Jun 28 13:18:31 matrix synapse[2349]: synapse.http.server: [PUT-45410] <XForwardedForRequest at 0x7f9329c1c9b0 method='PUT' uri='/_matrix/client/r0/profile/@jcalonso:mydomain.com/avatar_url' clientproto='HTTP/1.0' site=8008> SynapseError: 404 - No row found (profiles)
Jun 28 13:18:31 matrix synapse[2349]: synapse.access.http.8008: [PUT-45410] 172.16.16.15 - 8008 - {@jcalonso:mydomain.com} Processed request: 0.003sec/0.000sec (0.000sec, 0.000sec) (0.000sec/0.001sec/2) 73B 404 "PUT /_matrix/client/r0/profile/@jcalonso:mydomain.com/avatar_url HTTP/1.0" "Mozilla/5.0 (X11; Linux x86_64; rv:67.0) Gecko/20100101 Firefox/67.0" [0 dbevts]
```

**Comment by jryans** [comment]
I would suggest asking in #riot:matrix.org and / or #synapse:matrix.org in case others have encountered this and can help debug.

**Comment by jcalonso** [comment]
thanks @jryans will do

**Comment by jcalonso** [comment]
Upgraded to Riot v1.3.0 and Synapse v1.1.0 and problem persists

**Comment by jryans** [comment]
Sorry to hear this continue to happen... I haven't heard of this issue occurring before, so I am not quite sure what to suggest at the moment. 😓

**Comment by richvdh** [comment]
Well, this suggests that the `profiles` table in the synapse database is missing a row for this user. To confirm, you could try running this SQL:

```
SELECT * FROM profiles WHERE user_id='jcalonso';
```

The above should return a single row, but I suspect it will return nothing.

As to how this might have happened: no idea :/. Have you recently done any maintenance on your database?

**Comment by jcalonso** [comment]
@richvdh I queried the profiles table and there is only one entry, and that's for a bot account I created. I should have another 2 real accounts there (one being jcalonso), Not sure what happened, maybe re-running this Ansible playbook had side effects: https://github.com/Madic-/matrix-synapse-auto-deploy

Should I reinstall? is there anything I should backup before doing this?

Thanks for your help

**Comment by richvdh** [comment]
> maybe re-running this Ansible playbook had side effects: https://github.com/Madic-/matrix-synapse-auto-deploy

Looks like it would have done if you ran it with `make_migration: true`, yes :/.

I think the easiest solution is going to be just to add the missing rows to `profiles`:

```
INSERT INTO profiles (user_id) VALUES ('jcalonso');
```

hopefully you won't find too much else that has been deleted.

If you decide to start again from scratch, it's best to leave any rooms you are in first. It's also best to keep a copy of your server's signing key (the target of `signing_key_path` in the config).

**Comment by jcalonso** [comment]
Thanks for your help @richvdh this also fixed another issue I was having with the mobile app.

**Comment by meteorpublish** [comment]
Had the same problem with a new install of riot-web. Avatar didn't update in the settings until I restarted Riot.

**Comment by chris-aeviator** [comment]
I'm facing the same issue but see this:

```
uri='/_matrix/media/r0/thumbnail/MYSERVER.TLD/QE[…my file handler....]ZCuE?width=201&height=201&method=crop' clientproto='HTTP/1.1' site=8008>
matrix-server-v2 | Traceback (most recent call last):
matrix-server-v2 |   File "/usr/local/lib/python3.7/dist-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
matrix-server-v2 |     result = g.send(result)
matrix-server-v2 | StopIteration: [{'thumbnail_width': 391, 'thumbnail_height': 367, 'thumbnail_method': 'scale', 'thumbnail_type': 'image/png', 'thumbnail_length': 180443}]
matrix-server-v2 |
matrix-server-v2 | During handling of the above exception, another exception occurred:
matrix-server-v2 |
matrix-server-v2 | Traceback (most recent call last):
matrix-server-v2 |   File "/usr/local/lib/python3.7/dist-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
matrix-server-v2 |     result = g.send(result)
matrix-server-v2 | StopIteration: [{'thumbnail_width': 391, 'thumbnail_height': 367, 'thumbnail_method': 'scale', 'thumbnail_type': 'image/png', 'thumbnail_length': 180443}]
matrix-server-v2 |
matrix-server-v2 | During handling of the above exception, another exception occurred:
matrix-server-v2 |
matrix-server-v2 | Traceback (most recent call last):
matrix-server-v2 |   File "/usr/local/lib/python3.7/dist-packages/synapse/http/server.py", line 78, in wrapped_request_handler
matrix-server-v2 |     await h(self, request)
matrix-server-v2 |   File "/usr/local/lib/python3.7/dist-packages/synapse/rest/media/v1/thumbnail_resource.py", line 68, in _async_render_GET
matrix-server-v2 |     request, media_id, width, height, method, m_type
matrix-server-v2 |   File "/usr/local/lib/python3.7/dist-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
matrix-server-v2 |     result = g.send(result)
matrix-server-v2 |   File "/usr/local/lib/python3.7/dist-packages/synapse/rest/media/v1/thumbnail_resource.py", line 100, in _respond_local_thumbnail
matrix-server-v2 |     width, height, method, m_type, thumbnail_infos
matrix-server-v2 |   File "/usr/local/lib/python3.7/dist-packages/synapse/rest/media/v1/thumbnail_resource.py", line 336, in _select_thumbnail
matrix-server-v2 |     return min(crop_info_list2)[-1]
matrix-server-v2 | ValueError: min() arg is an empty sequence
