### ISSUE TITLE
Signing error during electron build

### ISSUE THREAD

**Issue by awesome-michael** [vector-im/riot-web#10309]
### Description

I'm trying to build the desktop app with electron on macOS using the `yarn build:electron` command. It works pretty well but then I get this error during the signing process (is it the signing of the .app package?):

```
Configuring yargs through package.json is deprecated and will be removed in the next major release, please use the JS API instead.
  • electron-builder version=20.39.0
  • loaded configuration file=package.json ("build" field)
  • installing production dependencies platform=darwin arch=x64 appDir=/Users/xxx/repositories/riot-web/electron_app
Configuring yargs through package.json is deprecated and will be removed in the next major release, please use the JS API instead.
Configuring yargs through package.json is deprecated and will be removed in the next major release, please use the JS API instead.
  • electron-builder version=20.39.0
  • loaded configuration file=package.json ("build" field)
  • writing effective config file=electron_app/dist/builder-effective-config.yaml
  • no native production dependencies
  • packaging       platform=darwin arch=x64 electron=4.2.2 appOutDir=electron_app/dist/mac
  • signing         file=electron_app/dist/mac/myChat.app identityName=gdbcert identityHash=5A58160560A00CB41688AFDF4CAB3F11F49F8968 provisioningProfile=none
Error: Command failed: codesign --sign 5A58160560A00CB41688AFDF4CAB3F11F49F8968 --force /Users/xxx/repositories/riot-web/electron_app/dist/mac/myChat.app/Contents/Frameworks/myChat Helper.app/Contents/MacOS/myChat Helper
error: unknown error -26276=ffffffffffff995c

    at ChildProcess.exithandler (child_process.js:290:12)
    at ChildProcess.emit (events.js:200:13)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
From previous event:
    at MacPackager.sign (/Users/xxx/repositories/riot-web/node_modules/app-builder-lib/src/macPackager.ts:121:97)
    at /Users/xxx/repositories/riot-web/node_modules/app-builder-lib/src/macPackager.ts:89:26
    at processImmediate (internal/timers.js:439:21)
From previous event:
    at /Users/xxx/repositories/riot-web/node_modules/app-builder-lib/src/macPackager.ts:89:10
    at Generator.next (<anonymous>)
From previous event:
    at MacPackager.pack (/Users/xxx/repositories/riot-web/node_modules/app-builder-lib/src/macPackager.ts:80:95)
    at /Users/xxx/repositories/riot-web/node_modules/app-builder-lib/src/packager.ts:430:24
    at Generator.next (<anonymous>)
    at /Users/xxx/repositories/riot-web/node_modules/fs-extra-p/node_modules/fs-extra/lib/mkdirs/mkdirs.js:56:16
    at /Users/xxx/repositories/riot-web/node_modules/graceful-fs/polyfills.js:285:20
    at FSReqCallback.oncomplete (fs.js:166:5)
From previous event:
    at Packager.doBuild (/Users/xxx/repositories/riot-web/node_modules/app-builder-lib/src/packager.ts:396:24)
    at /Users/xxx/repositories/riot-web/node_modules/app-builder-lib/src/packager.ts:366:57
    at Generator.next (<anonymous>)
    at /Users/xxx/repositories/riot-web/node_modules/graceful-fs/graceful-fs.js:111:16
    at /Users/xxx/repositories/riot-web/node_modules/graceful-fs/graceful-fs.js:45:10
    at FSReqCallback.oncomplete (fs.js:153:23)
From previous event:
    at Packager._build (/Users/xxx/repositories/riot-web/node_modules/app-builder-lib/src/packager.ts:335:133)
    at /Users/xxx/repositories/riot-web/node_modules/app-builder-lib/src/packager.ts:331:23
    at Generator.next (<anonymous>)
    at processImmediate (internal/timers.js:439:21)
From previous event:
    at Packager.build (/Users/xxx/repositories/riot-web/node_modules/app-builder-lib/src/packager.ts:288:14)
    at build (/Users/xxx/repositories/riot-web/node_modules/app-builder-lib/src/index.ts:59:28)
    at build (/Users/xxx/repositories/riot-web/node_modules/electron-builder/src/builder.ts:228:10)
    at /Users/xxx/repositories/riot-web/node_modules/electron-builder/src/cli/cli.ts:46:19
error Command failed with exit code 1.
```

I assume that I need a certificate to sign the app by myself. Where do I get such a certificate, which one do I need and where do I have to change the configuration that the new certificate is used?

### Steps to reproduce

- Follow build instructions
- Build using `yarn build:electron`

### Version information
riot-web version 1.2.2

**Comment by jryans** [comment]
See https://www.electron.build/code-signing for more about signing. For macOS, you'd need to get an Apple code signing certificate and have that loaded in your keychain.

**Comment by enannos** [comment]
Hi, 
what do we need to do for Windows? Is there a way to bypass the signing?
I cannot build the electron app anymore.
```



  • packaging       platform=win32 arch=x64 electron=7.1.2 appOutDir=electron_app\dist\win-unpacked
Couldn't find signing token in keychain { Error: spawn security ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn security',
  path: 'security',
  spawnargs:
   [ 'find-generic-password', '-s', 'riot_signing_token', '-w' ],
  cmd: 'security find-generic-password -s riot_signing_token -w' }
  ⨯ spawn security ENOENT  stackTrace=
                             Error: spawn security ENOENT
                                 at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
                                 at onErrorNT (internal/child_process.js:415:16)
                                 at process._tickCallback (internal/process/next_tick.js:63:19)
                             From previous event:
                                 at runCallback (timers.js:705:18)
                                 at tryOnImmediate (timers.js:676:5)
                                 at processImmediate (timers.js:658:5)
                             From previous event:
                                 at WinPackager.signApp (C:\Users\XXXXXXXXXXXX\Documents\RIOT\RIOT-TEST\riot-web\node_modules\electron-builder\node_modules\app-builder-lib\src\winPackager.ts:357:27)
                                 at WinPackager.doPack (C:\Users\XXXXXXXXXXXXX\Documents\RIOT\RIOT-TEST\riot-web\node_modules\electron-builder\node_modules\app-builder-lib\src\platformPackager.ts:243:16)
error Command failed with exit code 1.
```

**Comment by t3chguy** [comment]
@enannos this is not a support channel. See https://github.com/vector-im/riot-web/blob/develop/package.json#L186-L197

**Comment by jryans** [comment]
#riot-web:matrix.org is best option for support questions like this.
