### ISSUE TITLE
Difficulty with buidling a linux desktop app

### ISSUE THREAD

**Issue by frankiezafe** [vector-im/riot-web#10307]
**Is your suggestion related to a problem? Please describe.**
It's painfull to complie riot from source:
- matrix-js-sdk is not a submodule
- nodejs version is not specified (8.10 in linux mint official repo, >= 8.15 required during compilation)
- no link to a valid electron installation guide

Once everything is setup and build is done, running `yarn electron` returns this error:

```
yarn electron
yarn run v1.16.0
$ yarn install:electron && electron .
$ install-app-deps
  • please use as subcommand: electron-builder install-app-deps
  • electron-builder version=20.44.4
  • loaded configuration file=package.json ("build" field)
  • installing production dependencies platform=linux arch=x64 appDir=/home/frankiezafe/Downloads/riot-web/electron_app
App threw an error during load
TypeError: protocol.registerStandardSchemes is not a function
    at Object.<anonymous> (/home/frankiezafe/Downloads/riot-web/electron_app/src/electron-main.js:214:10)
    at Module._compile (internal/modules/cjs/loader.js:815:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:677:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:609:12)
    at Function.Module._load (internal/modules/cjs/loader.js:601:3)
    at loadApplicationPackage (/usr/local/lib/node_modules/electron/dist/resources/default_app.asar/main.js:107:12)
    at Object.<anonymous> (/usr/local/lib/node_modules/electron/dist/resources/default_app.asar/main.js:155:5)
    at Module._compile (internal/modules/cjs/loader.js:815:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
Unhandled exception TypeError: protocol.registerStandardSchemes is not a function
    at Object.<anonymous> (/home/frankiezafe/Downloads/riot-web/electron_app/src/electron-main.js:214:10)
    at Module._compile (internal/modules/cjs/loader.js:815:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:677:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:609:12)
    at Function.Module._load (internal/modules/cjs/loader.js:601:3)
    at loadApplicationPackage (/usr/local/lib/node_modules/electron/dist/resources/default_app.asar/main.js:107:12)
    at Object.<anonymous> (/usr/local/lib/node_modules/electron/dist/resources/default_app.asar/main.js:155:5)
    at Module._compile (internal/modules/cjs/loader.js:815:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
```

**Describe the solution you'd like**
a clear succession of commands to compile and install the desktop client on my machine

**Describe alternatives you've considered**
currently running docker build

**Additional context**
Linux Mint 19.1 Cinnamon

**Comment by turt2live** [comment]
We use electron 4, not 5. So `yarn add electron@4` to fix the error at the least.

**Comment by frankiezafe** [comment]
successed to build the standalone app after setting up the dev environment (bottom of the readme) and using `yarn electron-builder` instead
i'll check the version of electron i'm using
in the meanwhile, the deb i've generated is here: https://frankiezafe.itch.io/riot-web-desktop
quite tricky compilation in my pov, but great work by the way!

**Comment by t3chguy** [comment]
> matrix-js-sdk is not a submodule

do you mean git submodules?
For javascript dependencies npm/yarn is definitely recommended over git submodules by convention

> nodejs version is not specified (8.10 in linux mint official repo, >= 8.15 required during compilation)

The README specifies:

> Ensure you have the latest LTS version of Node.js installed.

Which is listed on https://nodejs.org/en/ as 10.16.0, the fact that you got it working with a prior version is fully unsupported.

**Comment by jryans** [comment]
It looks like this was resolved by the reporter.
