### ISSUE TITLE
Pills broken in rooms where the user mentioned is not present

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#10869]
Stacktrace: 

```
Could not retrieve profile data for @snoonet-irc:matrix.org: TypeError: Cannot read property 'length' of undefined
    at Object.getInitialLetter (https://riot.im/develop/bundles/e1fec82aab5564f8769f/bundle.js:55736:18)
    at Object.render (https://riot.im/develop/bundles/e1fec82aab5564f8769f/bundle.js:100316:50)
    at finishClassComponent (https://riot.im/develop/bundles/e1fec82aab5564f8769f/bundle.js:395781:31)
    at updateClassComponent (https://riot.im/develop/bundles/e1fec82aab5564f8769f/bundle.js:395736:24)
    at beginWork$1 (https://riot.im/develop/bundles/e1fec82aab5564f8769f/bundle.js:397247:16)
    at HTMLUnknownElement.callCallback (https://riot.im/develop/bundles/e1fec82aab5564f8769f/bundle.js:379089:14)
    at Object.invokeGuardedCallbackDev (https://riot.im/develop/bundles/e1fec82aab5564f8769f/bundle.js:379139:16)
    at invokeGuardedCallback (https://riot.im/develop/bundles/e1fec82aab5564f8769f/bundle.js:379196:31)
    at beginWork$$1 (https://riot.im/develop/bundles/e1fec82aab5564f8769f/bundle.js:401959:7)
    at performUnitOfWork (https://riot.im/develop/bundles/e1fec82aab5564f8769f/bundle.js:400953:12)
    at workLoopSync (https://riot.im/develop/bundles/e1fec82aab5564f8769f/bundle.js:400927:22)
    at renderRoot (https://riot.im/develop/bundles/e1fec82aab5564f8769f/bundle.js:400620:11)
    at runRootCallback (https://riot.im/develop/bundles/e1fec82aab5564f8769f/bundle.js:400296:20)
    at https://riot.im/develop/bundles/e1fec82aab5564f8769f/bundle.js:390095:24
    at unstable_runWithPriority (https://riot.im/develop/bundles/e1fec82aab5564f8769f/bundle.js:405452:12)
    at runWithPriority$2 (https://riot.im/develop/bundles/e1fec82aab5564f8769f/bundle.js:390047:10)
    at flushSyncCallbackQueueImpl (https://riot.im/develop/bundles/e1fec82aab5564f8769f/bundle.js:390091:7)
    at flushSyncCallbackQueue (https://riot.im/develop/bundles/e1fec82aab5564f8769f/bundle.js:390080:3)
    at scheduleUpdateOnFiber (https://riot.im/develop/bundles/e1fec82aab5564f8769f/bundle.js:400173:9)
    at Object.enqueueSetState (https://riot.im/develop/bundles/e1fec82aab5564f8769f/bundle.js:391842:5)
    at Object../node_modules/react/cjs/react.development.js.Component.setState (https://riot.im/develop/bundles/e1fec82aab5564f8769f/bundle.js:406424:16)
    at https://riot.im/develop/bundles/e1fec82aab5564f8769f/bundle.js:122404:20
```

**Comment by turt2live** [comment]
Looks like this got fixed at some point
