### ISSUE TITLE
Joining a room causes Riot to soft crash, but still joins the room when restarted

### ISSUE THREAD

**Issue by PopeRigby** [vector-im/riot-web#10997]
### Description

Joining a room from a community causes Riot to soft crash, meaning 
* The whole window goes grey (I'm using the dark theme, so it might turn a different color if you're using a different theme.) 
* Riot locks up
* Riot requires a restart 

After Riot is restarted, the room is joined.

### Steps to reproduce

1. Right click on a community and select 'View Community'
2. Select a room from the community's list
3. Wait for Riot to load into the room
4. Observe, as Riot soft crashes and locks up

I expect for Riot to simply load into the room and not go blank.

Logs being sent: Yes

### Version information

- **Platform**: Desktop
- **OS**: Windows 10
- **Version**: 10.0.18362 Build 18362

### Screenshot
![Screenshot (66)](https://user-images.githubusercontent.com/20866468/65838043-8cc11c00-e2b3-11e9-9861-d0908ce958d3.png)

**Comment by eras** [comment]
Hit the issue myself as well. Here's console output (from staging):

```
FlairStore: Emit updateGroupProfile for +community:matrix.org rageshake.js:107:31
FlairStore: Emit updateGroupProfile for +polynomial-supporters:matrix.org rageshake.js:107:31
Switching to room id !whmdEgcaXKdEezpiDw:matrix.org at event undefined rageshake.js:107:31
Looking at $153021467257224OoqOG:matrix.org rageshake.js:107:31
RVS update: !whmdEgcaXKdEezpiDw:matrix.org undefined loading? false joining? false initial? true shouldPeek? true rageshake.js:107:31
Returning cached capabilities rageshake.js:107:31
updateTint from RoomView._gatherTimelinePanelRef rageshake.js:107:31
Tinter.tint from updateTint rageshake.js:107:31
newscreen room/#matrix.fi:matrix.org rageshake.js:107:31
[!whmdEgcaXKdEezpiDw:matrix.org] Current version: 1 rageshake.js:107:31
[!whmdEgcaXKdEezpiDw:matrix.org] Version capability:  
Object { default: "4", available: {…} }
rageshake.js:107:31
Persisting sync data up to  s1110412342_757263662_227097_360008462_212477894_958575_32740462_17516110_58966 indexeddb-worker.js:1:100598
FlairStore: Request group profile of +ircnet:irc.snt.utwente.nl rageshake.js:107:31
FlairStore: Emit updateGroupProfile for +ircnet:irc.snt.utwente.nl rageshake.js:107:31
XML Parsing Error: syntax error
Location: https://riot.im/staging/version?cachebuster=1570124487643
Line Number 1, Column 1: version:1:1
Presence: unavailable rageshake.js:107:31
FlairStore: Request group profile of +rustlang:matrix.org rageshake.js:107:31
FlairStore: Emit updateGroupProfile for +rustlang:matrix.org rageshake.js:107:31
FlairStore: Request group profile of +quadratic-supporters:matrix.org rageshake.js:107:31
FlairStore: Emit updateGroupProfile for +quadratic-supporters:matrix.org rageshake.js:107:31
FlairStore: Request group profile of +oftc:matrix.org rageshake.js:107:31
FlairStore: Emit updateGroupProfile for +oftc:matrix.org rageshake.js:107:31
Persisting sync data up to  s1110418067_757263662_231082_360011370_212480403_958577_32740584_17516219_58966 indexeddb-worker.js:1:100598
Persisting sync data up to  s1110423125_757263662_234915_360013917_212482465_958577_32740755_17516336_58966 indexeddb-worker.js:1:100598
XML Parsing Error: syntax error
Location: https://riot.im/staging/version?cachebuster=1570125087772
Line Number 1, Column 1: version:1:1
Request to reset timeline in room  !MbRaSiMIRhhxDtJENL:maunium.net  viewing: !whmdEgcaXKdEezpiDw:matrix.org rageshake.js:107:31
Persisting sync data up to  s1110429292_757263662_239103_360016579_212484636_958579_32740917_17516418_58968 indexeddb-worker.js:1:100598
Request to reset timeline in room  !MbRaSiMIRhhxDtJENL:maunium.net  viewing: !whmdEgcaXKdEezpiDw:matrix.org rageshake.js:107:31
FlairStore: Request group profile of +freenode:matrix.org rageshake.js:107:31
FlairStore: Emit updateGroupProfile for +freenode:matrix.org rageshake.js:107:31
Persisting sync data up to  s1110435424_757263662_243182_360019187_212486876_958580_32741072_17516497_58969 indexeddb-worker.js:1:100598
XML Parsing Error: syntax error
Location: https://riot.im/staging/version?cachebuster=1570125688187
Line Number 1, Column 1: version:1:1
Presence: online rageshake.js:107:31
Switching to room id !rCWNvpCTZHQkiRYUDE:matrix.org at event null rageshake.js:107:31
RVS update: !rCWNvpCTZHQkiRYUDE:matrix.org undefined loading? false joining? true initial? true shouldPeek? true rageshake.js:107:31
newscreen room/!rCWNvpCTZHQkiRYUDE:matrix.org rageshake.js:107:31
Starting load of AsyncWrapper for modal rageshake.js:107:31
RVS update: !rCWNvpCTZHQkiRYUDE:matrix.org undefined loading? false joining? false initial? undefined shouldPeek? true rageshake.js:107:31
RVS update: !rCWNvpCTZHQkiRYUDE:matrix.org undefined loading? false joining? true initial? undefined shouldPeek? true rageshake.js:107:31
EventTimelineSet.addLiveEvent: ignoring duplicate event $3PeEY3J_71os7D6Nnx0eP8dt88vOBE_3FANqdkb03IA rageshake.js:107:31
Returning cached capabilities rageshake.js:107:31
updateTint from RoomView._gatherTimelinePanelRef rageshake.js:107:31
Tinter.tint from updateTint rageshake.js:107:31
[!rCWNvpCTZHQkiRYUDE:matrix.org] Current version: 5 rageshake.js:107:31
[!rCWNvpCTZHQkiRYUDE:matrix.org] Version capability:  
Object { default: "4", available: {…} }
rageshake.js:107:31
stopping MatrixClient rageshake.js:107:31
SyncApi.stop rageshake.js:107:31
stopping OutgoingRoomKeyRequestManager rageshake.js:107:31
TypeError: "this.container is undefined"
    value resizer.js:186
    value resizer.js:93
    value bundle.js:40
    value bundle.js:40
    Ws React
    unstable_runWithPriority scheduler.production.min.js:20
    React 4
    unstable_runWithPriority scheduler.production.min.js:20
    React 6
    onMyMembership RoomView.js:1015
    emit events.js:151
    value ReEmitter.js:63
    n ReEmitter.js:76
    emit events.js:146
    updateMyMembership room.js:605
    e sync.js:1613
    E runtime.js:62
    _invoke runtime.js:296
    t runtime.js:114
    c bluebird.js:5290
    _promiseFulfilled bluebird.js:2147
    _settlePromise bluebird.js:3364
    _settlePromise0 bluebird.js:3404
    _settlePromises bluebird.js:3484
    p bluebird.js:190
    f bluebird.js:183
    _drainQueues bluebird.js:199
    drainQueues bluebird.js:69
rageshake.js:107:31
Caught /sync error value@https://riot.im/staging/bundles/dd5aab4dd0f13f051ac7/bundle.js:86:1077147
value@https://riot.im/staging/bundles/dd5aab4dd0f13f051ac7/bundle.js:86:1075572
value@https://riot.im/staging/bundles/dd5aab4dd0f13f051ac7/bundle.js:40:811492
value@https://riot.im/staging/bundles/dd5aab4dd0f13f051ac7/bundle.js:40:812033
Ws@https://riot.im/staging/bundles/dd5aab4dd0f13f051ac7/bundle.js:59:94989
t.unstable_runWithPriority@https://riot.im/staging/bundles/dd5aab4dd0f13f051ac7/bundle.js:67:3884
po@https://riot.im/staging/bundles/dd5aab4dd0f13f051ac7/bundle.js:59:41541
Hs@https://riot.im/staging/bundles/dd5aab4dd0f13f051ac7/bundle.js:59:90891
Ms@https://riot.im/staging/bundles/dd5aab4dd0f13f051ac7/bundle.js:59:79559
_o/<@https://riot.im/staging/bundles/dd5aab4dd0f13f051ac7/bundle.js:59:41813
t.unstable_runWithPriority@https://riot.im/staging/bundles/dd5aab4dd0f13f051ac7/bundle.js:67:3884
po@https://riot.im/staging/bundles/dd5aab4dd0f13f051ac7/bundle.js:59:41541
_o@https://riot.im/staging/bundles/dd5aab4dd0f13f051ac7/bundle.js:59:41758
go@https://riot.im/staging/bundles/dd5aab4dd0f13f051ac7/bundle.js:59:41693
Is@https://riot.im/staging/bundles/dd5aab4dd0f13f051ac7/bundle.js:59:78550
enqueueForceUpdate@https://riot.im/staging/bundles/dd5aab4dd0f13f051ac7/bundle.js:59:46823
E.prototype.forceUpdate@https://riot.im/staging/bundles/dd5aab4dd0f13f051ac7/bundle.js:49:1526
onMyMembership@https://riot.im/staging/bundles/dd5aab4dd0f13f051ac7/bundle.js:41:442598
s.prototype.emit@https://riot.im/staging/bundles/dd5aab4dd0f13f051ac7/bundle.js:12:4633
value@https://riot.im/staging/bundles/dd5aab4dd0f13f051ac7/bundle.js:41:203653
n@https://riot.im/staging/bundles/dd5aab4dd0f13f051ac7/bundle.js:41:203810
s.prototype.emit@https://riot.im/staging/bundles/dd5aab4dd0f13f051ac7/bundle.js:12:4576
k.prototype.updateMyMembership@https://riot.im/staging/bundles/dd5aab4dd0f13f051ac7/bundle.js:41:229074
e/<@https://riot.im/staging/bundles/dd5aab4dd0f13f051ac7/bundle.js:72:120883
E@https://riot.im/staging/bundles/dd5aab4dd0f13f051ac7/bundle.js:19:91871
b/i._invoke</<@https://riot.im/staging/bundles/dd5aab4dd0f13f051ac7/bundle.js:19:91659
k/</e[t]@https://riot.im/staging/bundles/dd5aab4dd0f13f051ac7/bundle.js:19:92051
c@https://riot.im/staging/bundles/dd5aab4dd0f13f051ac7/bundle.js:1:81419
o/<[16]</t.exports/f.prototype._promiseFulfilled@https://riot.im/staging/bundles/dd5aab4dd0f13f051ac7/bundle.js:1:38290
o/<[22]</n.exports/D.prototype._settlePromise@https://riot.im/staging/bundles/dd5aab4dd0f13f051ac7/bundle.js:1:55487
o/<[22]</n.exports/D.prototype._settlePromise0@https://riot.im/staging/bundles/dd5aab4dd0f13f051ac7/bundle.js:1:56085
o/<[22]</n.exports/D.prototype._settlePromises@https://riot.im/staging/bundles/dd5aab4dd0f13f051ac7/bundle.js:1:57437
p@https://riot.im/staging/bundles/dd5aab4dd0f13f051ac7/bundle.js:1:9527
f@https://riot.im/staging/bundles/dd5aab4dd0f13f051ac7/bundle.js:1:9466
o/<[2]</l.prototype._drainQueues@https://riot.im/staging/bundles/dd5aab4dd0f13f051ac7/bundle.js:1:10986
l/this.drainQueues@https://riot.im/staging/bundles/dd5aab4dd0f13f051ac7/bundle.js:1:9208
rageshake.js:107:31
Sync no longer running: exiting.
```

**Comment by turt2live** [comment]
That error looks very similar to another error we're seeing elsewhere...

**Comment by jryans** [comment]
@eras Your stack trace above is more similar to https://github.com/vector-im/riot-web/issues/11076, so let's track your variant over there.

**Comment by jryans** [comment]
After joining a room, @PopeRigby's stack trace includes:

```
2019-09-29T19:07:43.186Z E Cannot read property 'children' of undefined
TypeError: Cannot read property 'children' of undefined
    at e.value (vector://vector/webapp/bundles/29e0fd2675e0766674fa/bundle.js:86:1062994)
    at e.value (vector://vector/webapp/bundles/29e0fd2675e0766674fa/bundle.js:86:1061393)
    at t.value (vector://vector/webapp/bundles/29e0fd2675e0766674fa/bundle.js:40:807838)
    at t.value (vector://vector/webapp/bundles/29e0fd2675e0766674fa/bundle.js:40:808379)
    at Ws (vector://vector/webapp/bundles/29e0fd2675e0766674fa/bundle.js:59:94989)
    at t.unstable_runWithPriority (vector://vector/webapp/bundles/29e0fd2675e0766674fa/bundle.js:67:3884)
    at po (vector://vector/webapp/bundles/29e0fd2675e0766674fa/bundle.js:59:41541)
    at Hs (vector://vector/webapp/bundles/29e0fd2675e0766674fa/bundle.js:59:90891)
    at Ms (vector://vector/webapp/bundles/29e0fd2675e0766674fa/bundle.js:59:79559)
    at vector://vector/webapp/bundles/29e0fd2675e0766674fa/bundle.js:59:41813
    at t.unstable_runWithPriority (vector://vector/webapp/bundles/29e0fd2675e0766674fa/bundle.js:67:3884)
    at po (vector://vector/webapp/bundles/29e0fd2675e0766674fa/bundle.js:59:41541)
    at _o (vector://vector/webapp/bundles/29e0fd2675e0766674fa/bundle.js:59:41758)
    at go (vector://vector/webapp/bundles/29e0fd2675e0766674fa/bundle.js:59:41693)
    at Is (vector://vector/webapp/bundles/29e0fd2675e0766674fa/bundle.js:59:78550)
    at Object.enqueueForceUpdate (vector://vector/webapp/bundles/29e0fd2675e0766674fa/bundle.js:59:46823)
2019-09-29T19:07:43.189Z E Caught /sync error TypeError: Cannot read property 'children' of undefined
    at e.value (vector://vector/webapp/bundles/29e0fd2675e0766674fa/bundle.js:86:1062994)
    at e.value (vector://vector/webapp/bundles/29e0fd2675e0766674fa/bundle.js:86:1061393)
    at t.value (vector://vector/webapp/bundles/29e0fd2675e0766674fa/bundle.js:40:807838)
    at t.value (vector://vector/webapp/bundles/29e0fd2675e0766674fa/bundle.js:40:808379)
    at Ws (vector://vector/webapp/bundles/29e0fd2675e0766674fa/bundle.js:59:94989)
    at t.unstable_runWithPriority (vector://vector/webapp/bundles/29e0fd2675e0766674fa/bundle.js:67:3884)
    at po (vector://vector/webapp/bundles/29e0fd2675e0766674fa/bundle.js:59:41541)
    at Hs (vector://vector/webapp/bundles/29e0fd2675e0766674fa/bundle.js:59:90891)
    at Ms (vector://vector/webapp/bundles/29e0fd2675e0766674fa/bundle.js:59:79559)
    at vector://vector/webapp/bundles/29e0fd2675e0766674fa/bundle.js:59:41813
    at t.unstable_runWithPriority (vector://vector/webapp/bundles/29e0fd2675e0766674fa/bundle.js:67:3884)
    at po (vector://vector/webapp/bundles/29e0fd2675e0766674fa/bundle.js:59:41541)
    at _o (vector://vector/webapp/bundles/29e0fd2675e0766674fa/bundle.js:59:41758)
    at go (vector://vector/webapp/bundles/29e0fd2675e0766674fa/bundle.js:59:41693)
    at Is (vector://vector/webapp/bundles/29e0fd2675e0766674fa/bundle.js:59:78550)
    at Object.enqueueForceUpdate (vector://vector/webapp/bundles/29e0fd2675e0766674fa/bundle.js:59:46823)
From previous event:
    at D.B [as _captureStackTrace] (vector://vector/webapp/bundles/29e0fd2675e0766674fa/bundle.js:1:24267)
    at new f (vector://vector/webapp/bundles/29e0fd2675e0766674fa/bundle.js:1:37122)
    at T.<anonymous> (vector://vector/webapp/bundles/29e0fd2675e0766674fa/bundle.js:1:40211)
    at T._processSyncResponse (vector://vector/webapp/bundles/29e0fd2675e0766674fa/bundle.js:72:122926)
    at T.<anonymous> (vector://vector/webapp/bundles/29e0fd2675e0766674fa/bundle.js:72:115189)
    at E (vector://vector/webapp/bundles/29e0fd2675e0766674fa/bundle.js:19:105852)
    at Generator._invoke (vector://vector/webapp/bundles/29e0fd2675e0766674fa/bundle.js:19:105640)
    at Generator.C.forEach.e.<computed> [as next] (vector://vector/webapp/bundles/29e0fd2675e0766674fa/bundle.js:19:106032)
    at Generator.c (vector://vector/webapp/bundles/29e0fd2675e0766674fa/bundle.js:1:81376)
    at f._promiseFulfilled (vector://vector/webapp/bundles/29e0fd2675e0766674fa/bundle.js:1:38247)
    at p (vector://vector/webapp/bundles/29e0fd2675e0766674fa/bundle.js:1:9537)
    at f (vector://vector/webapp/bundles/29e0fd2675e0766674fa/bundle.js:1:9423)
    at l._drainQueues (vector://vector/webapp/bundles/29e0fd2675e0766674fa/bundle.js:1:10943)
    at drainQueues (vector://vector/webapp/bundles/29e0fd2675e0766674fa/bundle.js:1:9165)
```

**Comment by jryans** [comment]
I am not convinced that communities are required to reproduce this. The error seems to be thrown in usage of `Resizer` in the `MainSplit` component, as copied from https://github.com/vector-im/riot-web/issues/11076:

```
2019-10-04T16:48:49.328Z E The above error occurred in the <MainSplit> component:
    in MainSplit (created by RoomView)
    in ErrorBoundary (created by RoomView)
    in main (created by RoomView)
    in RoomView (created by LoggedInView)
    in div (created by LoggedInView)
    in DragDropContext (created by LoggedInView)
    in div (created by LoggedInView)
    in LoggedInView (created by MatrixChat)
    in ErrorBoundary (created by MatrixChat)
    in MatrixChat
```

**Comment by PopeRigby** [comment]
> I am not convinced that communities are required to reproduce this.

You're probably right about that. I'll test later.
