### ISSUE TITLE
Cannot read property 'getGroups' of null in _makeGroupInviteTiles

### ISSUE THREAD

**Issue by jryans** [vector-im/riot-web#11078]
```
2019-10-06T14:27:39.575Z E Cannot read property 'getGroups' of null
TypeError: Cannot read property 'getGroups' of null
    at t._makeGroupInviteTiles (vector://vector/webapp/bundles/a6f8076a857e57b3741a/bundle.js:118:74955)
    at t.render (vector://vector/webapp/bundles/a6f8076a857e57b3741a/bundle.js:118:77220)
    at ya (vector://vector/webapp/bundles/a6f8076a857e57b3741a/bundle.js:59:65582)
    at va (vector://vector/webapp/bundles/a6f8076a857e57b3741a/bundle.js:59:65377)
    at Zs (vector://vector/webapp/bundles/a6f8076a857e57b3741a/bundle.js:59:99683)
    at qs (vector://vector/webapp/bundles/a6f8076a857e57b3741a/bundle.js:59:83963)
    at Gs (vector://vector/webapp/bundles/a6f8076a857e57b3741a/bundle.js:59:80988)
    at Ms (vector://vector/webapp/bundles/a6f8076a857e57b3741a/bundle.js:59:79559)
    at vector://vector/webapp/bundles/a6f8076a857e57b3741a/bundle.js:59:41813
    at t.unstable_runWithPriority (vector://vector/webapp/bundles/a6f8076a857e57b3741a/bundle.js:67:3884)
    at po (vector://vector/webapp/bundles/a6f8076a857e57b3741a/bundle.js:59:41541)
    at _o (vector://vector/webapp/bundles/a6f8076a857e57b3741a/bundle.js:59:41758)
    at go (vector://vector/webapp/bundles/a6f8076a857e57b3741a/bundle.js:59:41693)
    at Pe (vector://vector/webapp/bundles/a6f8076a857e57b3741a/bundle.js:59:109447)
    at Un (vector://vector/webapp/bundles/a6f8076a857e57b3741a/bundle.js:59:31680)
    at Bn (vector://vector/webapp/bundles/a6f8076a857e57b3741a/bundle.js:59:31397)
2019-10-06T14:27:39.575Z E The above error occured while React was rendering the following components: 
    in RoomList
    in aside
    in div
    in LeftPanel
    in div
    in t
    in div
    in LoggedInView
    in t
    in MatrixChat
```

**Comment by jryans** [comment]
This appears to be one example of an entire class of errors of the form:

1. Log out, causing the client peg to become `null`
2. Some async process (event handler, timeout, request, etc.) tries to use the client in a component before it unmounts, triggering a soft crash
3. Several moments later, the app actually unmounts
