### ISSUE TITLE
Soft react crash instance (twice)

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#11091]
First errors:
```
2019-10-08T16:36:38.770Z E Unable to find a DOM node for "2". This is often because of forgetting to add `props.attributes` to a custom component.
Error: Unable to find a DOM node for "2". This is often because of forgetting to add `props.attributes` to a custom component.
    at $e (https://riot.im/app/bundles/a6f8076a857e57b3741a/bundle.js:118:286932)
    at Qe (https://riot.im/app/bundles/a6f8076a857e57b3741a/bundle.js:118:287167)
    at Je (https://riot.im/app/bundles/a6f8076a857e57b3741a/bundle.js:118:287560)
    at t.r.updateSelection (https://riot.im/app/bundles/a6f8076a857e57b3741a/bundle.js:118:291892)
    at t.value (https://riot.im/app/bundles/a6f8076a857e57b3741a/bundle.js:118:293817)
    at Ws (https://riot.im/app/bundles/a6f8076a857e57b3741a/bundle.js:59:94989)
    at t.unstable_runWithPriority (https://riot.im/app/bundles/a6f8076a857e57b3741a/bundle.js:67:3884)
    at po (https://riot.im/app/bundles/a6f8076a857e57b3741a/bundle.js:59:41541)
    at Hs (https://riot.im/app/bundles/a6f8076a857e57b3741a/bundle.js:59:90891)
    at Ms (https://riot.im/app/bundles/a6f8076a857e57b3741a/bundle.js:59:79559)
    at https://riot.im/app/bundles/a6f8076a857e57b3741a/bundle.js:59:41813
    at t.unstable_runWithPriority (https://riot.im/app/bundles/a6f8076a857e57b3741a/bundle.js:67:3884)
    at po (https://riot.im/app/bundles/a6f8076a857e57b3741a/bundle.js:59:41541)
    at _o (https://riot.im/app/bundles/a6f8076a857e57b3741a/bundle.js:59:41758)
    at go (https://riot.im/app/bundles/a6f8076a857e57b3741a/bundle.js:59:41693)
    at Pe (https://riot.im/app/bundles/a6f8076a857e57b3741a/bundle.js:59:109447)
2019-10-08T16:36:38.818Z E Unable to find a DOM node for "2". This is often because of forgetting to add `props.attributes` to a custom component.
Error: Unable to find a DOM node for "2". This is often because of forgetting to add `props.attributes` to a custom component.
    at $e (https://riot.im/app/bundles/a6f8076a857e57b3741a/bundle.js:118:286932)
    at Qe (https://riot.im/app/bundles/a6f8076a857e57b3741a/bundle.js:118:287167)
    at Je (https://riot.im/app/bundles/a6f8076a857e57b3741a/bundle.js:118:287560)
    at t.r.updateSelection (https://riot.im/app/bundles/a6f8076a857e57b3741a/bundle.js:118:291892)
    at t.value (https://riot.im/app/bundles/a6f8076a857e57b3741a/bundle.js:118:293817)
    at Ws (https://riot.im/app/bundles/a6f8076a857e57b3741a/bundle.js:59:94989)
    at t.unstable_runWithPriority (https://riot.im/app/bundles/a6f8076a857e57b3741a/bundle.js:67:3884)
    at po (https://riot.im/app/bundles/a6f8076a857e57b3741a/bundle.js:59:41541)
    at Hs (https://riot.im/app/bundles/a6f8076a857e57b3741a/bundle.js:59:90891)
    at Ms (https://riot.im/app/bundles/a6f8076a857e57b3741a/bundle.js:59:79559)
    at https://riot.im/app/bundles/a6f8076a857e57b3741a/bundle.js:59:41813
    at t.unstable_runWithPriority (https://riot.im/app/bundles/a6f8076a857e57b3741a/bundle.js:67:3884)
    at po (https://riot.im/app/bundles/a6f8076a857e57b3741a/bundle.js:59:41541)
    at _o (https://riot.im/app/bundles/a6f8076a857e57b3741a/bundle.js:59:41758)
    at go (https://riot.im/app/bundles/a6f8076a857e57b3741a/bundle.js:59:41693)
    at Pe (https://riot.im/app/bundles/a6f8076a857e57b3741a/bundle.js:59:109447)
2019-10-08T16:36:38.819Z E The above error occured while React was rendering the following components: 
    in t
    in t
    in div
    in div
    in t
    in div
    in div
    in div
    in t
    in div
    in div
    in t
    in t
    in main
    in RoomView
    in div
    in t
    in div
    in LoggedInView
    in t
    in MatrixChat
2019-10-08T16:36:54.708Z I Routing URL  https://riot.im/app/#/login
```

Second set (which apparently caused the rageshake):
```
2019-10-08T16:37:26.754Z E Unable to find a DOM node for "8". This is often because of forgetting to add `props.attributes` to a custom component.
Error: Unable to find a DOM node for "8". This is often because of forgetting to add `props.attributes` to a custom component.
    at $e (https://riot.im/app/bundles/a6f8076a857e57b3741a/bundle.js:118:286932)
    at Qe (https://riot.im/app/bundles/a6f8076a857e57b3741a/bundle.js:118:287167)
    at Je (https://riot.im/app/bundles/a6f8076a857e57b3741a/bundle.js:118:287560)
    at t.r.updateSelection (https://riot.im/app/bundles/a6f8076a857e57b3741a/bundle.js:118:291892)
    at t.value (https://riot.im/app/bundles/a6f8076a857e57b3741a/bundle.js:118:293817)
    at Ws (https://riot.im/app/bundles/a6f8076a857e57b3741a/bundle.js:59:94989)
    at t.unstable_runWithPriority (https://riot.im/app/bundles/a6f8076a857e57b3741a/bundle.js:67:3884)
    at po (https://riot.im/app/bundles/a6f8076a857e57b3741a/bundle.js:59:41541)
    at Hs (https://riot.im/app/bundles/a6f8076a857e57b3741a/bundle.js:59:90891)
    at Ms (https://riot.im/app/bundles/a6f8076a857e57b3741a/bundle.js:59:79559)
    at https://riot.im/app/bundles/a6f8076a857e57b3741a/bundle.js:59:41813
    at t.unstable_runWithPriority (https://riot.im/app/bundles/a6f8076a857e57b3741a/bundle.js:67:3884)
    at po (https://riot.im/app/bundles/a6f8076a857e57b3741a/bundle.js:59:41541)
    at _o (https://riot.im/app/bundles/a6f8076a857e57b3741a/bundle.js:59:41758)
    at go (https://riot.im/app/bundles/a6f8076a857e57b3741a/bundle.js:59:41693)
    at Pe (https://riot.im/app/bundles/a6f8076a857e57b3741a/bundle.js:59:109447)
2019-10-08T16:37:26.792Z E Unable to find a DOM node for "8". This is often because of forgetting to add `props.attributes` to a custom component.
Error: Unable to find a DOM node for "8". This is often because of forgetting to add `props.attributes` to a custom component.
    at $e (https://riot.im/app/bundles/a6f8076a857e57b3741a/bundle.js:118:286932)
    at Qe (https://riot.im/app/bundles/a6f8076a857e57b3741a/bundle.js:118:287167)
    at Je (https://riot.im/app/bundles/a6f8076a857e57b3741a/bundle.js:118:287560)
    at t.r.updateSelection (https://riot.im/app/bundles/a6f8076a857e57b3741a/bundle.js:118:291892)
    at t.value (https://riot.im/app/bundles/a6f8076a857e57b3741a/bundle.js:118:293817)
    at Ws (https://riot.im/app/bundles/a6f8076a857e57b3741a/bundle.js:59:94989)
    at t.unstable_runWithPriority (https://riot.im/app/bundles/a6f8076a857e57b3741a/bundle.js:67:3884)
    at po (https://riot.im/app/bundles/a6f8076a857e57b3741a/bundle.js:59:41541)
    at Hs (https://riot.im/app/bundles/a6f8076a857e57b3741a/bundle.js:59:90891)
    at Ms (https://riot.im/app/bundles/a6f8076a857e57b3741a/bundle.js:59:79559)
    at https://riot.im/app/bundles/a6f8076a857e57b3741a/bundle.js:59:41813
    at t.unstable_runWithPriority (https://riot.im/app/bundles/a6f8076a857e57b3741a/bundle.js:67:3884)
    at po (https://riot.im/app/bundles/a6f8076a857e57b3741a/bundle.js:59:41541)
    at _o (https://riot.im/app/bundles/a6f8076a857e57b3741a/bundle.js:59:41758)
    at go (https://riot.im/app/bundles/a6f8076a857e57b3741a/bundle.js:59:41693)
    at Pe (https://riot.im/app/bundles/a6f8076a857e57b3741a/bundle.js:59:109447)
2019-10-08T16:37:26.792Z E The above error occured while React was rendering the following components: 
    in t
    in t
    in div
    in div
    in t
    in div
    in div
    in div
    in t
    in div
    in div
    in t
    in t
    in main
    in RoomView
    in div
    in t
    in div
    in LoggedInView
    in t
    in MatrixChat
```

**Comment by turt2live** [comment]
This bug came from an Android device, which we don't support - closing as invalid.
