### ISSUE TITLE
getCaret soft crash with null node

### ISSUE THREAD

**Issue by jryans** [vector-im/riot-web#11110]
A rageshake was submitted with the following React soft crash, which translates to `getCaret` in `dom.js` with a null `node`:

```
2019-10-10T08:33:31.583Z E Cannot read property 'textContent' of null
TypeError: Cannot read property 'textContent' of null
    at vector://vector/webapp/bundles/a6f8076a857e57b3741a/bundle.js:41:88531
    at l (vector://vector/webapp/bundles/a6f8076a857e57b3741a/bundle.js:41:88716)
    at t.getCaretOffsetAndText (vector://vector/webapp/bundles/a6f8076a857e57b3741a/bundle.js:41:87179)
    at t.value (vector://vector/webapp/bundles/a6f8076a857e57b3741a/bundle.js:101:379874)
    at vector://vector/webapp/bundles/a6f8076a857e57b3741a/bundle.js:59:72627
    at Ba (vector://vector/webapp/bundles/a6f8076a857e57b3741a/bundle.js:59:72668)
    at Va (vector://vector/webapp/bundles/a6f8076a857e57b3741a/bundle.js:59:74794)
    at Ws (vector://vector/webapp/bundles/a6f8076a857e57b3741a/bundle.js:59:93162)
    at t.unstable_runWithPriority (vector://vector/webapp/bundles/a6f8076a857e57b3741a/bundle.js:67:3884)
    at po (vector://vector/webapp/bundles/a6f8076a857e57b3741a/bundle.js:59:41541)
    at Hs (vector://vector/webapp/bundles/a6f8076a857e57b3741a/bundle.js:59:90891)
    at Ms (vector://vector/webapp/bundles/a6f8076a857e57b3741a/bundle.js:59:79559)
    at vector://vector/webapp/bundles/a6f8076a857e57b3741a/bundle.js:59:41813
    at t.unstable_runWithPriority (vector://vector/webapp/bundles/a6f8076a857e57b3741a/bundle.js:67:3884)
    at po (vector://vector/webapp/bundles/a6f8076a857e57b3741a/bundle.js:59:41541)
    at _o (vector://vector/webapp/bundles/a6f8076a857e57b3741a/bundle.js:59:41758)
2019-10-10T08:33:31.640Z E Cannot read property 'textContent' of null
TypeError: Cannot read property 'textContent' of null
    at vector://vector/webapp/bundles/a6f8076a857e57b3741a/bundle.js:41:88531
    at l (vector://vector/webapp/bundles/a6f8076a857e57b3741a/bundle.js:41:88716)
    at t.getCaretOffsetAndText (vector://vector/webapp/bundles/a6f8076a857e57b3741a/bundle.js:41:87179)
    at t.value (vector://vector/webapp/bundles/a6f8076a857e57b3741a/bundle.js:101:379874)
    at vector://vector/webapp/bundles/a6f8076a857e57b3741a/bundle.js:59:72627
    at Ba (vector://vector/webapp/bundles/a6f8076a857e57b3741a/bundle.js:59:72668)
    at Va (vector://vector/webapp/bundles/a6f8076a857e57b3741a/bundle.js:59:74794)
    at Ws (vector://vector/webapp/bundles/a6f8076a857e57b3741a/bundle.js:59:93162)
    at t.unstable_runWithPriority (vector://vector/webapp/bundles/a6f8076a857e57b3741a/bundle.js:67:3884)
    at po (vector://vector/webapp/bundles/a6f8076a857e57b3741a/bundle.js:59:41541)
    at Hs (vector://vector/webapp/bundles/a6f8076a857e57b3741a/bundle.js:59:90891)
    at Ms (vector://vector/webapp/bundles/a6f8076a857e57b3741a/bundle.js:59:79559)
    at vector://vector/webapp/bundles/a6f8076a857e57b3741a/bundle.js:59:41813
    at t.unstable_runWithPriority (vector://vector/webapp/bundles/a6f8076a857e57b3741a/bundle.js:67:3884)
    at po (vector://vector/webapp/bundles/a6f8076a857e57b3741a/bundle.js:59:41541)
    at _o (vector://vector/webapp/bundles/a6f8076a857e57b3741a/bundle.js:59:41758)
2019-10-10T08:33:31.640Z E The above error occured while React was rendering the following components: 
    in t
    in TextualBody
    in MessageEvent
    in div
    in div
    in EventTile
    in li
    in ol
    in div
    in div
    in div
    in t
    in ScrollPanel
    in MessagePanel
    in TimelinePanel
    in div
    in div
    in div
    in t
    in t
    in main
    in RoomView
    in div
    in t
    in div
    in LoggedInView
    in t
    in MatrixChat
```

**Comment by bwindels** [comment]
I suspect this is happening in the edit composer, while unmounting: https://github.com/matrix-org/matrix-react-sdk/blob/61654a338c67578d41318d6debb2f90ccf6a760e/src/components/views/rooms/EditMessageComposer.js#L214
