### ISSUE TITLE
Rapidly changing rooms can soft-crash react

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#11120]
```
2019-10-11T10:22:18.662Z E Invalid arguments for `getRelationsForEvent`
Error: Invalid arguments for `getRelationsForEvent`
    at d.getRelationsForEvent (http://127.0.0.1:8084/bundles/47654951f59a9322430d/bundle.js:40:144250)
    at t.getRelationsForEvent (http://127.0.0.1:8084/bundles/47654951f59a9322430d/bundle.js:99:169821)
    at t.getReactions (http://127.0.0.1:8084/bundles/47654951f59a9322430d/bundle.js:109:17234)
    at t.getInitialState (http://127.0.0.1:8084/bundles/47654951f59a9322430d/bundle.js:109:12290)
    at new EventTile (http://127.0.0.1:8084/bundles/47654951f59a9322430d/bundle.js:72:236335)
    at Ko (http://127.0.0.1:8084/bundles/47654951f59a9322430d/bundle.js:59:47183)
    at va (http://127.0.0.1:8084/bundles/47654951f59a9322430d/bundle.js:59:62752)
    at Zs (http://127.0.0.1:8084/bundles/47654951f59a9322430d/bundle.js:59:99683)
    at qs (http://127.0.0.1:8084/bundles/47654951f59a9322430d/bundle.js:59:83963)
    at Gs (http://127.0.0.1:8084/bundles/47654951f59a9322430d/bundle.js:59:80988)
    at Ms (http://127.0.0.1:8084/bundles/47654951f59a9322430d/bundle.js:59:79559)
    at http://127.0.0.1:8084/bundles/47654951f59a9322430d/bundle.js:59:41813
    at t.unstable_runWithPriority (http://127.0.0.1:8084/bundles/47654951f59a9322430d/bundle.js:67:3884)
    at po (http://127.0.0.1:8084/bundles/47654951f59a9322430d/bundle.js:59:41541)
    at _o (http://127.0.0.1:8084/bundles/47654951f59a9322430d/bundle.js:59:41758)
    at go (http://127.0.0.1:8084/bundles/47654951f59a9322430d/bundle.js:59:41693)
    at As (http://127.0.0.1:8084/bundles/47654951f59a9322430d/bundle.js:59:78550)
    at Object.enqueueSetState (http://127.0.0.1:8084/bundles/47654951f59a9322430d/bundle.js:59:46506)
    at t.E.setState (http://127.0.0.1:8084/bundles/47654951f59a9322430d/bundle.js:49:1439)
    at http://127.0.0.1:8084/bundles/47654951f59a9322430d/bundle.js:99:66472
    at c (http://127.0.0.1:8084/bundles/47654951f59a9322430d/bundle.js:1:143441)
    at D._settlePromiseFromHandler (http://127.0.0.1:8084/bundles/47654951f59a9322430d/bundle.js:1:116608)
    at D._settlePromise (http://127.0.0.1:8084/bundles/47654951f59a9322430d/bundle.js:1:117408)
    at D._settlePromiseCtx (http://127.0.0.1:8084/bundles/47654951f59a9322430d/bundle.js:1:117914)
    at http://127.0.0.1:8084/bundles/47654951f59a9322430d/bundle.js:1:72750
2019-10-11T10:22:18.672Z E Invalid arguments for `getRelationsForEvent`
Error: Invalid arguments for `getRelationsForEvent`
    at d.getRelationsForEvent (http://127.0.0.1:8084/bundles/47654951f59a9322430d/bundle.js:40:144250)
    at t.getRelationsForEvent (http://127.0.0.1:8084/bundles/47654951f59a9322430d/bundle.js:99:169821)
    at t.getReactions (http://127.0.0.1:8084/bundles/47654951f59a9322430d/bundle.js:109:17234)
    at t.getInitialState (http://127.0.0.1:8084/bundles/47654951f59a9322430d/bundle.js:109:12290)
    at new EventTile (http://127.0.0.1:8084/bundles/47654951f59a9322430d/bundle.js:72:236335)
    at Ko (http://127.0.0.1:8084/bundles/47654951f59a9322430d/bundle.js:59:47183)
    at va (http://127.0.0.1:8084/bundles/47654951f59a9322430d/bundle.js:59:62752)
    at Zs (http://127.0.0.1:8084/bundles/47654951f59a9322430d/bundle.js:59:99683)
    at qs (http://127.0.0.1:8084/bundles/47654951f59a9322430d/bundle.js:59:83963)
    at Gs (http://127.0.0.1:8084/bundles/47654951f59a9322430d/bundle.js:59:80988)
    at Ms (http://127.0.0.1:8084/bundles/47654951f59a9322430d/bundle.js:59:79559)
    at http://127.0.0.1:8084/bundles/47654951f59a9322430d/bundle.js:59:41813
    at t.unstable_runWithPriority (http://127.0.0.1:8084/bundles/47654951f59a9322430d/bundle.js:67:3884)
    at po (http://127.0.0.1:8084/bundles/47654951f59a9322430d/bundle.js:59:41541)
    at _o (http://127.0.0.1:8084/bundles/47654951f59a9322430d/bundle.js:59:41758)
    at go (http://127.0.0.1:8084/bundles/47654951f59a9322430d/bundle.js:59:41693)
    at As (http://127.0.0.1:8084/bundles/47654951f59a9322430d/bundle.js:59:78550)
    at Object.enqueueSetState (http://127.0.0.1:8084/bundles/47654951f59a9322430d/bundle.js:59:46506)
    at t.E.setState (http://127.0.0.1:8084/bundles/47654951f59a9322430d/bundle.js:49:1439)
    at http://127.0.0.1:8084/bundles/47654951f59a9322430d/bundle.js:99:66472
    at c (http://127.0.0.1:8084/bundles/47654951f59a9322430d/bundle.js:1:143441)
    at D._settlePromiseFromHandler (http://127.0.0.1:8084/bundles/47654951f59a9322430d/bundle.js:1:116608)
    at D._settlePromise (http://127.0.0.1:8084/bundles/47654951f59a9322430d/bundle.js:1:117408)
    at D._settlePromiseCtx (http://127.0.0.1:8084/bundles/47654951f59a9322430d/bundle.js:1:117914)
    at http://127.0.0.1:8084/bundles/47654951f59a9322430d/bundle.js:1:72750
2019-10-11T10:22:18.672Z E The above error occured while React was rendering the following components: 
    in EventTile
    in li
    in ol
    in div
    in div
    in div
    in t
    in ScrollPanel
    in MessagePanel
    in TimelinePanel
    in div
    in div
    in div
    in t
    in t
    in main
    in RoomView
    in div
    in t
    in div
    in LoggedInView
    in t
    in MatrixChat
```

**Comment by jryans** [comment]
This appears to be a new soft crash issue (doesn't match any of the past ones).

**Comment by jryans** [comment]
This seems to suggest we were creating a new `EventTile`, and it had a `mxEvent` object, but calling `getId()` on the event returned a falsy value. How is that possible...? 🤔

**Comment by t3chguy** [comment]
Those were my findings last week also :((
Mentioned them in standup but did not document them here, makes very little sense

**Comment by jryans** [comment]
We'll start by adding a diagnostic log to better understand what's happening here.

@turt2live, please continue to send rageshakes when this happens so we can see what we learn from the logging.

**Comment by jryans** [comment]
For now, I'll take this off the project board until we get a new rageshake.

**Comment by t3chguy** [comment]
I tried to have a cursory glance at this but without having this occur locally I'm stuck, passing this back off to you as you're assigned @jryans - see above-referenced rageshake

**Comment by dbkr** [comment]
I appear to be getting this, albeit by creating a room and then refreshing the client shortly afterwards. The stack trace you wanted is:

```
Stacktrace for https://github.com/vector-im/riot-web/issues/11120 
    in EventTile (created by MessagePanel)
    in MessagePanel (created by TimelinePanel)
    in TimelinePanel (created by RoomView)
    in RoomView (created by LoggedInView)
    in LoggedInView (created by MatrixChat)
    in MatrixChat
```

although I'm not sure what else we would have expected.

**Comment by jryans** [comment]
Removed assignment, as I'm not sure I'll have time any more, but we should definitely figure this out.
