### ISSUE TITLE
Cannot make calls with Catalina on Desktop

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#11151]
```
2019-10-16T11:21:04.301Z I placeVideoCall
2019-10-16T11:21:04.403Z I _maybeGotUserMediaForInvite -> video
2019-10-16T11:21:04.403Z I Failed to getUserMedia: NotReadableError
2019-10-16T11:21:04.403Z I stopAllMedia (stream=%s) 
2019-10-16T11:21:04.403Z E Call error: Couldn't start capturing media! Is your microphone set up and does this app have permission?
Error: Couldn't start capturing media! Is your microphone set up and does this app have permission?
    at S (vector://vector/webapp/bundles/a6f8076a857e57b3741a/bundle.js:19:124402)
    at c._getUserMediaFailed (vector://vector/webapp/bundles/a6f8076a857e57b3741a/bundle.js:19:119924)
    at c._maybeGotUserMediaForInvite (vector://vector/webapp/bundles/a6f8076a857e57b3741a/bundle.js:19:116371)
    at vector://vector/webapp/bundles/a6f8076a857e57b3741a/bundle.js:19:126335
```

**Comment by dbkr** [comment]
I guess we should try specifying an entitlements file with camera & mic keys in it. Relevant links:

 * https://github.com/electron/electron-osx-sign/blob/master/default.entitlements.darwin.plist
 * https://www.electron.build/configuration/mac
 * ...was hoping to find a list of the relevant entitlements for camera & mic access but a couple of minutes of searching has not turned them up. Probably use Xcode to make en entitlements file.
