### ISSUE TITLE
Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#11297]
```
2019-11-02T18:00:55.987Z E Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at Va (https://riot.im/app/bundles/2399aff5932e52cc7d90/bundle.js:59:74520)
    at Ws (https://riot.im/app/bundles/2399aff5932e52cc7d90/bundle.js:59:93162)
    at t.unstable_runWithPriority (https://riot.im/app/bundles/2399aff5932e52cc7d90/bundle.js:67:3884)
    at po (https://riot.im/app/bundles/2399aff5932e52cc7d90/bundle.js:59:41541)
    at Hs (https://riot.im/app/bundles/2399aff5932e52cc7d90/bundle.js:59:90891)
    at Ms (https://riot.im/app/bundles/2399aff5932e52cc7d90/bundle.js:59:79559)
    at https://riot.im/app/bundles/2399aff5932e52cc7d90/bundle.js:59:41813
    at t.unstable_runWithPriority (https://riot.im/app/bundles/2399aff5932e52cc7d90/bundle.js:67:3884)
    at po (https://riot.im/app/bundles/2399aff5932e52cc7d90/bundle.js:59:41541)
    at _o (https://riot.im/app/bundles/2399aff5932e52cc7d90/bundle.js:59:41758)
    at go (https://riot.im/app/bundles/2399aff5932e52cc7d90/bundle.js:59:41693)
    at Is (https://riot.im/app/bundles/2399aff5932e52cc7d90/bundle.js:59:78550)
    at Object.enqueueSetState (https://riot.im/app/bundles/2399aff5932e52cc7d90/bundle.js:59:46506)
    at t.E.setState (https://riot.im/app/bundles/2399aff5932e52cc7d90/bundle.js:49:1439)
    at https://riot.im/app/bundles/2399aff5932e52cc7d90/bundle.js:41:434805
    at c (https://riot.im/app/bundles/2399aff5932e52cc7d90/bundle.js:1:81419)
2019-11-02T18:00:55.997Z E Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at Va (https://riot.im/app/bundles/2399aff5932e52cc7d90/bundle.js:59:74520)
    at Ws (https://riot.im/app/bundles/2399aff5932e52cc7d90/bundle.js:59:93162)
    at t.unstable_runWithPriority (https://riot.im/app/bundles/2399aff5932e52cc7d90/bundle.js:67:3884)
    at po (https://riot.im/app/bundles/2399aff5932e52cc7d90/bundle.js:59:41541)
    at Hs (https://riot.im/app/bundles/2399aff5932e52cc7d90/bundle.js:59:90891)
    at Ms (https://riot.im/app/bundles/2399aff5932e52cc7d90/bundle.js:59:79559)
    at https://riot.im/app/bundles/2399aff5932e52cc7d90/bundle.js:59:41813
    at t.unstable_runWithPriority (https://riot.im/app/bundles/2399aff5932e52cc7d90/bundle.js:67:3884)
    at po (https://riot.im/app/bundles/2399aff5932e52cc7d90/bundle.js:59:41541)
    at _o (https://riot.im/app/bundles/2399aff5932e52cc7d90/bundle.js:59:41758)
    at go (https://riot.im/app/bundles/2399aff5932e52cc7d90/bundle.js:59:41693)
    at Is (https://riot.im/app/bundles/2399aff5932e52cc7d90/bundle.js:59:78550)
    at Object.enqueueSetState (https://riot.im/app/bundles/2399aff5932e52cc7d90/bundle.js:59:46506)
    at t.E.setState (https://riot.im/app/bundles/2399aff5932e52cc7d90/bundle.js:49:1439)
    at https://riot.im/app/bundles/2399aff5932e52cc7d90/bundle.js:41:434805
    at c (https://riot.im/app/bundles/2399aff5932e52cc7d90/bundle.js:1:81419)
2019-11-02T18:00:55.998Z E The above error occured while React was rendering the following components: 
    in h3
    in div
    in div
    in RoomPreviewBar
    in t
    in div
    in RoomView
    in div
    in t
    in div
    in LoggedInView
    in t
    in MatrixChat
```

**Comment by turt2live** [comment]
The error came from an Android device (just noticed that), which is unsupported. Additionally, without further information I can't reproduce this.
