### ISSUE TITLE
Gemini can break a room / something about event tiles

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#11352]
```
2019-11-08T16:35:50.134Z W %cUnhandled rejection Error: ScrollPanel._getScrollNode called before gemini ref collected
    at Object._getScrollNode (https://riot.im/develop/bundles/dda9bd59e426e82eac8e/bundle.js:91143:19)
    at Object._callee2$ (https://riot.im/develop/bundles/dda9bd59e426e82eac8e/bundle.js:90944:43)
    at tryCatch (https://riot.im/develop/bundles/dda9bd59e426e82eac8e/bundle.js:195284:40)
    at Generator.invoke [as _invoke] (https://riot.im/develop/bundles/dda9bd59e426e82eac8e/bundle.js:195518:22)
    at Generator.prototype.<computed> [as next] (https://riot.im/develop/bundles/dda9bd59e426e82eac8e/bundle.js:195336:21)
From previous event:
    at Object._restoreSavedScrollState (https://riot.im/develop/bundles/dda9bd59e426e82eac8e/bundle.js:90994:26)
    at Object.checkScroll (https://riot.im/develop/bundles/dda9bd59e426e82eac8e/bundle.js:90459:14)
    at Object.onResize (https://riot.im/develop/bundles/dda9bd59e426e82eac8e/bundle.js:90446:14)
    at ResizeNotifier.emit (https://riot.im/develop/bundles/dda9bd59e426e82eac8e/bundle.js:368385:7)
    at ResizeNotifier.<anonymous> (https://riot.im/develop/bundles/dda9bd59e426e82eac8e/bundle.js:191545:26)
    at invokeFunc (https://riot.im/develop/bundles/dda9bd59e426e82eac8e/bundle.js:277021:23)
    at leadingEdge (https://riot.im/develop/bundles/dda9bd59e426e82eac8e/bundle.js:277031:26)
    at ResizeNotifier.debounced [as _throttledMiddlePanel] (https://riot.im/develop/bundles/dda9bd59e426e82eac8e/bundle.js:277098:20)
    at ResizeNotifier.notifyRightHandleResized (https://riot.im/develop/bundles/dda9bd59e426e82eac8e/bundle.js:191571:18)
    at MainSplit._onResized (https://riot.im/develop/bundles/dda9bd59e426e82eac8e/bundle.js:82264:43)
    at ResizeItem.setSize (https://riot.im/develop/bundles/dda9bd59e426e82eac8e/bundle.js:179881:17)
    at FixedDistributor.resize (https://riot.im/develop/bundles/dda9bd59e426e82eac8e/bundle.js:179006:23)
    at MainSplit._createResizer (https://riot.im/develop/bundles/dda9bd59e426e82eac8e/bundle.js:82283:36)
    at MainSplit.componentDidMount (https://riot.im/develop/bundles/dda9bd59e426e82eac8e/bundle.js:82297:22)
    at commitLifeCycles (https://riot.im/develop/bundles/dda9bd59e426e82eac8e/bundle.js:408377:22)
    at commitLayoutEffects (https://riot.im/develop/bundles/dda9bd59e426e82eac8e/bundle.js:411141:7)
    at HTMLUnknownElement.callCallback (https://riot.im/develop/bundles/dda9bd59e426e82eac8e/bundle.js:388675:14)
    at Object.invokeGuardedCallbackDev (https://riot.im/develop/bundles/dda9bd59e426e82eac8e/bundle.js:388725:16)
    at invokeGuardedCallback (https://riot.im/develop/bundles/dda9bd59e426e82eac8e/bundle.js:388782:31)
    at commitRootImpl (https://riot.im/develop/bundles/dda9bd59e426e82eac8e/bundle.js:410913:9)
    at unstable_runWithPriority (https://riot.im/develop/bundles/dda9bd59e426e82eac8e/bundle.js:419122:12)
    at runWithPriority$2 (https://riot.im/develop/bundles/dda9bd59e426e82eac8e/bundle.js:399633:10)
    at commitRoot (https://riot.im/develop/bundles/dda9bd59e426e82eac8e/bundle.js:410742:3)
    at runRootCallback (https://riot.im/develop/bundles/dda9bd59e426e82eac8e/bundle.js:409882:20)
    at https://riot.im/develop/bundles/dda9bd59e426e82eac8e/bundle.js:399681:24
    at unstable_runWithPriority (https://riot.im/develop/bundles/dda9bd59e426e82eac8e/bundle.js:419122:12)
    at runWithPriority$2 (https://riot.im/develop/bundles/dda9bd59e426e82eac8e/bundle.js:399633:10)
    at flushSyncCallbackQueueImpl (https://riot.im/develop/bundles/dda9bd59e426e82eac8e/bundle.js:399677:7)
    at flushSyncCallbackQueue (https://riot.im/develop/bundles/dda9bd59e426e82eac8e/bundle.js:399666:3)
    at scheduleUpdateOnFiber (https://riot.im/develop/bundles/dda9bd59e426e82eac8e/bundle.js:409759:9)
    at Object.enqueueSetState (https://riot.im/develop/bundles/dda9bd59e426e82eac8e/bundle.js:401428:5)
From previous event:
    at Object._viewRoom (https://riot.im/develop/bundles/dda9bd59e426e82eac8e/bundle.js:83361:17)
    at Object.onAction (https://riot.im/develop/bundles/dda9bd59e426e82eac8e/bundle.js:83045:22)
    at MatrixDispatcher._invokeCallback (https://riot.im/develop/bundles/dda9bd59e426e82eac8e/bundle.js:218297:24)
    at MatrixDispatcher.dispatch (https://riot.im/develop/bundles/dda9bd59e426e82eac8e/bundle.js:218273:14) color: red
```

possibly related is:
```
2019-11-08T16:35:51.292Z E The above error occurred in the <EventTile> component:
    in EventTile (created by MessagePanel)
    in li (created by MessagePanel)
    in ol (created by ScrollPanel)
    in div (created by ScrollPanel)
    in div (created by AutoHideScrollbar)
    in div (created by AutoHideScrollbar)
    in AutoHideScrollbar (created by ScrollPanel)
    in ScrollPanel (created by MessagePanel)
    in MessagePanel (created by TimelinePanel)
    in TimelinePanel (created by RoomView)
    in div (created by RoomView)
    in div (created by RoomView)
    in div (created by MainSplit)
    in MainSplit (created by RoomView)
    in ErrorBoundary (created by RoomView)
    in main (created by RoomView)
    in RoomView (created by LoggedInView)
    in div (created by LoggedInView)
    in DragDropContext (created by LoggedInView)
    in div (created by LoggedInView)
    in LoggedInView (created by MatrixChat)
    in ErrorBoundary (created by MatrixChat)
    in MatrixChat

React will try to recreate this component tree from scratch using the error boundary you provided, ErrorBoundary.
2019-11-08T16:35:51.301Z E Cannot read property 'startsWith' of undefined
TypeError: Cannot read property 'startsWith' of undefined
    at Object.EventTile_render [as render] (https://riot.im/develop/bundles/dda9bd59e426e82eac8e/bundle.js:144200:119)
    at finishClassComponent (https://riot.im/develop/bundles/dda9bd59e426e82eac8e/bundle.js:405367:31)
    at updateClassComponent (https://riot.im/develop/bundles/dda9bd59e426e82eac8e/bundle.js:405322:24)
    at beginWork$1 (https://riot.im/develop/bundles/dda9bd59e426e82eac8e/bundle.js:406833:16)
    at HTMLUnknownElement.callCallback (https://riot.im/develop/bundles/dda9bd59e426e82eac8e/bundle.js:388675:14)
    at Object.invokeGuardedCallbackDev (https://riot.im/develop/bundles/dda9bd59e426e82eac8e/bundle.js:388725:16)
    at invokeGuardedCallback (https://riot.im/develop/bundles/dda9bd59e426e82eac8e/bundle.js:388782:31)
    at beginWork$$1 (https://riot.im/develop/bundles/dda9bd59e426e82eac8e/bundle.js:411545:7)
    at performUnitOfWork (https://riot.im/develop/bundles/dda9bd59e426e82eac8e/bundle.js:410539:12)
    at workLoopSync (https://riot.im/develop/bundles/dda9bd59e426e82eac8e/bundle.js:410513:22)
    at renderRoot (https://riot.im/develop/bundles/dda9bd59e426e82eac8e/bundle.js:410206:11)
    at runRootCallback (https://riot.im/develop/bundles/dda9bd59e426e82eac8e/bundle.js:409882:20)
    at https://riot.im/develop/bundles/dda9bd59e426e82eac8e/bundle.js:399681:24
    at unstable_runWithPriority (https://riot.im/develop/bundles/dda9bd59e426e82eac8e/bundle.js:419122:12)
    at runWithPriority$2 (https://riot.im/develop/bundles/dda9bd59e426e82eac8e/bundle.js:399633:10)
    at flushSyncCallbackQueueImpl (https://riot.im/develop/bundles/dda9bd59e426e82eac8e/bundle.js:399677:7)
    at flushSyncCallbackQueue (https://riot.im/develop/bundles/dda9bd59e426e82eac8e/bundle.js:399666:3)
    at scheduleUpdateOnFiber (https://riot.im/develop/bundles/dda9bd59e426e82eac8e/bundle.js:409759:9)
    at Object.enqueueSetState (https://riot.im/develop/bundles/dda9bd59e426e82eac8e/bundle.js:401428:5)
    at Object../node_modules/react/cjs/react.development.js.Component.setState (https://riot.im/develop/bundles/dda9bd59e426e82eac8e/bundle.js:414529:16)
    at https://riot.im/develop/bundles/dda9bd59e426e82eac8e/bundle.js:83379:20
    at tryCatcher (https://riot.im/develop/bundles/dda9bd59e426e82eac8e/bundle.js:200940:23)
    at Promise._settlePromiseFromHandler (https://riot.im/develop/bundles/dda9bd59e426e82eac8e/bundle.js:199072:31)
    at Promise._settlePromise (https://riot.im/develop/bundles/dda9bd59e426e82eac8e/bundle.js:199129:18)
    at Promise._settlePromiseCtx (https://riot.im/develop/bundles/dda9bd59e426e82eac8e/bundle.js:199166:10)
    at https://riot.im/develop/bundles/dda9bd59e426e82eac8e/bundle.js:196137:20
2019-11-08T16:35:51.301Z E The above error occured while React was rendering the following components: 
    in EventTile (created by MessagePanel)
    in li (created by MessagePanel)
    in ol (created by ScrollPanel)
    in div (created by ScrollPanel)
    in div (created by AutoHideScrollbar)
    in div (created by AutoHideScrollbar)
    in AutoHideScrollbar (created by ScrollPanel)
    in ScrollPanel (created by MessagePanel)
    in MessagePanel (created by TimelinePanel)
    in TimelinePanel (created by RoomView)
    in div (created by RoomView)
    in div (created by RoomView)
    in div (created by MainSplit)
    in MainSplit (created by RoomView)
    in ErrorBoundary (created by RoomView)
    in main (created by RoomView)
    in RoomView (created by LoggedInView)
    in div (created by LoggedInView)
    in DragDropContext (created by LoggedInView)
    in div (created by LoggedInView)
    in LoggedInView (created by MatrixChat)
    in ErrorBoundary (created by MatrixChat)
    in MatrixChat
```

**Comment by t3chguy** [comment]
Missing null guards of https://github.com/matrix-org/matrix-react-sdk/pull/3601

**Comment by turt2live** [comment]
For reference, the theme was redacted messages. Redacted messages don't have message types, and the new verification in DMs stuff was looking for a message type. The other symptoms of the app not working are because of React falling over despite the error boundary.
