### ISSUE TITLE
New widget prompt design can soft crash

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#11419]
```
2019-11-18T19:18:44.905Z E Cannot read property 'length' of null
TypeError: Cannot read property 'length' of null
    at Object.defaultAvatarUrlForString (https://riot.im/develop/bundles/1e1b71a568c694c82ff5/bundle.js:60171:31)
    at Object._getState (https://riot.im/develop/bundles/1e1b71a568c694c82ff5/bundle.js:105480:48)
    at Object.BaseAvatar_getInitialState [as getInitialState] (https://riot.im/develop/bundles/1e1b71a568c694c82ff5/bundle.js:105418:21)
    at new BaseAvatar (https://riot.im/develop/bundles/1e1b71a568c694c82ff5/bundle.js:216842:54)
    at constructClassInstance (https://riot.im/develop/bundles/1e1b71a568c694c82ff5/bundle.js:407893:18)
    at updateClassComponent (https://riot.im/develop/bundles/1e1b71a568c694c82ff5/bundle.js:411570:5)
    at beginWork$1 (https://riot.im/develop/bundles/1e1b71a568c694c82ff5/bundle.js:413090:16)
    at HTMLUnknownElement.callCallback (https://riot.im/develop/bundles/1e1b71a568c694c82ff5/bundle.js:394932:14)
    at Object.invokeGuardedCallbackDev (https://riot.im/develop/bundles/1e1b71a568c694c82ff5/bundle.js:394982:16)
    at invokeGuardedCallback (https://riot.im/develop/bundles/1e1b71a568c694c82ff5/bundle.js:395039:31)
    at beginWork$$1 (https://riot.im/develop/bundles/1e1b71a568c694c82ff5/bundle.js:417802:7)
    at performUnitOfWork (https://riot.im/develop/bundles/1e1b71a568c694c82ff5/bundle.js:416796:12)
    at workLoopSync (https://riot.im/develop/bundles/1e1b71a568c694c82ff5/bundle.js:416770:22)
    at renderRoot (https://riot.im/develop/bundles/1e1b71a568c694c82ff5/bundle.js:416463:11)
    at runRootCallback (https://riot.im/develop/bundles/1e1b71a568c694c82ff5/bundle.js:416139:20)
    at https://riot.im/develop/bundles/1e1b71a568c694c82ff5/bundle.js:405938:24
    at unstable_runWithPriority (https://riot.im/develop/bundles/1e1b71a568c694c82ff5/bundle.js:425379:12)
    at runWithPriority$2 (https://riot.im/develop/bundles/1e1b71a568c694c82ff5/bundle.js:405890:10)
    at flushSyncCallbackQueueImpl (https://riot.im/develop/bundles/1e1b71a568c694c82ff5/bundle.js:405934:7)
    at flushSyncCallbackQueue (https://riot.im/develop/bundles/1e1b71a568c694c82ff5/bundle.js:405923:3)
    at scheduleUpdateOnFiber (https://riot.im/develop/bundles/1e1b71a568c694c82ff5/bundle.js:416016:9)
    at Object.enqueueSetState (https://riot.im/develop/bundles/1e1b71a568c694c82ff5/bundle.js:407685:5)
    at Object../node_modules/react/cjs/react.development.js.Component.setState (https://riot.im/develop/bundles/1e1b71a568c694c82ff5/bundle.js:420786:16)
    at https://riot.im/develop/bundles/1e1b71a568c694c82ff5/bundle.js:86913:20
    at tryCatcher (https://riot.im/develop/bundles/1e1b71a568c694c82ff5/bundle.js:206966:23)
    at Promise._settlePromiseFromHandler (https://riot.im/develop/bundles/1e1b71a568c694c82ff5/bundle.js:205098:31)
    at Promise._settlePromise (https://riot.im/develop/bundles/1e1b71a568c694c82ff5/bundle.js:205155:18)
    at Promise._settlePromiseCtx (https://riot.im/develop/bundles/1e1b71a568c694c82ff5/bundle.js:205192:10)
2019-11-18T19:18:44.906Z E The above error occured while React was rendering the following components: 
    in BaseAvatar (created by AppPermission)
    in div (created by AppPermission)
    in div (created by AppPermission)
    in AppPermission (created by AppTile)
    in div (created by AppTile)
    in div (created by AppTile)
    in AppTile (created by AppsDrawer)
    in div (created by AppsDrawer)
    in div (created by AppsDrawer)
    in AppsDrawer (created by AuxPanel)
    in div (created by AuxPanel)
    in AuxPanel (created by RoomView)
    in div (created by RoomView)
    in div (created by MainSplit)
    in MainSplit (created by RoomView)
    in ErrorBoundary (created by RoomView)
    in main (created by RoomView)
    in RoomView (created by LoggedInView)
    in div (created by LoggedInView)
    in DragDropContext (created by LoggedInView)
    in div (created by LoggedInView)
    in LoggedInView (created by MatrixChat)
    in ErrorBoundary (created by MatrixChat)
    in MatrixChat
```

**Comment by turt2live** [comment]
This regressed in https://github.com/matrix-org/matrix-react-sdk/pull/3622
