### ISSUE TITLE
White screen on linux build

### ISSUE THREAD

**Issue by hsanjuan** [vector-im/riot-web#11626]
### Description

I have followed the instructions to build the Riot app. The build works fine, but starting the app results in a white screen and nothing else. No errors on console.

I cannot even start with `--devtools` because that results in:

```
Error: Cannot find module 'electron-devtools-installer'
Require stack:
- /tmp/.mount_riotlqSKlr/resources/app.asar/src/electron-main.js
- 
    at Module._resolveFilename (internal/modules/cjs/loader.js:717:15)
    at Function../lib/common/reset-search-paths.ts.Module._resolveFilename (/browser_init.js:7552:16)
    at Module._load (internal/modules/cjs/loader.js:622:27)
    at Module._load (electron/js2c/asar.js:717:26)
    at Function.Module._load (electron/js2c/asar.js:717:26)
    at Module.require (internal/modules/cjs/loader.js:775:19)
    at require (internal/modules/cjs/helpers.js:68:18)
    at App.<anonymous> (/tmp/.mount_riotlqSKlr/resources/app.asar/src/electr5:80)
    at App.emit (events.js:208:15) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/tmp/.mount_riotlqSKlr/resources/app.asar/src/electron-main.js',
    undefined
  ]
}
```

I have done `yarn add electron-devtools-installer`, `npm install -g.. ` and some googling etc. and I've given up dealing with this.

I remember this (or something similar) happening last time I built it a while ago, but somehow managed to run with --devtools which showed some electron dependency missing which I probably `npm install`'ed globally and things started working.

What is the actual way to debug this? There are no console logs, or --debug flag or errors printed anywhere. Is this supposed to be this way?

### Steps to reproduce

```
yarn install
yarn build:electron:linux
```

I have modified this target to produce an AppImage (I will never understand why there is no official distribution of AppImages and instead they are packaged for Debian only.):

```
"build:electron:linux": "yarn build && electron-builder -l AppImage --x64"
```

I also deleted the `.config/Riot` folder and added `config.json` from the template and only changed the setting `"piwik": false`. The previous `config.json` that I had worked with the old version and there were not too many differences anyway.

### Describe how what happens differs from what you expected.

I expected to download and run Riot using an electron app binary which is universally runable in all linuxes because it packages all the things needed in it.

There is no official image. So I expected I could easily build it myself.

The builds do not produce an AppImage as I expected, so I have to learn yarn and electron flags. I also have to read the Building From Source docs and figure out that `node_modules/.bin/build -l --x64` does not work because `build` does not exist. Then I have to modify the package.json manually to get the right flags to electron.

When I have finally built something, I run it and I get a white screen with no errors whatsoever. I expected to get an error message or something.

Finally I expected to maybe find similar issues but I cannot seem to find anything very similar. It would seem that white screen happens when something breaks, but there is no explanation on how to find what broke.

### Version information

b93b6b448e05543563b3d013c41ef31228fd2760 - master as of today, also tested with 1.5.5.

- **Platform**: desktop

For the desktop app:

- **OS**: OpenSUSE
- **Version**:  check the user settings panel if unsure -> would be great to have a settings panel.

**Comment by t3chguy** [comment]
--devtools is to install react devtools which if you're getting a white screen will not help you. Open the app and open js webtools using control shift I

**Comment by hsanjuan** [comment]
Thank you, the console shows an error:

```
bundle.js:35 Starting watcher for RoomList.orderByImportance@<null room>
bundle.js:35 Starting watcher for feature_custom_tags@<null room>
bundle.js:35 Initialised rageshake.
bundle.js:35 To fix line numbers in Chrome: Meatball menu → Settings → Blackboxing → Add /rageshake\.js$
bundle.js:35 Using WebAssembly Olm
bundle.js:35 Using Electron platform
bundle.js:35 Migrating session from old origin...
bundle.js:35 Storage persist request granted: true persisted: true
bundle.js:35 Origin migration complete
bundle.js:35 set language to en-us
bundle.js:35 Unhandled rejection TypeError: N.ThemeWatcher is not a constructor
    at vector://vector/webapp/bundles/8e9be77…/bundle.js:41:813672
    at E (vector://vector/webapp/bundles/8e9be77…/bundle.js:35:148890)
    at Generator._invoke (vector://vector/webapp/bundles/8e9be77…/bundle.js:35:148678)
    at Generator.C.forEach.e.<computed> [as next] (vector://vector/webapp/bundles/8e9be77…/bundle.js:35:149070)
    at Generator.c (vector://vector/webapp/bundles/8e9be77…/bundle.js:19:149335)
    at f._promiseFulfilled (vector://vector/webapp/bundles/8e9be77…/bundle.js:19:106206)
    at D._settlePromise (vector://vector/webapp/bundles/8e9be77…/bundle.js:19:123403)
    at D._settlePromise0 (vector://vector/webapp/bundles/8e9be77…/bundle.js:19:124001)
    at D._settlePromises (vector://vector/webapp/bundles/8e9be77…/bundle.js:19:125353)
    at p (vector://vector/webapp/bundles/8e9be77…/bundle.js:19:77443)
    at f (vector://vector/webapp/bundles/8e9be77…/bundle.js:19:77382)
    at l._drainQueues (vector://vector/webapp/bundles/8e9be77…/bundle.js:19:78902)
    at drainQueues (vector://vector/webapp/bundles/8e9be77…/bundle.js:19:77124)
From previous event:
    at D.B [as _captureStackTrace] (vector://vector/webapp/bundles/8e9be77…/bundle.js:19:92226)
    at new f (vector://vector/webapp/bundles/8e9be77…/bundle.js:19:105081)
    at vector://vector/webapp/bundles/8e9be77…/bundle.js:19:108170
    at vector://vector/webapp/bundles/8e9be77…/bundle.js:41:816558
    at Object.<anonymous> (vector://vector/webapp/bundles/8e9be77…/bundle.js:41:821487)
    at Object.<anonymous> (vector://vector/webapp/bundles/8e9be77…/bundle.js:41:821493)
    at o (vector://vector/webapp/bundles/8e9be77…/bundle.js:1:361)
    at Object.<anonymous> (vector://vector/webapp/bundles/8e9be77…/bundle.js:41:757291)
    at o (vector://vector/webapp/bundles/8e9be77…/bundle.js:1:361)
    at vector://vector/webapp/bundles/8e9be77…/bundle.js:1:2076
    at vector://vector/webapp/bundles/8e9be77…/bundle.js:1:2088
```

**Comment by t3chguy** [comment]
Looks like you built a mismatched build. Wrong riot-web to matrix-react-sdk versions

**Comment by hsanjuan** [comment]
Thank you, I removed:

```
        scripts/matrix-js-sdk/
        scripts/matrix-react-sdk/
        scripts/node_modules/
```
(apparently old from previous builds)

Then do `yarn link`, `yarn install`, `yarn build:electron:linux` and things work now.
