### ISSUE TITLE
matrix-seshat not found

### ISSUE THREAD

**Issue by kroeckx** [vector-im/riot-web#11637]
When starting riot-web, I get:
```
seshat unavailable Error: Cannot find module 'matrix-seshat'
Require stack:
- /opt/Riot/resources/app.asar/src/electron-main.js
- 
    at Module._resolveFilename (internal/modules/cjs/loader.js:717:15)
    at Function../lib/common/reset-search-paths.ts.Module._resolveFilename (electron/js2c/browser_init.js:7609:16)
    at Module._load (internal/modules/cjs/loader.js:622:27)
    at Module._load (electron/js2c/asar.js:717:26)
    at Function.Module._load (electron/js2c/asar.js:717:26)
    at Module.require (internal/modules/cjs/loader.js:775:19)
    at require (internal/modules/cjs/helpers.js:68:18)
    at Object.<anonymous> (/opt/Riot/resources/app.asar/src/electron-main.js:49:14)
    at Module._compile (internal/modules/cjs/loader.js:880:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:892:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/opt/Riot/resources/app.asar/src/electron-main.js', undefined ]
}
```

Using the riot-web 1.5.6 .deb package.

Everything seems to work at first sight.

**Comment by jryans** [comment]
`seshat` is an optional experimental feature, so this does not actually indicate an error, but this log message doesn't make that clear at all, so we should improve the logging.

@ara4n, @poljar: Can we remove the console log and instead show status elsewhere, perhaps in the Riot UI?

**Comment by poljar** [comment]
That log message was added here https://github.com/vector-im/riot-web/commit/fe7813958a36a771b4924409ddaa866aae7fec66.

On the react side we log a more user friendly message here https://github.com/matrix-org/matrix-react-sdk/blob/develop/src/indexing/EventIndexPeg.js#L44.

I think that error message is only helpful to people that build/package Seshat with riot-desktop. Not sure if we want to propagate that through to the Riot UI.
