### ISSUE TITLE
On /develop after press hovered emoji button on message - Something went wrong

### ISSUE THREAD

**Issue by MurzNN** [vector-im/riot-web#11641]
On Develop after press hovered emoji button on message - Something went wrong, debug logs are sent via Riot interface.

**Comment by turt2live** [comment]
```
2019-12-10T18:49:32.095Z E Object.fromEntries is not a function
TypeError: Object.fromEntries is not a function
    at ReactionPicker.getReactions (https://riot.im/develop/bundles/313a9ca264a61fb61be3/bundle.js:119597:27)
    at new ReactionPicker (https://riot.im/develop/bundles/313a9ca264a61fb61be3/bundle.js:119555:73)
    at constructClassInstance (https://riot.im/develop/bundles/313a9ca264a61fb61be3/bundle.js:382701:18)
    at updateClassComponent (https://riot.im/develop/bundles/313a9ca264a61fb61be3/bundle.js:386910:5)
    at beginWork$1 (https://riot.im/develop/bundles/313a9ca264a61fb61be3/bundle.js:388683:16)
    at HTMLUnknownElement.callCallback (https://riot.im/develop/bundles/313a9ca264a61fb61be3/bundle.js:368833:14)
    at Object.invokeGuardedCallbackDev (https://riot.im/develop/bundles/313a9ca264a61fb61be3/bundle.js:368882:16)
    at invokeGuardedCallback (https://riot.im/develop/bundles/313a9ca264a61fb61be3/bundle.js:368937:31)
    at beginWork$$1 (https://riot.im/develop/bundles/313a9ca264a61fb61be3/bundle.js:394277:7)
    at performUnitOfWork (https://riot.im/develop/bundles/313a9ca264a61fb61be3/bundle.js:393195:12)
2019-12-10T18:49:32.095Z E The above error occured while React was rendering the following components: 
    in ReactionPicker (created by ReactButton)
    in div (created by ContextMenu)
    in div (created by ContextMenu)
    in ContextMenu (created by ReactButton)
    in ReactButton (created by MessageActionBar)
    in div (created by MessageActionBar)
    in MessageActionBar (created by EventTile)
    in div (created by EventTile)
    in div (created by EventTile)
    in EventTile (created by MessagePanel)
    in li (created by MessagePanel)
    in ol (created by ScrollPanel)
    in div (created by ScrollPanel)
    in div (created by AutoHideScrollbar)
    in div (created by AutoHideScrollbar)
    in AutoHideScrollbar (created by ScrollPanel)
    in ScrollPanel (created by MessagePanel)
    in MessagePanel (created by TimelinePanel)
    in TimelinePanel (created by RoomView)
    in div (created by RoomView)
    in div (created by RoomView)
    in div (created by MainSplit)
    in MainSplit (created by RoomView)
    in ErrorBoundary (created by RoomView)
    in main (created by RoomView)
    in RoomView (created by LoggedInView)
    in div (created by LoggedInView)
    in DragDropContext (created by LoggedInView)
    in div (created by LoggedInView)
    in LoggedInView (created by MatrixChat)
    in ErrorBoundary (created by MatrixChat)
    in MatrixChat
```

from the rageshake

**Comment by t3chguy** [comment]
You are not using a supported browser it seems: https://caniuse.com/#search=fromEntries

**Comment by MurzNN** [comment]
Yes, my browser is not too fresh, I use Rambox Electron app as wrapper:

Electron: 4.1.4
~~Internet Explorer 6.0~~ Chromium: 69.0.3497.128

So maybe check at startup and warn that browser is too old?

**Comment by t3chguy** [comment]
We do using modernizr but it isn't perfect at detecting the thousands of methods a browser may/may not support outside of spec

**Comment by turt2live** [comment]
We thought we specified exactly what we support, but it turns out we didn't. We've fixed this with https://github.com/vector-im/riot-web/pull/11658, though to copy it here: Chrome 69 is not supported by us, and neither is whatever this rambox thing (by extension). 

Sorry :(
