### ISSUE TITLE
Clicking a pill for a member not in the room soft crashes

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#11730]
see rageshake

```
2019-12-26T09:17:32.918Z E The above error occurred in the <UserOptionsSection> component:
    in UserOptionsSection (created by UserInfo)
    in div (created by AutoHideScrollbar)
    in div (created by AutoHideScrollbar)
    in AutoHideScrollbar (created by UserInfo)
    in div (created by UserInfo)
    in UserInfo (created by RightPanel)
    in aside (created by RightPanel)
    in RightPanel (created by RoomView)
    in div (created by MainSplit)
    in MainSplit (created by RoomView)
    in ErrorBoundary (created by RoomView)
    in main (created by RoomView)
    in RoomView (created by LoggedInView)
    in div (created by LoggedInView)
    in DragDropContext (created by LoggedInView)
    in div (created by LoggedInView)
    in LoggedInView (created by MatrixChat)
    in ErrorBoundary (created by MatrixChat)
    in MatrixChat

React will try to recreate this component tree from scratch using the error boundary you provided, ErrorBoundary.
2019-12-26T09:17:32.929Z E RoomViewStore.getRoomId is not a function
TypeError: RoomViewStore.getRoomId is not a function
    at UserOptionsSection (https://riot.im/develop/bundles/f90f82ef975b77c509af/bundle.js:132341:82)
    at renderWithHooks (https://riot.im/develop/bundles/f90f82ef975b77c509af/bundle.js:391275:18)
    at updateFunctionComponent (https://riot.im/develop/bundles/f90f82ef975b77c509af/bundle.js:393362:20)
    at beginWork$1 (https://riot.im/develop/bundles/f90f82ef975b77c509af/bundle.js:395191:16)
    at HTMLUnknownElement.callCallback (https://riot.im/develop/bundles/f90f82ef975b77c509af/bundle.js:375351:14)
    at Object.invokeGuardedCallbackDev (https://riot.im/develop/bundles/f90f82ef975b77c509af/bundle.js:375400:16)
    at invokeGuardedCallback (https://riot.im/develop/bundles/f90f82ef975b77c509af/bundle.js:375455:31)
    at beginWork$$1 (https://riot.im/develop/bundles/f90f82ef975b77c509af/bundle.js:400795:7)
    at performUnitOfWork (https://riot.im/develop/bundles/f90f82ef975b77c509af/bundle.js:399713:12)
    at workLoopSync (https://riot.im/develop/bundles/f90f82ef975b77c509af/bundle.js:399686:22)
2019-12-26T09:17:32.930Z E The above error occured while React was rendering the following components: 
    in UserOptionsSection (created by UserInfo)
    in div (created by AutoHideScrollbar)
    in div (created by AutoHideScrollbar)
    in AutoHideScrollbar (created by UserInfo)
    in div (created by UserInfo)
    in UserInfo (created by RightPanel)
    in aside (created by RightPanel)
    in RightPanel (created by RoomView)
    in div (created by MainSplit)
    in MainSplit (created by RoomView)
    in ErrorBoundary (created by RoomView)
    in main (created by RoomView)
    in RoomView (created by LoggedInView)
    in div (created by LoggedInView)
    in DragDropContext (created by LoggedInView)
    in div (created by LoggedInView)
    in LoggedInView (created by MatrixChat)
    in ErrorBoundary (created by MatrixChat)
    in MatrixChat
2019-12-26T09:17:33.252Z E Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in %s.%s a useEffect cleanup function 
    in UserInfo (created by RightPanel)
    in aside (created by RightPanel)
    in RightPanel (created by RoomView)
    in div (created by MainSplit)
    in MainSplit (created by RoomView)
```

**Comment by turt2live** [comment]
I don't think this is urgent enough to get a fire status.
