### ISSUE TITLE
RoomPreviewBar explodes sometimes

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#11793]
I don't think this is worthy of a fire label yet. It happens rarely.

```
2020-01-07T11:16:13.930Z E Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at qa (https://chat.openintents.org/bundles/82c94c5aecead828f57e/bundle.js:66:74520)
    at Ks (https://chat.openintents.org/bundles/82c94c5aecead828f57e/bundle.js:66:93162)
    at t.unstable_runWithPriority (https://chat.openintents.org/bundles/82c94c5aecead828f57e/bundle.js:74:3884)
    at po (https://chat.openintents.org/bundles/82c94c5aecead828f57e/bundle.js:66:41541)
    at Hs (https://chat.openintents.org/bundles/82c94c5aecead828f57e/bundle.js:66:90891)
    at Ms (https://chat.openintents.org/bundles/82c94c5aecead828f57e/bundle.js:66:79559)
    at https://chat.openintents.org/bundles/82c94c5aecead828f57e/bundle.js:66:41813
    at t.unstable_runWithPriority (https://chat.openintents.org/bundles/82c94c5aecead828f57e/bundle.js:74:3884)
    at po (https://chat.openintents.org/bundles/82c94c5aecead828f57e/bundle.js:66:41541)
    at _o (https://chat.openintents.org/bundles/82c94c5aecead828f57e/bundle.js:66:41758)
    at go (https://chat.openintents.org/bundles/82c94c5aecead828f57e/bundle.js:66:41693)
    at Fs (https://chat.openintents.org/bundles/82c94c5aecead828f57e/bundle.js:66:78550)
    at Object.enqueueSetState (https://chat.openintents.org/bundles/82c94c5aecead828f57e/bundle.js:66:46506)
    at t.E.setState (https://chat.openintents.org/bundles/82c94c5aecead828f57e/bundle.js:49:1439)
    at https://chat.openintents.org/bundles/82c94c5aecead828f57e/bundle.js:41:630484
    at c (https://chat.openintents.org/bundles/82c94c5aecead828f57e/bundle.js:1:81419)
2020-01-07T11:16:13.935Z E Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at qa (https://chat.openintents.org/bundles/82c94c5aecead828f57e/bundle.js:66:74520)
    at Ks (https://chat.openintents.org/bundles/82c94c5aecead828f57e/bundle.js:66:93162)
    at t.unstable_runWithPriority (https://chat.openintents.org/bundles/82c94c5aecead828f57e/bundle.js:74:3884)
    at po (https://chat.openintents.org/bundles/82c94c5aecead828f57e/bundle.js:66:41541)
    at Hs (https://chat.openintents.org/bundles/82c94c5aecead828f57e/bundle.js:66:90891)
    at Ms (https://chat.openintents.org/bundles/82c94c5aecead828f57e/bundle.js:66:79559)
    at https://chat.openintents.org/bundles/82c94c5aecead828f57e/bundle.js:66:41813
    at t.unstable_runWithPriority (https://chat.openintents.org/bundles/82c94c5aecead828f57e/bundle.js:74:3884)
    at po (https://chat.openintents.org/bundles/82c94c5aecead828f57e/bundle.js:66:41541)
    at _o (https://chat.openintents.org/bundles/82c94c5aecead828f57e/bundle.js:66:41758)
    at go (https://chat.openintents.org/bundles/82c94c5aecead828f57e/bundle.js:66:41693)
    at Fs (https://chat.openintents.org/bundles/82c94c5aecead828f57e/bundle.js:66:78550)
    at Object.enqueueSetState (https://chat.openintents.org/bundles/82c94c5aecead828f57e/bundle.js:66:46506)
    at t.E.setState (https://chat.openintents.org/bundles/82c94c5aecead828f57e/bundle.js:49:1439)
    at https://chat.openintents.org/bundles/82c94c5aecead828f57e/bundle.js:41:630484
    at c (https://chat.openintents.org/bundles/82c94c5aecead828f57e/bundle.js:1:81419)
2020-01-07T11:16:13.935Z E The above error occured while React was rendering the following components: 
    in h3
    in div
    in div
    in RoomPreviewBar
    in t
    in div
    in RoomView
    in div
    in t
    in div
    in LoggedInView
    in t
    in MatrixChat
```

**Comment by t3chguy** [comment]
I cannot reproduce it and the stacktraces in the rageshakes are all from /app/ and not all that useful :(

Awaiting a reproduction from /develop with a stacktrace.

**Comment by t3chguy** [comment]
This looks like the google translate explosion
