### ISSUE TITLE
Undefined events in the timeline cause crashes

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#12423]
The obvious first question is "how did we end up with undefined events?", but for now, have a stacktrace:
```
2020-02-19T22:01:41.604Z E Cannot read property 'sender' of undefined
TypeError: Cannot read property 'sender' of undefined
    at ln.getTiles (vector://vector/webapp/bundles/9d2aa2b068c5e7f90891/bundle.js:2:3425579)
    at cn._getEventTiles (vector://vector/webapp/bundles/9d2aa2b068c5e7f90891/bundle.js:2:3419710)
    at cn.render (vector://vector/webapp/bundles/9d2aa2b068c5e7f90891/bundle.js:2:3423574)
    at $a (vector://vector/webapp/bundles/9d2aa2b068c5e7f90891/bundle.js:2:2052246)
    at Ya (vector://vector/webapp/bundles/9d2aa2b068c5e7f90891/bundle.js:2:2052041)
    at xs (vector://vector/webapp/bundles/9d2aa2b068c5e7f90891/bundle.js:2:2087222)
    at gc (vector://vector/webapp/bundles/9d2aa2b068c5e7f90891/bundle.js:2:2071565)
    at hc (vector://vector/webapp/bundles/9d2aa2b068c5e7f90891/bundle.js:2:2071490)
    at ic (vector://vector/webapp/bundles/9d2aa2b068c5e7f90891/bundle.js:2:2068838)
    at vector://vector/webapp/bundles/9d2aa2b068c5e7f90891/bundle.js:2:2027280
```

Not escalating to Fire status until multiple reports show up.

**Comment by turt2live** [comment]
Welcome to the fire, new issue.

**Comment by turt2live** [comment]
This is caused by redacted create events (or all initial state events) trying to be grouped. Regressed in https://github.com/matrix-org/matrix-react-sdk/pull/4059

Just need some empty array checks and it'll be fixed. All 10 rageshakes look to be having exactly the same problem, but thank you in particular to the one person who said they removed all recent messages for a user.
