### ISSUE TITLE
Sync error: Cannot read property 'highlight' of undefined

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#12580]
This doesn't appear to be a fatal error

```
2020-02-29T19:44:11.984Z E Caught /sync error TypeError: Cannot read property 'highlight' of undefined
    at D.<anonymous> (vector://vector/webapp/bundles/9d2aa2b068c5e7f90891/bundle.js:2:744884)
    at D.s.emit (vector://vector/webapp/bundles/9d2aa2b068c5e7f90891/bundle.js:2:82147)
    at o._handleEvent (vector://vector/webapp/bundles/9d2aa2b068c5e7f90891/bundle.js:2:576448)
    at o.n (vector://vector/webapp/bundles/9d2aa2b068c5e7f90891/bundle.js:2:576499)
    at g.s.emit (vector://vector/webapp/bundles/9d2aa2b068c5e7f90891/bundle.js:2:82090)
    at g.addReceipt (vector://vector/webapp/bundles/9d2aa2b068c5e7f90891/bundle.js:2:809017)
    at g.addEphemeralEvents (vector://vector/webapp/bundles/9d2aa2b068c5e7f90891/bundle.js:2:807112)
    at vector://vector/webapp/bundles/9d2aa2b068c5e7f90891/bundle.js:2:716884
    at Object.I (vector://vector/webapp/bundles/9d2aa2b068c5e7f90891/bundle.js:2:25404)
    at async m._processSyncResponse (vector://vector/webapp/bundles/9d2aa2b068c5e7f90891/bundle.js:2:715456)
```

**Comment by t3chguy** [comment]
Fixed in the TSC'ing
