### ISSUE TITLE
React crash while looking up profile data for a user

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#12627]
```
2020-03-05T13:01:38.082Z E Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
Error: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
    at vs (https://riot.im/app/bundles/5913369ec59578312adc/bundle.js:2:2078906)
    at bc (https://riot.im/app/bundles/5913369ec59578312adc/bundle.js:2:2098541)
    at t.unstable_runWithPriority (https://riot.im/app/bundles/5913369ec59578312adc/bundle.js:2:2119846)
    at zr (https://riot.im/app/bundles/5913369ec59578312adc/bundle.js:2:2044961)
    at vc (https://riot.im/app/bundles/5913369ec59578312adc/bundle.js:2:2096647)
    at ic (https://riot.im/app/bundles/5913369ec59578312adc/bundle.js:2:2087009)
    at https://riot.im/app/bundles/5913369ec59578312adc/bundle.js:2:2045252
    at t.unstable_runWithPriority (https://riot.im/app/bundles/5913369ec59578312adc/bundle.js:2:2119846)
    at zr (https://riot.im/app/bundles/5913369ec59578312adc/bundle.js:2:2044961)
    at $r (https://riot.im/app/bundles/5913369ec59578312adc/bundle.js:2:2045197)
2020-03-05T13:01:38.084Z E Could not retrieve profile data for @_slack_redacted:matrix.org: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
Error: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
    at vs (https://riot.im/app/bundles/5913369ec59578312adc/bundle.js:2:2078906)
    at bc (https://riot.im/app/bundles/5913369ec59578312adc/bundle.js:2:2098541)
    at t.unstable_runWithPriority (https://riot.im/app/bundles/5913369ec59578312adc/bundle.js:2:2119846)
    at zr (https://riot.im/app/bundles/5913369ec59578312adc/bundle.js:2:2044961)
    at vc (https://riot.im/app/bundles/5913369ec59578312adc/bundle.js:2:2096647)
    at ic (https://riot.im/app/bundles/5913369ec59578312adc/bundle.js:2:2087009)
    at https://riot.im/app/bundles/5913369ec59578312adc/bundle.js:2:2045252
    at t.unstable_runWithPriority (https://riot.im/app/bundles/5913369ec59578312adc/bundle.js:2:2119846)
    at zr (https://riot.im/app/bundles/5913369ec59578312adc/bundle.js:2:2044961)
    at $r (https://riot.im/app/bundles/5913369ec59578312adc/bundle.js:2:2045197)
```

Then later...
```
2020-03-05T13:01:39.490Z E Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
Error: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
    at vs (https://riot.im/app/bundles/5913369ec59578312adc/bundle.js:2:2078906)
    at bc (https://riot.im/app/bundles/5913369ec59578312adc/bundle.js:2:2098541)
    at t.unstable_runWithPriority (https://riot.im/app/bundles/5913369ec59578312adc/bundle.js:2:2119846)
    at zr (https://riot.im/app/bundles/5913369ec59578312adc/bundle.js:2:2044961)
    at vc (https://riot.im/app/bundles/5913369ec59578312adc/bundle.js:2:2096647)
    at ic (https://riot.im/app/bundles/5913369ec59578312adc/bundle.js:2:2087009)
    at https://riot.im/app/bundles/5913369ec59578312adc/bundle.js:2:2045252
    at t.unstable_runWithPriority (https://riot.im/app/bundles/5913369ec59578312adc/bundle.js:2:2119846)
    at zr (https://riot.im/app/bundles/5913369ec59578312adc/bundle.js:2:2044961)
    at $r (https://riot.im/app/bundles/5913369ec59578312adc/bundle.js:2:2045197)
2020-03-05T13:01:39.491Z I Ending watcher ID 1583413296871_10_showTypingNotifications_null
2020-03-05T13:01:39.493Z I Ending watcher ID 1583413296834_9_MessageComposerInput.autoReplaceEmoji_null
2020-03-05T13:01:39.497Z E Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
Error: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
    at vs (https://riot.im/app/bundles/5913369ec59578312adc/bundle.js:2:2078906)
    at bc (https://riot.im/app/bundles/5913369ec59578312adc/bundle.js:2:2098541)
    at t.unstable_runWithPriority (https://riot.im/app/bundles/5913369ec59578312adc/bundle.js:2:2119846)
    at zr (https://riot.im/app/bundles/5913369ec59578312adc/bundle.js:2:2044961)
    at vc (https://riot.im/app/bundles/5913369ec59578312adc/bundle.js:2:2096647)
    at ic (https://riot.im/app/bundles/5913369ec59578312adc/bundle.js:2:2087009)
    at https://riot.im/app/bundles/5913369ec59578312adc/bundle.js:2:2045252
    at t.unstable_runWithPriority (https://riot.im/app/bundles/5913369ec59578312adc/bundle.js:2:2119846)
    at zr (https://riot.im/app/bundles/5913369ec59578312adc/bundle.js:2:2044961)
    at $r (https://riot.im/app/bundles/5913369ec59578312adc/bundle.js:2:2045197)
2020-03-05T13:01:39.497Z E The above error occured while React was rendering the following components: 
    in img
    in BaseAvatar
    in MemberAvatar
    in span
    in Pill
    in span
    in blockquote
    in div
    in div
    in b
    in div
    in div
    in EventTile
    in li
    in ol
    in div
    in div
    in div
    in s
    in ScrollPanel
    in ln
    in TimelinePanel
    in div
    in div
    in ce
    in Uc
    in main
    in RoomView
    in div
    in t
    in div
    in LoggedInView
    in Uc
    in MatrixChat
```

**Comment by Infinity-Intellect** [comment]
@turt2live Could you elaborate on the steps to reproduce this crash ? I would like to work on this issue.

**Comment by turt2live** [comment]
This is all the information we have on it. It was reported as a crash to us with very little information,

**Comment by Infinity-Intellect** [comment]
@turt2live Don't we have information as to what caused the issue ?

**Comment by turt2live** [comment]
The user's submitted report was "can't log in", which is just an indicator that the app didn't load. Sorry, this is truly all the information we have on this one.

**Comment by t3chguy** [comment]
I bet this is another google translate fail!
Fixed by https://github.com/vector-im/riot-web/pull/13669
