### ISSUE TITLE
Doesn't build on arch linux

### ISSUE THREAD

**Issue by cubetastic33** [vector-im/riot-web#12771]
### Description

I am unable to build the riot app on arch linux. I'd actually be fine if I didn't have to build it, but the version in the arch repositories is flagged outdated
### Steps to reproduce

- Follow the instructions [here](https://github.com/vector-im/riot-web#building-from-source)

Describe how what happens differs from what you expected.

When I run `yarn build`, it fails. This is the output:

```
$ yarn build
yarn run v1.22.4
$ yarn clean && yarn build:genfiles && yarn build:compile && yarn build:types && yarn build:bundle
$ rimraf lib webapp electron_app/dist
$ yarn reskindex && yarn build:res
$ reskindex -h src/header
Reskindex: completed
$ node scripts/copy-res.js
$ babel -d lib --verbose --extensions ".ts,.js,.tsx" src
src/component-index.js -> lib/component-index.js
src/components/structures/VectorEmbeddedPage.js -> lib/components/structures/VectorEmbeddedPage.js
src/components/views/auth/VectorAuthFooter.js -> lib/components/views/auth/VectorAuthFooter.js
src/components/views/auth/VectorAuthHeaderLogo.js -> lib/components/views/auth/VectorAuthHeaderLogo.js
src/components/views/auth/VectorAuthPage.js -> lib/components/views/auth/VectorAuthPage.js
src/components/views/auth/VectorCustomServerDialog.js -> lib/components/views/auth/VectorCustomServerDialog.js
src/vector/app.js -> lib/vector/app.js
src/vector/getconfig.js -> lib/vector/getconfig.js
src/vector/index.js -> lib/vector/index.js
src/vector/indexeddb-worker.js -> lib/vector/indexeddb-worker.js
src/vector/mobile_guide/index.js -> lib/vector/mobile_guide/index.js
src/vector/modernizr.js -> lib/vector/modernizr.js
src/vector/platform/ElectronPlatform.js -> lib/vector/platform/ElectronPlatform.js
src/vector/platform/VectorBasePlatform.js -> lib/vector/platform/VectorBasePlatform.js
src/vector/platform/WebPlatform.js -> lib/vector/platform/WebPlatform.js
src/vector/rageshakesetup.js -> lib/vector/rageshakesetup.js
src/vector/url_utils.ts -> lib/vector/url_utils.js
Successfully compiled 17 files with Babel.
$ tsc --emitDeclarationOnly --jsx react
$ cross-env NODE_ENV=production webpack -p --progress --bail --mode production
32% building 97/116 modules 19 active /home/aravk/Documents/riot-web/node_modules/ua-parser-js/src/ua-parser.jsModuleNotFoundError: Module not found: Error: Can't resolve './component-index' in '/home/aravk/Documents/riot-web/node_modules/matrix-react-sdk/src'
    at /home/aravk/Documents/riot-web/node_modules/webpack/lib/Compilation.js:925:10
    at /home/aravk/Documents/riot-web/node_modules/webpack/lib/NormalModuleFactory.js:401:22
    at /home/aravk/Documents/riot-web/node_modules/webpack/lib/NormalModuleFactory.js:130:21
    at /home/aravk/Documents/riot-web/node_modules/webpack/lib/NormalModuleFactory.js:224:22
    at /home/aravk/Documents/riot-web/node_modules/neo-async/async.js:2830:7
    at /home/aravk/Documents/riot-web/node_modules/neo-async/async.js:6877:13
    at /home/aravk/Documents/riot-web/node_modules/webpack/lib/NormalModuleFactory.js:214:25
    at /home/aravk/Documents/riot-web/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:213:14
    at /home/aravk/Documents/riot-web/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (eval at create (/home/aravk/Documents/riot-web/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:13:1)
    at /home/aravk/Documents/riot-web/node_modules/webpack/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:44:7
    at /home/aravk/Documents/riot-web/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (eval at create (/home/aravk/Documents/riot-web/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:13:1)
    at /home/aravk/Documents/riot-web/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (eval at create (/home/aravk/Documents/riot-web/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:25:1)
    at /home/aravk/Documents/riot-web/node_modules/webpack/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:67:43
    at /home/aravk/Documents/riot-web/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (eval at create (/home/aravk/Documents/riot-web/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:14:1)
    at /home/aravk/Documents/riot-web/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (eval at create (/home/aravk/Documents/riot-web/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:25:1)
    at /home/aravk/Documents/riot-web/node_modules/webpack/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:67:43
    at /home/aravk/Documents/riot-web/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (eval at create (/home/aravk/Documents/riot-web/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:14:1)
    at /home/aravk/Documents/riot-web/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (eval at create (/home/aravk/Documents/riot-web/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:13:1)
    at /home/aravk/Documents/riot-web/node_modules/webpack/node_modules/enhanced-resolve/lib/DirectoryExistsPlugin.js:27:15
    at /home/aravk/Documents/riot-web/node_modules/webpack/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:85:15
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
resolve './component-index' in '/home/aravk/Documents/riot-web/node_modules/matrix-react-sdk/src'
  using description file: /home/aravk/Documents/riot-web/node_modules/matrix-react-sdk/package.json (relative path: ./src)
    Field 'matrix_src_browser' doesn't contain a valid alias configuration
    Field 'browser' doesn't contain a valid alias configuration
    using description file: /home/aravk/Documents/riot-web/node_modules/matrix-react-sdk/package.json (relative path: ./src/component-index)
      no extension
        Field 'matrix_src_browser' doesn't contain a valid alias configuration
        Field 'browser' doesn't contain a valid alias configuration
        /home/aravk/Documents/riot-web/node_modules/matrix-react-sdk/src/component-index doesn't exist
      .js
        Field 'matrix_src_browser' doesn't contain a valid alias configuration
        Field 'browser' doesn't contain a valid alias configuration
        /home/aravk/Documents/riot-web/node_modules/matrix-react-sdk/src/component-index.js doesn't exist
      .json
        Field 'matrix_src_browser' doesn't contain a valid alias configuration
        Field 'browser' doesn't contain a valid alias configuration
        /home/aravk/Documents/riot-web/node_modules/matrix-react-sdk/src/component-index.json doesn't exist
      .ts
        Field 'matrix_src_browser' doesn't contain a valid alias configuration
        Field 'browser' doesn't contain a valid alias configuration
        /home/aravk/Documents/riot-web/node_modules/matrix-react-sdk/src/component-index.ts doesn't exist
      .tsx
        Field 'matrix_src_browser' doesn't contain a valid alias configuration
        Field 'browser' doesn't contain a valid alias configuration
        /home/aravk/Documents/riot-web/node_modules/matrix-react-sdk/src/component-index.tsx doesn't exist
      as directory
/home/aravk/Documents/riot-web/node_modules/matrix-react-sdk/src/component-index doesn't exist
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Logs being sent: I'm not sure how to do this... do you mean I should go to account settings in riot? Well, riot's not even building for me

![image](https://user-images.githubusercontent.com/33519300/76964780-420e8b80-6949-11ea-81c4-0b8975cc5b8e.png)

### Version information

- **Platform**: desktop

For the desktop app:

- **OS**: Arch Linux
- **Version**: The latest master as of 18-03-2020Z13:20

**Comment by jryans** [comment]
Thanks for the report! Let's discuss packaging and support questions like this in #riot-web:matrix.org.

**Comment by cubetastic33** [comment]
Right, thank you! I'll ask there.
