### ISSUE TITLE
decrypt returns 'bad MAC' for asymmetric SSSS keys, refuses to progress

### ISSUE THREAD

**Issue by foldleft** [vector-im/riot-web#12846]
I got the following while trying to SSSS authenticate a device with manual SSSS key input:

<img width="783" alt="Screenshot 2020-03-24 at 15 52 26" src="https://user-images.githubusercontent.com/3935731/77448475-c5682b00-6de8-11ea-9b87-050e8010e10c.png">
<img width="676" alt="Screenshot 2020-03-24 at 16 00 18" src="https://user-images.githubusercontent.com/3935731/77448480-c7ca8500-6de8-11ea-8b73-68c50d916fcb.png">

cc: @uhoreg

**Comment by uhoreg** [comment]
This seems to be working for me.  Is this on a new login for an existing account?  Also, if this is a test account on your own server, can you post the output of `select * from account_data where user_id='[userid]';`

**Comment by foldleft** [comment]
it is. 

```
sqlite> select * from account_data where user_id='@test3:localhost';
@test3:localhost|m.secret_storage.key.p1qsGQf87EbkwuBS60ZEW4jKwaJAlkwd|9|{"algorithm": "m.secret_storage.v1.curve25519-aes-sha2", "pubkey": "pDWOpOAMh513w/YaaPHx2zM4SXSpirkOwXKw1PuxLVA", "signatures": {"@test3:localhost": {"ed25519:pUCJXS96IJfIHjcvIKo3aQ53NbOpJlw8k0TDSGXEbjA": "S0sThlmDv40RS7TkxdyUxuOBR1Dlv3bkYeB+fSXDpgMoghDWA4gxeHaHdZGGYzePPI5TjuLfNmZfDB9YOnlABg"}}}
@test3:localhost|m.secret_storage.key.hGq9iS4H1Dd0Kld5gLddZNMJI2cROx3k|12|{"algorithm": "m.secret_storage.v1.curve25519-aes-sha2", "pubkey": "pDWOpOAMh513w/YaaPHx2zM4SXSpirkOwXKw1PuxLVA", "signatures": {"@test3:localhost": {"ed25519:qxgxDttkfht5Qn1I8hPhCcEY5gYrK9s7zJWGNKnRu9k": "fWmHOmGZrCaUFLto8hsbWez2wEim7YVcedsKQdBAUkGGeodtClVQVTtmOVu5QkwYLXqiUztBy2AxNq9/jVbvBQ"}}}
@test3:localhost|m.secret_storage.key.yeTTmJuu4MdviIgMlxNdZBizgtb02D2l|19|{"algorithm": "m.secret_storage.v1.curve25519-aes-sha2", "pubkey": "YdZcHDATxRc013KRZIDa4ZHmn2g6rC359FskEcrrEXU", "signatures": {"@test3:localhost": {"ed25519:GdHfF1btgkdyw8CAq0wYdXZ5kEJ6Ixk1isZBbZC6PBY": "Kt2o+Iv9S8/+Q8bmnaemZmkJRVg0jjkb3+Y5kkE58DERoqg7koWw2fQSWBwxmYFPagxj3IsSCKaFabCe8Pb9AQ"}}}
@test3:localhost|m.secret_storage.key.3VwHFChUy0cFc6g14G2LCPITOydW1UD9|35|{"algorithm": "m.secret_storage.v1.curve25519-aes-sha2", "pubkey": "X7Zv0lczW63rg5ABSi83T/0S5oaujYD+jPKPdnJ/kgQ", "signatures": {"@test3:localhost": {"ed25519:ZOEh1K6RQkDWpHUzoP0jG5GglwRHTwn4OHJMcJLhJh8": "Qpq+cODpxv2j1qrTgm8uanDoiTxEVvJ6ZsB/46OMiACEhnuXHwGJcpJwL1Hn50iLYaCE/jXioFXhyFHUzIqZBw"}}}
@test3:localhost|m.direct|85|{"@test4:localhost": ["!FvYCOictdDeEgPobtG:localhost", "!bqcvdWPmXPdoLveSKN:localhost"], "@test:localhost": ["!ZdRiAaPyAuttfAnAey:localhost"], "@test2:localhost": ["!zuYACBMEjXSKjgiVNa:localhost"], "@test5:localhost": ["!CRHkfWRveCTGcTEqRb:localhost"], "@test6:localhost": ["!GRAfFrOYuTxHbgipTN:localhost"], "@test7:localhost": ["!aQqqQEyEfwfCnmeiiY:localhost", "!zePOEeJzdIcoqwaSzd:localhost", "!QwBohegqKpLgGEmawc:localhost", "!YkdlCdHeBBCTFXocnq:localhost", "!HElXepXwjPxTlDtZNp:localhost", "!NpdJGPperaIHmDggKV:localhost", "!pIfaKYZRPMkrnecYgr:localhost", "!wSuvWZHxoxxGDHBBGA:localhost", "!XETOspgZqPuPIjThLq:localhost", "!zFhBPnWnTaxGeffXtI:localhost", "!iMEGcsermGktzQyhCy:localhost", "!PjFXvAzVATSCrcNYAk:localhost", "!tMTZGupzbCngvVvCyB:localhost", "!DGpsPWpEsPCXjhKyeO:localhost", "!nFjsOvGGpiOqksgJeN:localhost", "!PfoSztzxdtLYCttJqu:localhost", "!fOxRemFiwrYaGqzdsr:localhost", "!ZtUQwoGiXYWrqNBYTw:localhost"]}
@test3:localhost|im.vector.setting.breadcrumbs|87|{"recent_rooms": ["!uzqkrhKGLXRHfzNTnF:localhost", "!ZtUQwoGiXYWrqNBYTw:localhost", "!ZGhxJkvVOLrzudzvaT:localhost", "!zuYACBMEjXSKjgiVNa:localhost", "!GRAfFrOYuTxHbgipTN:localhost", "!FvYCOictdDeEgPobtG:localhost", "!bqcvdWPmXPdoLveSKN:localhost", "!CRHkfWRveCTGcTEqRb:localhost", "!tSjqznkrEPtFHrFgFF:localhost", "!BLNmvNefTqdKAXOlep:localhost", "!ZurkIttvtPGBBwEUzM:localhost", "!bscFnniPgmmrqpkZBz:localhost", "!uLHArjJqJIURvstoTw:localhost", "!ZdRiAaPyAuttfAnAey:localhost", "!ebAzqhRIlyObravrdb:localhost"]}
@test3:localhost|m.secret_storage.default_key|90|{"key": "a3TAsmCUnvmOh3w0vHBL5mTdp1UpkQhP"}
@test3:localhost|m.megolm_backup.v1|94|{"encrypted": {"a3TAsmCUnvmOh3w0vHBL5mTdp1UpkQhP": {"iv": "xmqAF2irENA/4lvo0Dilfg==", "ciphertext": "bzTapH/zYAZFY+BXV9jcouuIcghORVuwD1qQ+eXkJ5V2QnUWpaF7VvS+p9g=", "mac": "FpxL39LMBLsmDUffwJMcP1pDAEhwEKrX9hhZs9VNMMw="}}}
@test3:localhost|m.secret_storage.key.a3TAsmCUnvmOh3w0vHBL5mTdp1UpkQhP|95|{"algorithm": "m.secret_storage.v1.aes-hmac-sha2", "signatures": {"@test3:localhost": {"ed25519:GdHfF1btgkdyw8CAq0wYdXZ5kEJ6Ixk1isZBbZC6PBY": "ROjJwdyF3vtC+Dqokrq9gulEET9FNO1pVdBIbiTIoj4LyyM1ecS4B9U4mcNcM4bo4OfJtIbdDxbcXMwrWM4gBw"}}}
@test3:localhost|m.cross_signing.master|96|{"encrypted": {"a3TAsmCUnvmOh3w0vHBL5mTdp1UpkQhP": {"iv": "cqep6bFg5FJ6YCqheQHYow==", "ciphertext": "IBrdjpO+xwYZlWwjMHmiRRzyZc1SpaxgRLP1pLmlJor8kst0lqFSCT+2pGY=", "mac": "Bjb7txAlzcMPzAfZAGpreic+v8z0zrGpjYHc93jRjQU="}}}
@test3:localhost|m.cross_signing.self_signing|97|{"encrypted": {"a3TAsmCUnvmOh3w0vHBL5mTdp1UpkQhP": {"iv": "JyxxkvOOdiUt54OsiwblEQ==", "ciphertext": "N4NbauppKHyVSqiyEMTs22dZ1YjwVXR5P0dkHleara4VzhEvm0H05T94dUc=", "mac": "7U3oJCTW140fY8orDMlJnUioN9g6Yf1NZ8I94Edz2Xk="}}}
@test3:localhost|m.cross_signing.user_signing|98|{"encrypted": {"a3TAsmCUnvmOh3w0vHBL5mTdp1UpkQhP": {"iv": "6OH2lnRFCNZlx7fcGXMsbQ==", "ciphertext": "YLKwsgKRf5OnhbIYIeaMCzM+Dcscpk0xYgNssE3gnXMCxNHcOavV7j+ln9Y=", "mac": "jFnnAfytgpPOrDl1VMcmM2xM2Fcd91zjraom6Qa5bpY="}}}
```

**Comment by foldleft** [comment]
also the backup/ssss key is `EsTB jSgF TuSi HoKV edWu 4t2j Ssvf QEDa Y5xN jhhj 8KYM 5fW8`

**Comment by jryans** [comment]
Perhaps the problem only happens when using a recovery key (while passphrases continue working)?

**Comment by foldleft** [comment]
I think that's likely

**Comment by uhoreg** [comment]
Strangely, when I write a small test program in node, the data decrypts correctly.  Can you apply the patch below to add some debugging lines, try again, and send the output?

``` diff
--- a/src/crypto/aes.js
+++ b/src/crypto/aes.js
@@ -161,6 +161,9 @@ async function encryptBrowser(data, key, name) {
 async function decryptBrowser(data, key, name) {
     const [aesKey, hmacKey] = await deriveKeysBrowser(key, name);
 
+    logger.log("*** decryptBrowser keys", name, key, aesKey, hmacKey);
+    logger.log("*** data", data);
+
     const ciphertext = decodeBase64(data.ciphertext);
 
     if (!await subtleCrypto.verify(
```

The first log line gives me

```
*** decryptBrowser keys m.cross_signing.master <Buffer 24 33 fc 5d 2e 9a 53 bb dd f6 08 85 da 10 a1 f6 ab c4 29 26 b9 7c b9 47 4a c5 b9 e8 61 9f 0b 1a> <Buffer 11 e7 46 65 15 ab 58 ab 63 a2 66 45 4d 4f 60 49 6a 40 b5 ef ec 80 43 0b 40 c5 57 3d 95 55 ca 61> <Buffer 82 26 b2 a7 60 bd 0f 56 44 36 2e bc 19 02 0e 16 a7 97 6c cd 77 3b 90 f8 72 fb 32 e2 e8 f5 69 d8>
```

in my node test program.

**Comment by foldleft** [comment]
Using the problem key `EsTB jSgF TuSi HoKV edWu 4t2j Ssvf QEDa Y5xN jhhj 8KYM 5fW8`

```
*** decryptBrowser keys m.cross_signing.user_signing Uint8Array(32) [36, 51, 252, 93, 46, 154, 83, 187, 221, 246, 8, 133, 218, 16, 161, 246, 171, 196, 41, 38, 185, 124, 185, 71, 74, 197, 185, 232, 97, 159, 11, 26] CryptoKey {type: "secret", extractable: false, algorithm: {…}, usages: Array(2)} CryptoKey {type: "secret", extractable: false, algorithm: {…}, usages: Array(2)}
rageshake.js?16c9:65 *** data {iv: "3lCEjfpjFv08lw5ArMKO5Q==", ciphertext: "y7zUCD6wZxu0XfIgAuFAavAsec7YoJNB3dZQmSU8X/ao68QfgsJjcH+0Ht4=", mac: "0sFSMw0oLvDHqHn7026y2DCf4dIxoaADTyeazTUk1uc="}
rageshake.js?16c9:65 Error restoring backup Error: Error decrypting secret m.cross_signing.user_signing: bad MAC
    at decryptBrowser (aes.js?043b:175)
```

Using a key created after your patch, `EsTL 7i2Q 4JNe 9peC GTgF YhVK CSWm sxw5 FXed 9o93 1K3q rEyn`:

```
*** decryptBrowser keys m.megolm_backup.v1 Uint8Array(32) [64, 108, 250, 180, 52, 157, 221, 56, 214, 146, 254, 43, 7, 28, 72, 98, 64, 236, 124, 113, 17, 44, 242, 197, 208, 121, 158, 12, 218, 99, 230, 210] CryptoKey {type: "secret", extractable: false, algorithm: {…}, usages: Array(2)} CryptoKey {type: "secret", extractable: false, algorithm: {…}, usages: Array(2)}
rageshake.js?16c9:65 *** data {iv: "sraxrjY4OCRxuK+6Qkee6g==", ciphertext: "r3gBB3QIQ/FjmmMfZH3kUTcY3mPpidAP0FoXArIxqcwx2Mz5XNGalhkFLH4=", mac: "nbSn8rlgmRUjvCGT/wgqTumbJGFdIZLM5paiO1H4hRc="}
```

**Comment by foldleft** [comment]
a couple more known-bad keys
* `EsTp umhr 6EQj FDsT LDpg 5cXp psxo LRum 4ABb 1G5Z qBLe 5hgR`
* `EsTW j7RF sqe5 3xfg 9Qtv AfJ9 pTjr M3Dr WMH6 ibW9 kSL8 GuXb`
* `EsTW y6in toTs M4mu tUwc bAc7 ie7D RPFp qbXK rzBh cyzT C1sq`

**Comment by foldleft** [comment]
It's clear that you're getting two buffers back but I'm getting two `CryptoKey` objects back. Furthermore, this happens for both known-good and known-bad keys:

```
await deriveKeysBrowser(mxMatrixClientPeg.get().keyBackupKeyFromRecoveryKey("EsTW y6in toTs M4mu tUwc bAc7 ie7D RPFp qbXK rzBh cyzT C1sq"))
(2) [CryptoKey, CryptoKey]0: CryptoKey {type: "secret", extractable: false, algorithm: {…}, usages: Array(2)}1: CryptoKey {type: "secret", extractable: false, algorithm: {…}, usages: Array(2)}length: 2__proto__: Array(0)
await deriveKeysBrowser(mxMatrixClientPeg.get().keyBackupKeyFromRecoveryKey("EsTL 7i2Q 4JNe 9peC GTgF YhVK CSWm sxw5 FXed 9o93 1K3q rEyn"))
(2) [CryptoKey, CryptoKey]
```

**Comment by foldleft** [comment]
Okay, so it looks like it's not just the key – it's the key plus data.  I had run this against the wrong account.

It just behaved on `@test3:localhost`:
```
*** decryptBrowser keys m.megolm_backup.v1 Uint8Array(32) [36, 51, 252, 93, 46, 154, 83, 187, 221, 246, 8, 133, 218, 16, 161, 246, 171, 196, 41, 38, 185, 124, 185, 71, 74, 197, 185, 232, 97, 159, 11, 26] CryptoKey {type: "secret", extractable: false, algorithm: {…}, usages: Array(2)} CryptoKey {type: "secret", extractable: false, algorithm: {…}, usages: Array(2)}
rageshake.js?16c9:65 *** data {iv: "xmqAF2irENA/4lvo0Dilfg==", ciphertext: "bzTapH/zYAZFY+BXV9jcouuIcghORVuwD1qQ+eXkJ5V2QnUWpaF7VvS+p9g=", mac: "FpxL39LMBLsmDUffwJMcP1pDAEhwEKrX9hhZs9VNMMw="}
```

**Comment by foldleft** [comment]
well, now i can't seem to repro at all?  I wonder if it's related to some of the caching.

* `@test3:localhost` – logged in just fine after entering SSSS key
* `@test4:localhost` – requested my password, then my SSSS key, then logged in normally. Behaves as `@test3:localhost` thereafter
* `@test7:localhost` – requested my SSSS key twice, then as above

**Comment by jryans** [comment]
For at least the `Error decrypting secret m.megolm_backup.v1: bad MAC` version of this with the backup key secret, here's a clear repo case:

* Create a new account and setup 4S with key backup during registration
* Try to reset the cross-signing in Settings after login

**Comment by uhoreg** [comment]
I've created a node script to try to help debug this. https://gist.github.com/uhoreg/483c67af735c1fec6db55f7663d74182  Instructions on how to use it are on [lines 6-53](https://gist.github.com/uhoreg/483c67af735c1fec6db55f7663d74182#file-check_encryption-js-L6-L53)

**Comment by dbkr** [comment]
The script gives a bad mac error too (I added the actual mac that it got to the logging):

```
$ node check_encryption.js 
*** decrypt called with {
  iv: 'DRcRY9D6mYgccjOBUpaLYg==',
  ciphertext: 'TevRLK0ZEM4YxshwcvxPSGK7RfW3XiPq4z8SNqqTh8h3pYOl7roeVq+k3L4=',
  mac: '2ric1OFHU47QNjQEgAHUaz9q108V/CkPQpZqJE8muTc='
} Uint8Array(32) [
  164, 196,  39, 229, 155, 134, 178,
  237,  62,  60,  17, 247, 249, 122,
  211, 183, 101, 154, 152, 249, 112,
  248, 187,  17, 171, 113, 122,  92,
   60, 152, 117,  67
] m.cross_signing.master
(node:85876) UnhandledPromiseRejectionWarning: Error: Error decrypting secret m.cross_signing.master: bad MAC.  expected hY0OF0h41PVZfou6a18RA8cWfA+Uc0knFAp7rIjBOgM= got 2ric1OFHU47QNjQEgAHUaz9q108V/CkPQpZqJE8muTc=
    at decryptNode (/Users/dave/matrix/matrix-js-sdk/check_encryption.js:120:15)
    at /Users/dave/matrix/matrix-js-sdk/check_encryption.js:131:23
    at Object.<anonymous> (/Users/dave/matrix/matrix-js-sdk/check_encryption.js:132:3)
    at Module._compile (internal/modules/cjs/loader.js:1151:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1171:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
(node:85876) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:85876) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
dave@yaw ~/matrix/matrix-js-sdk $ vim check_encryption.js 
```

**Comment by uhoreg** [comment]
> For at least the `Error decrypting secret m.megolm_backup.v1: bad MAC` version of this with the backup key secret, here's a clear repo case:
> 
>     * Create a new account and setup 4S with key backup during registration
> 
>     * Try to reset the cross-signing in Settings after login

I just tried this, and it worked fine for me :confused:

**Comment by uhoreg** [comment]
Nobody seems to have run into this recently, so closing now.
