### ISSUE TITLE
verification is cancelled because of crash while cross-signing

### ISSUE THREAD

**Issue by bwindels** [vector-im/riot-web#13105]
Stack trace:
```
TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
    at Object.getSecretStorageKey (https://sw1v.riot.sw1v.org/bundles/48795db129c835dd0ea9/bundle.js:2:301276)
    at c._getSecretStorageKey (https://sw1v.riot.sw1v.org/bundles/48795db129c835dd0ea9/bundle.js:2:1594573)
    at c.get (https://sw1v.riot.sw1v.org/bundles/48795db129c835dd0ea9/bundle.js:2:1591094)
    at async Function.getFromSecretStorage (https://sw1v.riot.sw1v.org/bundles/48795db129c835dd0ea9/bundle.js:2:284765)
    at async c.getCrossSigningKey (https://sw1v.riot.sw1v.org/bundles/48795db129c835dd0ea9/bundle.js:2:283905)
    at async c.signObject (https://sw1v.riot.sw1v.org/bundles/48795db129c835dd0ea9/bundle.js:2:287387)
    at async I.setDeviceVerification (https://sw1v.riot.sw1v.org/bundles/48795db129c835dd0ea9/bundle.js:2:225641)
    at async I (https://sw1v.riot.sw1v.org/bundles/48795db129c835dd0ea9/bundle.js:2:993537)
    at async k._verifyKeys (https://sw1v.riot.sw1v.org/bundles/48795db129c835dd0ea9/bundle.js:2:729993)
    at async k._checkMAC (https://sw1v.riot.sw1v.org/bundles/48795db129c835dd0ea9/bundle.js:2:1601504)
```

Which causes the verification to cancel:
```
2020-04-09T10:15:12.756Z I Verification request xrtuT9xuBsjYKxQf1gZ1UOgPw8ntecRV: m.key.verification.cancel event with id:undefined, content:{"code":"m.unknown","reason":"TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))","transaction_id":"xrtuT9xuBsjYKxQf1gZ1UOgPw8ntecRV"} deviceId:UNNTRAUEWU, sender:@richvdh:sw1v.org, isSentByUs:true, isLiveEvent:true, isRemoteEcho:true, phase:4=>5, observeOnly:false=>false
```

Rageshakes from both parties:
 - https://github.com/matrix-org/riot-web-rageshakes/issues/2566
 - https://github.com/matrix-org/riot-web-rageshakes/issues/2567

**Comment by bwindels** [comment]
`keyInfos` seems to be an empty array at https://github.com/matrix-org/matrix-react-sdk/blob/develop/src/CrossSigningManager.js#L73

**Comment by bwindels** [comment]
I think this is because https://github.com/matrix-org/matrix-js-sdk/blob/v5.1.1/src/crypto/SecretStorage.js#L312 doesn't handle symmetrical encryption for 4S yet (in v5.1.1 of the js-sdk), e.g. `m.secret_storage.v1.aes-hmac-sha2` in the switch. As the user was also using their account on riot.im/develop it would indeed be expected that their 4S would have been migrated to symmetrical encryption already.

**Comment by bwindels** [comment]
Closing this as it should not occur anymore in a recent version that supports symmetrical 4S.

**Comment by Redsandro** [comment]
Any chance you could take a look at https://github.com/element-hq/element-web/issues/15970#issuecomment-1830479560 and see if it's similar? A lot of us are facing this issue, but we can't figure out the exact problem.
