### ISSUE TITLE
Nightly: Right clicking an image -> Save image as = Error + Save dialog

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#13845]
At least on windows. Here's a snapshot:
![](https://i.imgur.com/wvXMlHM.png)

**Comment by t3chguy** [comment]
```
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be one of type string, Buffer, or URL. Received type object
    at Object.open (fs.js:406:10)
    at Object.module.<computed> (electron/js2c/asar.js:163:31)
    at Object.module.<computed> [as open] (electron/js2c/asar.js:163:31)
    at WriteStream.open (internal/fs/streams.js:289:6)
    at new WriteStream (internal/fs/streams.js:269:10)
    at Object.createWriteStream (fs.js:1807:10)
    at click (C:\Users\7t3ch\AppData\Local\riot-desktop-nightly\app-0.0.1-nightly2020053101\resources\app.asar\src\webcontents-handler.js:109:50)
    at MenuItem.click (electron/js2c/browser_init.js:1501:9)
    at Function.executeCommand (electron/js2c/browser_init.js:1762:13) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

**Comment by t3chguy** [comment]
This isn't a new regression, might be from updating to electron 7/8, but would be a nice thing to fix as save-as is entirely broken in Electron
