### ISSUE TITLE
Room switching time has increased

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#13973]
I'm probably to blame with one of the many concurrently-running stores floating around

**Comment by turt2live** [comment]
counting this as new-room-list work until proven otherwise

**Comment by turt2live** [comment]
```
rageshake.js?16c9:65 MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 501 Event.decrypted listeners added. Use emitter.setMaxListeners() to increase limit
    at _addListener (webpack-internal:///28:210:15)
    at MatrixClient.addListener (webpack-internal:///28:226:10)
    at new RoomNotificationState (webpack-internal:///592:141:76)
    at ListNotificationState.setRooms (webpack-internal:///592:297:21)
    at RoomSublist2.componentDidUpdate (webpack-internal:///587:97:34)
    at commitLifeCycles (webpack-internal:///48:19835:22)
    at commitLayoutEffects (webpack-internal:///48:22803:7)
    at HTMLUnknownElement.callCallback (webpack-internal:///48:188:14)
    at Object.invokeGuardedCallbackDev (webpack-internal:///48:237:16)
    at invokeGuardedCallback (webpack-internal:///48:292:31)
```

**Comment by turt2live** [comment]
I think this is mostly just my chrome being sad these days

**Comment by 3nprob** [comment]
Could this be part of the story behind either very slow UI load/navigation times or occasional complete UI freezes on element-desktop?Seeing both of those a lot, but only on a profile with huge amounts of rooms and messages - other profiles in the otherwise same environments don't have these issues nor these warnings.

In the case of the below, the came after this sequence:

1. start element-desktop on existing signed in profile
2. element-desktop opens, starting to load the sidebar and the most recently viewed room (which only has 2 participants and <200 messages total, all <2months old)
3. Sidebar and the last 2 messages in the room are loaded and rendered after 1m07s.

The rest of the messages never load, there is just a spinner.

Looking at the `Network` tab, there are 515 eternally pending requests for thumbnails from the HS but otherwise no failed or pending requests.

The log below starts after the 1m07 mark.

element-desktop 1.11.0 on Linux with Wayland.

```
[...]

Ready to encrypt events for !fOuOTZQyATDqfvoQuf:remerge.net

Returning cached capabilities

[getType] Room !barfoo:example.com does not have an m.room.create event

[getType] Room !foobar:matrix.org does not have an m.room.create event

MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 501 Event.decrypted listeners added. Use emitter.setMaxListeners() to increase limit
    at d (vector://vector/webapp/bundles/cbf8502bc188a87db8eb/vendors~init.js:2:15038)
    at s.addListener (vector://vector/webapp/bundles/cbf8502bc188a87db8eb/vendors~init.js:2:17622)
    at X.on (vector://vector/webapp/bundles/cbf8502bc188a87db8eb/vendors~init.js:2:479103)
    at new E (vector://vector/webapp/bundles/cbf8502bc188a87db8eb/vendors~init.js:2:631809)
    at k.getRoomState (vector://vector/webapp/bundles/cbf8502bc188a87db8eb/vendors~init.js:2:636542)
    at v.V [as getRoomFn] (vector://vector/webapp/bundles/cbf8502bc188a87db8eb/vendors~init.js:2:426564)
    at v.setRooms (vector://vector/webapp/bundles/cbf8502bc188a87db8eb/vendors~init.js:2:424066)
    at vector://vector/webapp/bundles/cbf8502bc188a87db8eb/vendors~init.js:2:431587
    at Array.forEach (<anonymous>)
    at G.updateNotificationStates (vector://vector/webapp/bundles/cbf8502bc188a87db8eb/vendors~init.js:2:431459)


MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 501 accountData listeners added. Use emitter.setMaxListeners() to increase limit
    at d (vector://vector/webapp/bundles/cbf8502bc188a87db8eb/vendors~init.js:2:15038)
    at s.addListener (vector://vector/webapp/bundles/cbf8502bc188a87db8eb/vendors~init.js:2:17622)
    at X.on (vector://vector/webapp/bundles/cbf8502bc188a87db8eb/vendors~init.js:2:479103)
    at new E (vector://vector/webapp/bundles/cbf8502bc188a87db8eb/vendors~init.js:2:631859)
    at k.getRoomState (vector://vector/webapp/bundles/cbf8502bc188a87db8eb/vendors~init.js:2:636542)
    at v.V [as getRoomFn] (vector://vector/webapp/bundles/cbf8502bc188a87db8eb/vendors~init.js:2:426564)
    at v.setRooms (vector://vector/webapp/bundles/cbf8502bc188a87db8eb/vendors~init.js:2:424066)
    at vector://vector/webapp/bundles/cbf8502bc188a87db8eb/vendors~init.js:2:431587
    at Array.forEach (<anonymous>)
    at G.updateNotificationStates (vector://vector/webapp/bundles/cbf8502bc188a87db8eb/vendors~init.js:2:431459)

Regenerating all room lists

Resetting known rooms, initiating regeneration

Resetting known rooms, initiating regeneration

MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 501 RoomState.events listeners added. Use emitter.setMaxListeners() to increase limit
    at d (vector://vector/webapp/bundles/cbf8502bc188a87db8eb/vendors~init.js:2:15038)
    at s.addListener (vector://vector/webapp/bundles/cbf8502bc188a87db8eb/vendors~init.js:2:17622)
    at X.on (vector://vector/webapp/bundles/cbf8502bc188a87db8eb/vendors~init.js:2:479103)
    at w.componentDidMount (vector://vector/webapp/bundles/cbf8502bc188a87db8eb/vendors~init.js:2:402204)
    at hs (vector://vector/webapp/bundles/cbf8502bc188a87db8eb/vendors~init.js:2:3068047)
    at Cl (vector://vector/webapp/bundles/cbf8502bc188a87db8eb/vendors~init.js:2:3085105)
    at t.unstable_runWithPriority (vector://vector/webapp/bundles/cbf8502bc188a87db8eb/vendors~init.js:2:3110390)
    at zi (vector://vector/webapp/bundles/cbf8502bc188a87db8eb/vendors~init.js:2:3026982)
    at Fl (vector://vector/webapp/bundles/cbf8502bc188a87db8eb/vendors~init.js:2:3081650)
    at hl (vector://vector/webapp/bundles/cbf8502bc188a87db8eb/vendors~init.js:2:3077761)

MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 501 sync listeners added. Use emitter.setMaxListeners() to increase limit
    at d (vector://vector/webapp/bundles/cbf8502bc188a87db8eb/vendors~init.js:2:15038)
    at s.addListener (vector://vector/webapp/bundles/cbf8502bc188a87db8eb/vendors~init.js:2:17622)
    at X.on (vector://vector/webapp/bundles/cbf8502bc188a87db8eb/vendors~init.js:2:479103)
    at vector://vector/webapp/bundles/cbf8502bc188a87db8eb/vendors~init.js:2:306076
    at Rl (vector://vector/webapp/bundles/cbf8502bc188a87db8eb/vendors~init.js:2:3086677)
    at t.unstable_runWithPriority (vector://vector/webapp/bundles/cbf8502bc188a87db8eb/vendors~init.js:2:3110390)
    at zi (vector://vector/webapp/bundles/cbf8502bc188a87db8eb/vendors~init.js:2:3026982)
    at Dl (vector://vector/webapp/bundles/cbf8502bc188a87db8eb/vendors~init.js:2:3086140)
    at hl (vector://vector/webapp/bundles/cbf8502bc188a87db8eb/vendors~init.js:2:3077441)
    at vector://vector/webapp/bundles/cbf8502bc188a87db8eb/vendors~init.js:2:3027205
```
