### ISSUE TITLE
riot-desktop's Seshat undefined symbol issue

### ISSUE THREAD

**Issue by dylangerdaly** [vector-im/riot-web#14052]
### Description

Can't enable E2EE Searching because Sashat isn't working, from what I can tell this has something to do with the Electron Version

### Steps to reproduce
Run `yarn run build:native`

Logs being sent: yes
```
yarn run v1.21.1
warning ../package.json: No license field
$ electron . --force-device-scale-factor=1.2 --profile-dir=/home/user/.config/Riot_Profile1
Keytar unexpected error: Error: Module did not self-register: '/home/user/riot-desktop/.hak/hakModules/keytar/build/Release/keytar.node'.
    at process.func [as dlopen] (electron/js2c/asar.js:140:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1034:18)
    at Object.func [as .node] (electron/js2c/asar.js:140:31)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:738:28)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/user/riot-desktop/.hak/hakModules/keytar/lib/keytar.js:1:14)
    at Module._compile (internal/modules/cjs/loader.js:967:30)
Seshat unexpected error: Error: /home/user/riot-desktop/.hak/hakModules/matrix-seshat/native/index.node: undefined symbol: _ZN2v816FunctionTemplate3NewEPNS_7IsolateEPFvRKNS_20FunctionCallbackInfoINS_5ValueEEEENS_5LocalIS4_EENSA_INS_9SignatureEEEiNS_19ConstructorBehaviorENS_14SideEffectTypeE
    at process.func [as dlopen] (electron/js2c/asar.js:140:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1034:18)
    at Object.func [as .node] (electron/js2c/asar.js:140:31)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:738:28)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/user/riot-desktop/.hak/hakModules/matrix-seshat/lib/index.js:15:16)
    at Module._compile (internal/modules/cjs/loader.js:967:30)
(node:1894) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
No update_base_url is defined: auto update is disabled
```

### Version information

- **Platform**: Desktop

For the desktop app:

- **OS**: Linux
- **Version**: develop

**Comment by dylangerdaly** [comment]
This has fixed itself in the latest develop branch: https://github.com/vector-im/riot-desktop/commit/3597f43b73d87c04dc3ee34a17c952279c70b528
