### ISSUE TITLE
element-desktop-nightly will not start

### ISSUE THREAD

**Issue by richvdh** [vector-im/riot-web#14720]
```
$ element-desktop-nightly 
/home/rav/.config/Element-Nightly exists: no
/home/rav/.config/Riot-Nightly exists: no
xdg-settings: default-url-scheme-handler not implemented for xfce
(node:29463) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
Couldn't find webapp files in any of: 
	/opt/Element-Nightly/resources/app.asar/webapp.asar
	/opt/Element-Nightly/resources/webapp.asar
	/opt/Element-Nightly/resources/app.asar/webapp
	/opt/Element-Nightly/resources/webapp
App setup failed: exiting Error: Failed to find webapp files
    at tryPaths (/opt/Element-Nightly/resources/app.asar/src/electron-main.js:155:11)
    at async setupGlobals (/opt/Element-Nightly/resources/app.asar/src/electron-main.js:161:16)
    at async App.<anonymous> (/opt/Element-Nightly/resources/app.asar/src/electron-main.js:768:9)
```

package version is `2020072301`.

**Comment by richvdh** [comment]
```
rav@fred:~$ ls -l /opt/Element-Nightly/resources/
total 17544
-rw-r--r-- 1 root root 17959921 Jul 23 09:46 app.asar
drwxr-xr-x 2 root root     4096 Jul 23 10:29 img
```

should there be a `webapp.asar` there?

**Comment by t3chguy** [comment]
![image](https://user-images.githubusercontent.com/2403652/88272964-67355100-ccd1-11ea-99c7-37085c34aeb7.png)


Indeed, it is somehow missing though

**Comment by jryans** [comment]
@richvdh There should now be a (hopefully) correct `2020072302` build, can you confirm?

**Comment by richvdh** [comment]
better!
