### ISSUE TITLE
No files (any files) displayed under "Files"

### ISSUE THREAD

**Issue by odiferousmint** [vector-im/riot-web#14761]
### Description

When I click on "Files" in both the desktop and the Android version of Element, it says something like: "There are no visible files in this room". I think on the Android version it even omits the term "visible". I cannot check right now. In any case, what does this mean given that we (person with whom I have a private room) did actually upload files? Is this a bug? I would like to see it similarly to how WhatsApp shows it, for example. I expected to see a list of uploaded files (even in an encrypted room), including any files, photos, videos, and so forth. It would definitely help as right now I need to scroll up which takes a long time, and IIRC the search does not support `has: image` and so forth.

### Version information

- **OS**: Arch Linux
- **Version**: 1.7.1 (element-desktop)

**Comment by t3chguy** [comment]
Sounds like the Arch 1.7.1 build you are using is not including Seshat for indexing encrypted messages.

Check Settings > Security & Privacy > Message Search

![image](https://user-images.githubusercontent.com/2403652/88454331-c082b900-ce66-11ea-800b-f4d801888439.png)

![image](https://user-images.githubusercontent.com/2403652/88454326-b95bab00-ce66-11ea-9bc5-b41a048dae72.png)

Should look like the above.

**Comment by odiferousmint** [comment]
Hmm yeah, I do have this:
![2020-07-25-120727_386x112_scrot](https://user-images.githubusercontent.com/43568459/88454367-6c300700-ce6f-11ea-8b39-36b947b79c8c.png)

**Comment by odiferousmint** [comment]
On Android when I go to a room's "Uploads", it does show the uploaded media, so disregard that.

**Comment by t3chguy** [comment]
@ArchangeGabriel any idea why this might happen (assuming this is your Arch package)

**Comment by ArchangeGabriel** [comment]
It works perfectly well for me… @odiferousmint Can you run from the terminal and paste any output?

**Comment by odiferousmint** [comment]
```
Keytar unexpected error: Error: /tmp/.org.chromium.Chromium.N39EcY: failed to map segment from shared object
    at process.func [as dlopen] (electron/js2c/asar.js:140:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1034:18)
    at Object.func [as .node] (electron/js2c/asar.js:149:18)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/usr/lib/element/app.asar/node_modules/keytar/lib/keytar.js:1:14)
    at Module._compile (internal/modules/cjs/loader.js:967:30)
Seshat unexpected error: Error: /tmp/.org.chromium.Chromium.2ptc4V: failed to map segment from shared object
    at process.func [as dlopen] (electron/js2c/asar.js:140:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1034:18)
    at Object.func [as .node] (electron/js2c/asar.js:149:18)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/usr/lib/element/app.asar/node_modules/matrix-seshat/lib/index.js:15:16)
    at Module._compile (internal/modules/cjs/loader.js:967:30)
[...]
```

Worth noting that I am running it with `firejail`, what do you think is the issue here so I could potentially lift some restrictions?

**Comment by t3chguy** [comment]
Glad you got it figured out

**Comment by t3chguy** [comment]
(I'm guessing its having to extract the seshat executable from the asar archive into tmp and execute it from there)

**Comment by ArchangeGabriel** [comment]
> (I'm guessing its having to extract the seshat executable from the asar archive into tmp and execute it from there)

Exactly.
