### ISSUE TITLE
compile error when npm install

### ISSUE THREAD

**Issue by wjhtinger** [vector-im/riot-web#2738]
[wangjh@localhost vector-web]$  npm install
npm WARN optional dep failed, continuing fsevents@1.0.15
npm WARN optional dep failed, continuing fsevents@1.0.15
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated to-iso-string@0.0.2: to-iso-string has been deprecated, use @segment/to-iso-string instead.
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN optional dep failed, continuing fsevents@1.0.15

> phantomjs-prebuilt@2.1.14 install /home/wangjh/work/vector-web/vector-web/node_modules/phantomjs-prebuilt
> node install.js

PhantomJS not found on PATH
Download already available at /tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2
Verified checksum of previously downloaded file
Extracting tar contents (via spawned process)
Removing /home/wangjh/work/vector-web/vector-web/node_modules/phantomjs-prebuilt/lib/phantom
Copying extracted folder /tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2-extract-1481602138100/phantomjs-2.1.1-linux-x86_64 -> /home/wangjh/work/vector-web/vector-web/node_modules/phantomjs-prebuilt/lib/phantom
Writing location.js file
Done. Phantomjs binary available at /home/wangjh/work/vector-web/vector-web/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs
npm WARN optional dep failed, continuing 7zip-bin-mac@1.0.1
npm WARN optional dep failed, continuing 7zip-bin-win@2.0.2
npm WARN optional dep failed, continuing fsevents@1.0.15
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN peerDependencies The peer dependency immutable@3.x.x included from draft-js-export-markdown will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN peerDependencies The peer dependency immutable@3.x.x included from draft-js-export-html will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN peerDependencies The peer dependency immutable@3.x.x included from draft-js-utils will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
-
> riot-web@0.9.1 prepublish /home/wangjh/work/vector-web/vector-web
> npm run build:compile

> riot-web@0.9.1 build:compile /home/wangjh/work/vector-web/vector-web
> babel --source-maps -d lib src

SyntaxError: Unexpected identifier (While processing preset: "/home/wangjh/work/vector-web/vector-web/node_modules/babel-preset-es2015/lib/index.js")
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/wangjh/work/vector-web/vector-web/node_modules/babel-preset-es2015/node_modules/babel-plugin-transform-es2015-parameters/node_modules/babel-template/node_modules/lodash/keys.js:1:83)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)

npm ERR! Linux 4.5.5-300.fc24.x86_64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "build:compile"
npm ERR! node v4.6.0
npm ERR! npm  v2.15.9
npm ERR! code ELIFECYCLE
npm ERR! riot-web@0.9.1 build:compile: `babel --source-maps -d lib src`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the riot-web@0.9.1 build:compile script 'babel --source-maps -d lib src'.
npm ERR! This is most likely a problem with the riot-web package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     babel --source-maps -d lib src
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs riot-web
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls riot-web
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/wangjh/work/vector-web/vector-web/npm-debug.log

npm ERR! Linux 4.5.5-300.fc24.x86_64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v4.6.0
npm ERR! npm  v2.15.9
npm ERR! code ELIFECYCLE
npm ERR! riot-web@0.9.1 prepublish: `npm run build:compile`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the riot-web@0.9.1 prepublish script 'npm run build:compile'.
npm ERR! This is most likely a problem with the riot-web package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build:compile
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs riot-web
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls riot-web
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/wangjh/work/vector-web/vector-web/npm-debug.log

What's wrong?

**Comment by wjhtinger** [comment]
New version is OK. Close.
