### ISSUE TITLE
Riot now fails fairly ungracefully in Tor browser

### ISSUE THREAD

**Issue by dbkr** [vector-im/riot-web#4379]

**Comment by ara4n** [comment]
is this a dup of https://github.com/vector-im/riot-web/issues/4238?

**Comment by dbkr** [comment]
Possibly, although I was initially testing with Tor browser 6.5

**Comment by richvdh** [comment]
@dbkr: could you be more specific?

**Comment by richvdh** [comment]
I suspect it's related to https://github.com/vector-im/riot-web/issues/4340 (ie, we barf if indexeddb fails)

**Comment by lampholder** [comment]
Testing with 7.0.1 (based on ff 52.2.0) - I get the modernizr warning then inifinispinner.

Looks likely to be a indexddb thing: `Error: must pass indexedDB into IndexedDBCryptoStore  bundle.js:120:1446`

Full log:
```
downloadable font: kern: Too large subtable, table discarded (font-family: "Open Sans" style:normal weight:normal stretch:normal src index:0) source: https://riot.im/app/fonts/Open_Sans/OpenSans-Regular.ttf  theme-light.css:1:68041
TypeError: asm.js type error: Disabled by 'asmjs' runtime option  olm.js
Browser missing feature: 'indexeddb'  bundle.js:82:19408
"Initialised rageshake: See https://bugs.chromium.org/p/chromium/issues/detail?id=583193 to fix line numbers on Chrome."  bundle.js:82:19408
set language to en-us  bundle.js:82:19408
"Vector starting at https://riot.im/app/"  bundle.js:82:19408
Browser is missing required features.  bundle.js:82:19408
downloadable font: kern: Too large subtable, table discarded (font-family: "Open Sans" style:normal weight:bold stretch:normal src index:0) source: https://riot.im/app/fonts/Open_Sans/OpenSans-Bold.ttf  theme-light.css:1:68608
User accepts the compatibility risks.  bundle.js:82:19408
set language to en-us  bundle.js:82:19408
User has previously accepted risks in using an unsupported browser  bundle.js:82:19408
"Vector starting at https://riot.im/app/"  bundle.js:82:19408
No previous session found.  bundle.js:82:19408
"Doing guest login on https://matrix.org"  bundle.js:82:19408
Unable to load session Error: must pass indexedDB into IndexedDBCryptoStore
Stack trace:
e@https://riot.im/app/bundles/cb81721f371eda52f2e4/bundle.js:120:1446
@https://riot.im/app/bundles/cb81721f371eda52f2e4/bundle.js:39:632
e.exports.createClient@https://riot.im/app/bundles/cb81721f371eda52f2e4/bundle.js:120:9782
a@https://riot.im/app/bundles/cb81721f371eda52f2e4/bundle.js:87:667
i/<@https://riot.im/app/bundles/cb81721f371eda52f2e4/bundle.js:87:147
r@https://riot.im/app/bundles/cb81721f371eda52f2e4/bundle.js:27:8950
g.prototype.then/</<@https://riot.im/app/bundles/cb81721f371eda52f2e4/bundle.js:27:9223
g/r.promiseDispatch@https://riot.im/app/bundles/cb81721f371eda52f2e4/bundle.js:27:2944
g.prototype.then/<@https://riot.im/app/bundles/cb81721f371eda52f2e4/bundle.js:27:9174
r@https://riot.im/app/bundles/cb81721f371eda52f2e4/bundle.js:27:6501
e@https://riot.im/app/bundles/cb81721f371eda52f2e4/bundle.js:27:6439
o@https://riot.im/app/bundles/cb81721f371eda52f2e4/bundle.js:82:8788
a@https://riot.im/app/bundles/cb81721f371eda52f2e4/bundle.js:82:8966
u/n@https://riot.im/app/bundles/cb81721f371eda52f2e4/bundle.js:82:9325
  bundle.js:82:19408
Error: must pass indexedDB into IndexedDBCryptoStore  bundle.js:120:1446
XML Parsing Error: syntax error
Location: https://riot.im/app/version?cachebuster=1498036540300
Line Number 1, Column 1:  version:1:1
Initialised anonymous analytics  bundle.js:82:19408
XML Parsing Error: syntax error
Location: https://riot.im/app/version?cachebuster=1498037140300
Line Number 1, Column 1:  version:1:1
XML Parsing Error: syntax error
Location: https://riot.im/app/version?cachebuster=1498037740300
Line Number 1, Column 1:  version:1:1
TypeError: n is null[Learn More]  bundle.js:149:10768
```

**Comment by dbkr** [comment]
Yeah, what @lampholder said - for me it went straight to infinite spinner, but I'd probably clicked through the warning screen on a previous run many moons ago

**Comment by richvdh** [comment]
p3 critical, @lampholder ?

fixed by https://github.com/matrix-org/matrix-js-sdk/issues/473, anyway

**Comment by lampholder** [comment]
p3 because it wasn't affecting many users, critical 'cause those it is affecting it's affecting _completely_.

That was my rationale, anyway... :P
