### ISSUE TITLE
Pasting/writing long messages in RTE lead to scrollbars & bad offsets

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#4414]
### Description

Pasting a stacktrace, for example, ends up with the following presentation:
![image](https://user-images.githubusercontent.com/1190097/27545142-53ed12ea-5a4c-11e7-948a-308640afc398.png)

Here's the sample message sent (incl. backticks):
```
2017-06-26 16:40:37.936 ERROR 19827 --- [http-nio-9005-exec-8] i.k.m.b.e.c.ApplicationServiceController : Error when processing PUT /transactions/7855

java.lang.NullPointerException: null
        at io.kamax.matrix.json.MatrixJsonObject.getInt(MatrixJsonObject.java:56) ~[matrix-java-sdk.jar!/:na]
        at io.kamax.matrix.json.event.MatrixJsonEvent.<init>(MatrixJsonEvent.java:46) ~[matrix-java-sdk.jar!/:na]
        at io.kamax.matrix.json.event.MatrixJsonRoomEvent.<init>(MatrixJsonRoomEvent.java:31) ~[matrix-java-sdk.jar!/:na]
        at io.kamax.matrix.json.event.MatrixJsonRoomMembershipEvent.<init>(MatrixJsonRoomMembershipEvent.java:37) ~[matrix-java-sdk.jar!/:na]
        at io.kamax.matrix.json.MatrixJsonEventFactory.get(MatrixJsonEventFactory.java:35) ~[matrix-java-sdk.jar!/:na]
        at io.kamax.matrix.bridge.email.controller.ApplicationServiceController.getTransaction(ApplicationServiceController.java:135) ~[classes!/:na]
        at sun.reflect.GeneratedMethodAccessor38.invoke(Unknown Source) ~[na:na]
```

### Steps to reproduce

- Write a long message
- See scrollbars

Log: not sent    

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 59
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by lukebarnard1** [comment]
This is just any text that doesn't have any spaces in it so it's something wrong with the word breaking.
