### ISSUE TITLE
Unhelpful error when entering invalid username

### ISSUE THREAD

**Issue by t3chguy** [vector-im/riot-web#4660]
![image](https://user-images.githubusercontent.com/2403652/28491051-f6adb5fe-6ee0-11e7-8aff-fee22b7f5f2c.png)

Obviously the chars are not valid in a username/localpart, but the error should be a little more helpful about it
riot.im/develop

**Comment by turt2live** [comment]
What's the server-side error? Likely encoding issues, but just want to make sure.

**Comment by t3chguy** [comment]
Register page does see `Wizard 𝖙3𝖈𝖍𝖌𝖚𝖞` as invalid, but the "Please pick a username" dialog does not and passes it to Synapse.

**Comment by t3chguy** [comment]
```
2017-07-23 20:24:09,231 - synapse.access.http.8008 - 59 - INFO - GET-3471131- 90.255.116.117 - 8008 - Received request: GET /_matrix/client/r0/r
egister/available?username=Wizard%20%F0%9D%96%993%F0%9D%96%88%F0%9D%96%8D%F0%9D%96%8C%F0%9D%96%9A%F0%9D%96%9E
2017-07-23 20:24:09,232 - synapse.http.server - 139 - ERROR - GET-3471131- Failed handle request synapse.http.server._async_render on <synapse.r
est.ClientRestResource object at 0x7ff20d7db8d0>: <XForwardedForRequest at 0x7ff1a294b3b0 method=GET uri=/_matrix/client/r0/register/available?u
sername=Wizard%20%F0%9D%96%993%F0%9D%96%88%F0%9D%96%8D%F0%9D%96%8C%F0%9D%96%9A%F0%9D%96%9E clientproto=HTTP/1.0 site=8008>
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/synapse/http/server.py", line 116, in wrapped_request_handler
    yield request_handler(self, request, request_metrics)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1126, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/usr/lib/python2.7/dist-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/usr/lib/python2.7/dist-packages/synapse/http/server.py", line 255, in _async_render
    callback_return = yield callback(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1126, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/usr/lib/python2.7/dist-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/usr/lib/python2.7/dist-packages/synapse/rest/client/v2_alpha/register.py", line 152, in on_GET
    yield self.registration_handler.check_username(username)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1128, in _inlineCallbacks
    result = g.send(result)
  File "/usr/lib/python2.7/dist-packages/synapse/handlers/register.py", line 50, in check_username
    if urllib.quote(localpart.encode('utf-8')) != localpart:
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf0 in position 7: ordinal not in range(128)
```

**Comment by lampholder** [comment]
Yuk yuk yuk :P

**Comment by t3chguy** [comment]
![image](https://user-images.githubusercontent.com/2403652/28777694-2802f74e-75f4-11e7-90ba-ce6ba1f22123.png)
