### ISSUE TITLE
Unable to connect to IPv6 homeserver

### ISSUE THREAD

**Issue by V10lator** [vector-im/riot-web#4816]
### Description

I tried to setup a homeserver on a IPv6 only vserver. Then I tried to connect via https://riot.im/app/#/register but all I get is "Internal server error".

### Steps to reproduce

- Setup matrix-synapse on a IPv6 only server (alternatively: block IPv4 traffic with a firewall).
- Go to https://riot.im/app/#/register
- Try to connect to your custom server.

Log: not sent

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chromium 58.0.3029.110 (64-bit)
- **OS**: Gentoo Linux
- **URL**: riot.im/app /

**Comment by t3chguy** [comment]
I presume you tested the IPv6 compatibility of both the client machine in question and the browser you are using?

**Comment by V10lator** [comment]
Yes. For example I'm getting 10 of 10 points when browsing to http://test-ipv6.com with the same browser.

**Comment by t3chguy** [comment]
what happens if you try to browse to matrix.org/_matrix/federation/v1/version (with matrix.org replaced with your domain/IP?)

**Comment by t3chguy** [comment]
Also, the reason could be the browser only trying IPv4 if the domain you are using has an A record and not even attempting IPv6 (AAAA)

**Comment by V10lator** [comment]
I get

`{"server":{"version":"0.22.1","name":"Synapse"}}`

The server is reachable via IPv6 only, there is no A record:

```
$ nslookup [CENSORED] 8.8.8.8
Server:         8.8.8.8
Address:        8.8.8.8#53

Non-authoritative answer:
Name:   [CENSORED]
Address: 2001:bc8:[CENSORED]
```

**Comment by ara4n** [comment]
the problem may be that the identity server can't connect back to your HS. try skipping setting an email during registration?

**Comment by ara4n** [comment]
alternatively, what is the error you're seeing in your HS logs?

**Comment by V10lator** [comment]
I tried without e-mail, still the same.

```
2017-08-19 14:35:19,094 - synapse.http.client - 112 - INFO - POST-3- Error sending request to  POST https://matrix.org/_matrix/identity/api/v1/validate/msisdn/requestToken: TimeoutError 
2017-08-19 14:35:19,095 - synapse.http.server - 139 - ERROR - POST-3- Failed handle request synapse.http.server._async_render on <synapse.rest.ClientRestResource object at 0x7fe566d54690>: <XForwardedForRequest at 0x7fe56c826cf8 method=POST uri=/_matrix/client/r0/register/msisdn/requestToken clientproto=HTTP/1.0 site=8008>
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/synapse/http/server.py", line 116, in wrapped_request_handler
    yield request_handler(self, request, request_metrics)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1297, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/usr/lib/python2.7/dist-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/usr/lib/python2.7/dist-packages/synapse/http/server.py", line 255, in _async_render
    callback_return = yield callback(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1297, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/usr/lib/python2.7/dist-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/usr/lib/python2.7/dist-packages/synapse/rest/client/v2_alpha/register.py", line 115, in on_POST
    ret = yield self.identity_handler.requestMsisdnToken(**body)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1297, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/usr/lib/python2.7/dist-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/usr/lib/python2.7/dist-packages/synapse/handlers/identity.py", line 199, in requestMsisdnToken
    params
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1297, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/usr/lib/python2.7/dist-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/usr/lib/python2.7/dist-packages/synapse/http/client.py", line 150, in post_json_get_json
    bodyProducer=FileBodyProducer(StringIO(json_str))
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1297, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/usr/lib/python2.7/dist-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/usr/lib/python2.7/dist-packages/synapse/http/client.py", line 114, in request
    raise e
TimeoutError: User timeout caused connection failure.
```

(vector.im doesn't have an AAAA record, so testing it is useless and I'm not aware of any other identity servers).

**Comment by dbkr** [comment]
So @ara4n was right in that it's the ID server hit timing out (but this time on the phone number rather than the email address). The workaround would be to try without either a phone number or email address.

**Comment by V10lator** [comment]
Thanks, that worked. Is this a known bug?

Anyway now I can't get the public room list. The error seems to be `InvalidAddressError: IPv4 port write() called with IPv6 address`. For reference the log (you need IPv6 connectivity to be able to see it) : http://nl01-v6.v10lator.de/matrix.txt - Should I report this to the matrix-synapse developers?

**Comment by robintown** [comment]
The situation here has probably changed in the past 5 years as IPv6 support has been stabilizing, but if this is still a problem, any remaining issues should be opened elsewhere, i.e. either on the Synapse or identity server repos.
