### ISSUE TITLE
Google Docs widget works only partially on Firefox

### ISSUE THREAD

**Issue by killua-eu** [vector-im/riot-web#4900]
### Description

Tried to add the publicly available google doc https://docs.google.com/document/d/1lWOh2U85ZQ9mJq0QMwj6WDVvbDDj-AaImfD-FRnD0UE/edit , only google docs ui loads, no content to be seen / to be edited. This happens solely on firefox (tried up to the latest FF beta available: 56.0~b6+build1-0ubuntu0.17.04.1, works well on chromium). The console output tells:

```
"Initialised rageshake: See https://bugs.chromium.org/p/chromium/issues/detail?id=583193 to fix line numbers on Chrome."  rageshake.js:65:16
set language to en-us  rageshake.js:65:16
"Vector starting at https://chat.private-matrix-server.com/#/room/!ualEsMujkGtoanhaWE:my.private-matrix-server.com"  rageshake.js:65:16
Restoring session for @pavel:my.private-matrix-server.com  rageshake.js:65:16
"setLoggedIn: mxid: @pavel:my.private-matrix-server.com deviceId: KDBIQAMMIG guest: false hs: https://my.private-matrix-server.com:443"  rageshake.js:65:16
Session persisted for @pavel:my.private-matrix-server.com  rageshake.js:65:16
Lifecycle: Starting MatrixClient  rageshake.js:65:16
IndexedDBStore.startup: connecting to backend  rageshake.js:65:16
MatrixClientPeg: waiting for MatrixClient store to initialise  rageshake.js:65:16
Switching to room id !ualEsMujkGtoanhaWE:my.private-matrix-server.com at event undefined  rageshake.js:65:16
IndexedDB worker is ready  rageshake.js:65:16
LocalIndexedDBStoreBackend.connect: connecting  indexeddb-worker.js:4:25416
LocalIndexedDBStoreBackend.connect: awaiting connection  indexeddb-worker.js:4:25784
LocalIndexedDBStoreBackend.connect: connected  indexeddb-worker.js:4:25884
LocalIndexedDBStoreBackend: loading account data  indexeddb-worker.js:4:28463
LocalIndexedDBStoreBackend: loaded account data  indexeddb-worker.js:4:28552
LocalIndexedDBStoreBackend: loaded sync data  indexeddb-worker.js:4:28790
LocalIndexedDBStoreBackend: loaded sync data  indexeddb-worker.js:4:28875
LocalIndexedDBStoreBackend: loaded initial data  indexeddb-worker.js:4:26178
IndexedDBStore.startup: loading presence events  rageshake.js:65:16
IndexedDBStore.startup: processing presence events  rageshake.js:65:16
MatrixClientPeg: really starting MatrixClient  rageshake.js:65:16
MatrixClientPeg: MatrixClient started  rageshake.js:65:16
Failed to poll for update Object { status: 404 }  rageshake.js:65:16
Looking for queued outgoing room key requests  rageshake.js:65:16
connecting to indexeddb matrix-js-sdk:crypto  rageshake.js:65:16
connected to indexeddb matrix-js-sdk:crypto  rageshake.js:65:16
No more outgoing room key requests  rageshake.js:65:16
Got TURN URIs: turn:my.private-matrix-server.com:3478?transport=udp,turn:my.private-matrix-server.com:3478?transport=tcp refresh in 86400 secs  rageshake.js:65:16
Got push rules  rageshake.js:65:16
Presence: online  rageshake.js:65:16
sync(): not doing HTTP hit, instead returning stored /sync data  rageshake.js:65:16
EventTimelineSet.addLiveEvent: ignoring duplicate event $1499634537355pqjyk:my.private-matrix-server.com  event-timeline-set.js:493:12
EventTimelineSet.addLiveEvent: ignoring duplicate event $1500016395123nPluA:my.private-matrix-server.com  event-timeline-set.js:493:12
EventTimelineSet.addLiveEvent: ignoring duplicate event $1500358479254SeGEy:my.private-matrix-server.com  event-timeline-set.js:493:12
EventTimelineSet.addLiveEvent: ignoring duplicate event $150283543892ymdZx:my.private-matrix-server.com  event-timeline-set.js:493:12
EventTimelineSet.addLiveEvent: ignoring duplicate event $1502989419196UzQKF:my.private-matrix-server.com  event-timeline-set.js:493:12
MatrixClient sync state => PREPARED  rageshake.js:65:16
newscreen room/!ualEsMujkGtoanhaWE:my.private-matrix-server.com  rageshake.js:65:16
RVS update: !ualEsMujkGtoanhaWE:my.private-matrix-server.com undefined loading? false joining? false initial? true waiting? undefined shouldPeek? true  rageshake.js:65:16
updateTint from RoomView._gatherTimelinePanelRef  rageshake.js:65:16
Tinter.tint from updateTint  rageshake.js:65:16
"Failed to get preview for https://docs.google.com/document/d/1lWOh2U85ZQ9mJq0QMwj6WDVvbDDj-AaImfD-FRnD0UE/edit Error: CORS request rejected: https://my.private-matrix-server.com:443/_matrix/media/r0/preview_url?url=https%3A%2F%2Fdocs.google.com%2Fdocument%2Fd%2F1lWOh2U85ZQ9mJq0QMwj6WDVvbDDj-AaImfD-FRnD0UE%2Fedit&ts=1503763561668&access_token=MDAyM2xvY2F0aW9uIG1hdHJpeC5pbmR1c3RyYS5zcGFjZQowMDEzaWRlbnRpZmllciBrZXkKMDAxMGNpZCBnZW4gPSAxCjAwMmZjaWQgdXNlcl9pZCA9IEBwYXZlbDptYXRyaXguaW5kdXN0cmEuc3BhY2UKMDAxNmNpZCB0eXBlID0gYWNjZXNzCjAwMjFjaWQgbm9uY2UgPSAxbnV4fi5UTmFtN19JRFh1CjAwMmZzaWduYXR1cmUgVFE2qsp3sqDzegHAAmrVd9qoCrjjFlJ2xAooFisHqQcK"  rageshake.js:65:16
"Failed to get preview for http://goldprice.org/gold-price-chart.html Error: CORS request rejected: https://my.private-matrix-server.com:443/_matrix/media/r0/preview_url?url=http%3A%2F%2Fgoldprice.org%2Fgold-price-chart.html&ts=1502528235661&access_token=MDAyM2xvY2F0aW9uIG1hdHJpeC5pbmR1c3RyYS5zcGFjZQowMDEzaWRlbnRpZmllciBrZXkKMDAxMGNpZCBnZW4gPSAxCjAwMmZjaWQgdXNlcl9pZCA9IEBwYXZlbDptYXRyaXguaW5kdXN0cmEuc3BhY2UKMDAxNmNpZCB0eXBlID0gYWNjZXNzCjAwMjFjaWQgbm9uY2UgPSAxbnV4fi5UTmFtN19JRFh1CjAwMmZzaWduYXR1cmUgVFE2qsp3sqDzegHAAmrVd9qoCrjjFlJ2xAooFisHqQcK"  rageshake.js:65:16
MatrixClient sync state => SYNCING  rageshake.js:65:16
Persisting sync data up to  s15897_616495_270_20178_4378_73_546_952  indexeddb-worker.js:4:27406
Checking if content is embeddable  Widget.js:59:8
Content is embeddable Object { props: Object, context: Object, refs: Object, updater: Object, state: Object, iframeLoaded: value(), iframeError: value(), isEmbeddable: value(), setSize: value(), _reactInternalInstance: Object }  Widget.js:117:12
uncaught exception: CustomError: Error in protected function: The number of pixels per point in the user's screen is not set  (unknown)
Persisting sync data up to  s15897_616500_270_20178_4378_73_546_952
```
So I'd assume its either the CORS or the uncaught exception at which the console output stopped or these two are related.

### Steps to reproduce

Use latest firefox with Google docs.

Log: not sent    

### Version information

- **Platform**: web (in-browser)

For the web app:

- **Browser**: Firefox (current), up to 56.0~b6+build1-0ubuntu0.17.04.1
- **OS**: Ubuntu 
- **URL**: Private server, riot ver. 0.12.2

**Comment by lampholder** [comment]
I was able to reproduce this.

**Comment by pafcu** [comment]
Still a problem on Firefox 57

**Comment by kittykat** [comment]
Can anyone still reproduce this with the latest version of Firefox?
