### ISSUE TITLE
Cannot edit google docs widget

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#4917]
### Description

![image](https://user-images.githubusercontent.com/1190097/29759305-b11d70d4-8b77-11e7-9eca-82d7477a6021.png)

Ignore the line through the picture - that's a graphics driver problem. 

The page never loads and the spinner (`https://scalar-staging.riot.im/img/spinner.gif`) 404's. Possibly because the `screen` parameter is `type_googledocs` instead of `type_googledoc` (the others appear to be consistent with the spec values, except google docs).

### Steps to reproduce

- Add a Google Docs widget
- Click the edit button

~~Log: sent (links to this issue)~~  Unable to send bug report. Here's the console error:
```
VM5228 scalar.bundle.js:66 Unhandled rejection TypeError: this._getDoctype is not a function
    at new t (https://scalar-staging.riot.im/scalar-web/scalar.bundle.js:63:12561)
    at d._constructComponentWithoutOwner (https://scalar-staging.riot.im/scalar-web/scalar.bundle.js:69:21777)
    at d._constructComponent (https://scalar-staging.riot.im/scalar-web/scalar.bundle.js:69:21644)
    at d.mountComponent (https://scalar-staging.riot.im/scalar-web/scalar.bundle.js:69:20809)
    at Object.mountComponent (https://scalar-staging.riot.im/scalar-web/scalar.bundle.js:6:29797)
    at Object.updateChildren (https://scalar-staging.riot.im/scalar-web/scalar.bundle.js:69:19091)
    at m._reconcilerUpdateChildren (https://scalar-staging.riot.im/scalar-web/scalar.bundle.js:70:20360)
    at m._updateChildren (https://scalar-staging.riot.im/scalar-web/scalar.bundle.js:70:21125)
    at m.updateChildren (https://scalar-staging.riot.im/scalar-web/scalar.bundle.js:70:21023)
    at m._updateDOMChildren (https://scalar-staging.riot.im/scalar-web/scalar.bundle.js:70:5504)
    at m.updateComponent (https://scalar-staging.riot.im/scalar-web/scalar.bundle.js:70:3728)
    at m.receiveComponent (https://scalar-staging.riot.im/scalar-web/scalar.bundle.js:70:3281)
    at Object.receiveComponent (https://scalar-staging.riot.im/scalar-web/scalar.bundle.js:6:30191)
    at d._updateRenderedComponent (https://scalar-staging.riot.im/scalar-web/scalar.bundle.js:69:25964)
    at d._performComponentUpdate (https://scalar-staging.riot.im/scalar-web/scalar.bundle.js:69:25721)
    at d.updateComponent (https://scalar-staging.riot.im/scalar-web/scalar.bundle.js:69:24999)
```

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 60
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by lampholder** [comment]
Is this still a problem?

I don't know much about the scalar config, but for the spinner to be 404ing looks very odd.

**Comment by turt2live** [comment]
@lampholder the spinner no longer 404s, but I'm stuck here:
![image](https://user-images.githubusercontent.com/1190097/30068073-d2136426-9219-11e7-96d2-03a1b3d7f409.png)

**Comment by turt2live** [comment]
This was fixed
