### ISSUE TITLE
Build failure with 0.12.5

### ISSUE THREAD

**Issue by silkeh** [vector-im/riot-web#5098]
Build for Solus fails, with the following steps (from the extracted source 0.12.5 tarball):

```
npm install --cache ../npm-cache
npm run build --cache ../npm-cache
```

The latter fails because the `ReEmitter` files (in `node_modules/matrix-js-sdk/lib/`) are named `Reemitter` and `Reemiter` instead.

```
> riot-web@0.12.5 build /tmp/riot-web-0.12.5
> npm run reskindex && npm run build:res && npm run build:bundle


> riot-web@0.12.5 reskindex /tmp/riot-web-0.12.5
> reskindex -h src/header

Reskindex: completed

> riot-web@0.12.5 build:res /tmp/riot-web-0.12.5
> node scripts/copy-res.js


> riot-web@0.12.5 build:bundle /tmp/riot-web-0.12.5
> cross-env NODE_ENV=production webpack -p --progress --bail

 64% 952/1055 build modulesError
    at /tmp/riot-web-0.12.5/node_modules/webpack/lib/Compilation.js:229:38
    at onDoneResolving (/tmp/riot-web-0.12.5/node_modules/webpack/lib/NormalModuleFactory.js:29:20)
    at /tmp/riot-web-0.12.5/node_modules/webpack/lib/NormalModuleFactory.js:85:20
    at /tmp/riot-web-0.12.5/node_modules/async/lib/async.js:726:13
    at /tmp/riot-web-0.12.5/node_modules/async/lib/async.js:52:16
    at done (/tmp/riot-web-0.12.5/node_modules/async/lib/async.js:241:17)
    at /tmp/riot-web-0.12.5/node_modules/async/lib/async.js:44:16
    at /tmp/riot-web-0.12.5/node_modules/async/lib/async.js:723:17
    at /tmp/riot-web-0.12.5/node_modules/async/lib/async.js:167:37
    at /tmp/riot-web-0.12.5/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:24:19
    at onResolved (/tmp/riot-web-0.12.5/node_modules/enhanced-resolve/lib/Resolver.js:38:18)
    at /tmp/riot-web-0.12.5/node_modules/enhanced-resolve/lib/Resolver.js:127:10
    at /tmp/riot-web-0.12.5/node_modules/enhanced-resolve/lib/Resolver.js:191:15
    at applyPluginsParallelBailResult.createInnerCallback.log (/tmp/riot-web-0.12.5/node_modules/enhanced-resolve/lib/Resolver.js:110:4)
    at loggingCallbackWrapper (/tmp/riot-web-0.12.5/node_modules/enhanced-resolve/lib/createInnerCallback.js:21:19)
    at /tmp/riot-web-0.12.5/node_modules/tapable/lib/Tapable.js:134:6
    at Resolver.<anonymous> (/tmp/riot-web-0.12.5/node_modules/enhanced-resolve/lib/DirectoryDescriptionFilePlugin.js:24:12)
    at Storage.finished (/tmp/riot-web-0.12.5/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:38:16)
    at ReadFileContext.callback (/tmp/riot-web-0.12.5/node_modules/graceful-fs/graceful-fs.js:78:16)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:420:13)
resolve file
  /tmp/riot-web-0.12.5/node_modules/matrix-js-sdk/lib/ReEmitter doesn't exist
  /tmp/riot-web-0.12.5/node_modules/matrix-js-sdk/lib/ReEmitter.web.js doesn't exist
  /tmp/riot-web-0.12.5/node_modules/matrix-js-sdk/lib/ReEmitter.webpack.js doesn't exist
  /tmp/riot-web-0.12.5/node_modules/matrix-js-sdk/lib/ReEmitter.js doesn't exist
  /tmp/riot-web-0.12.5/node_modules/matrix-js-sdk/lib/ReEmitter.json doesn't exist
resolve directory
  /tmp/riot-web-0.12.5/node_modules/matrix-js-sdk/lib/ReEmitter doesn't exist (directory default file)
  /tmp/riot-web-0.12.5/node_modules/matrix-js-sdk/lib/ReEmitter/package.json doesn't exist (directory description file)
 70% 1757/1757 build modulesnpm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! riot-web@0.12.5 build:bundle: `cross-env NODE_ENV=production webpack -p --progress --bail`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the riot-web@0.12.5 build:bundle script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /tmp/npm-cache/_logs/2017-09-21T17_42_33_543Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! riot-web@0.12.5 build: `npm run reskindex && npm run build:res && npm run build:bundle`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the riot-web@0.12.5 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /tmp/npm-cache/_logs/2017-09-21T17_42_33_550Z-debug.log
```

**Comment by Stebalien** [comment]
Something is wrong with the sdk build. You can work around it by running the following before building:

```sh
cd node_modules/matrix-js-sdk
npm install
npm run build
```

**Comment by dbkr** [comment]
Argh, this is the same case sensitivity bug but in js-sdk. Sorry :(

**Comment by dbkr** [comment]
v0.12.6 should fix this
