### ISSUE TITLE
Error: sh: 1: reskindex: not found

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/riot-web#5403]
### Description

Hey there! I'm trying to build Riot following the 'Setting up a dev environment' instructions, however I am getting stuck with the following error when running `npm start` in the riot-web directory:

```
root@ubuntu:~/riot-dev/riot-web# npm start                                                                                                                                         

> riot-web@0.12.7 start /root/riot-dev/riot-web
> parallelshell "npm run reskindex:watch" "npm run start:res" "npm run start:js"


> riot-web@0.12.7 reskindex:watch /root/riot-dev/riot-web
> reskindex -h src/header -w

sh: 1: reskindex: not found
[..................] / : info using node@v6.11.1
> riot-web@0.12.7 start:res /root/riot-dev/riot-web
> node scripts/copy-res.js -w



> riot-web@0.12.7 start:js /root/riot-dev/riot-web
> webpack-dev-server --output-filename=bundles/_dev_/[name].js --output-chunk-file=bundles/_dev_/[name].js -w --progress

npm ERR! Linux 4.9.36-x86_64-linode85
npm ERR! argv "/root/.nvm/versions/node/v6.11.1/bin/node" "/root/.nvm/versions/node/v6.11.1/bin/npm" "run" "reskindex:watch"
npm ERR! node v6.11.1
npm ERR! npm  v3.10.10
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! riot-web@0.12.7 reskindex:watch: `reskindex -h src/header -w`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the riot-web@0.12.7 reskindex:watch script 'reskindex -h src/header -w'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the riot-web package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     reskindex -h src/header -w
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs riot-web
npm ERR! Or if that isn't available, you can get their info via:                                                                                                          [44/1923]
npm ERR!     npm owner ls riot-web
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/riot-dev/riot-web/npm-debug.log

npm ERR! Linux 4.9.36-x86_64-linode85
npm ERR! argv "/root/.nvm/versions/node/v6.11.1/bin/node" "/root/.nvm/versions/node/v6.11.1/bin/npm" "start"
npm ERR! node v6.11.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! riot-web@0.12.7 start: `parallelshell "npm run reskindex:watch" "npm run start:res" "npm run start:js"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the riot-web@0.12.7 start script 'parallelshell "npm run reskindex:watch" "npm run start:res" "npm run start:js"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the riot-web package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     parallelshell "npm run reskindex:watch" "npm run start:res" "npm run start:js"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs riot-web
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls riot-web
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/riot-dev/riot-web/npm-debug.log
root@ubuntu:~/riot-de  0% compile/root/riot-dev/riot-web/node_modules/olm/olm.js:19
"undefined"!==typeof module&&(module.exports=a);process.on("uncaughtException",function(a){if(!(a instanceof T))throw a;});a.inspect=function(){return"[Emscripten Module object]"}
}else if(ma)a.print||(a.print=print),"undefined"!=typeof printErr&&(a.printErr=printErr),a.read="undefined"!=typeof read?read:function(){throw"no read() available (jsc?)";},a.read
Binary=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");z("object"===typeof a);return a},"undefined"!=
                                                                                                                ^

Error: listen EADDRINUSE 127.0.0.1:8080
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at Server._listen2 (net.js:1258:14)
    at listen (net.js:1294:10)
    at net.js:1404:9
    at GetAddrInfoReqWrap.asyncCallback [as callback] (dns.js:62:16)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:81:10)

npm ERR! Linux 4.9.36-x86_64-linode85
npm ERR! argv "/root/.nvm/versions/node/v6.11.1/bin/node" "/root/.nvm/versions/node/v6.11.1/bin/npm" "run" "start:js"
npm ERR! node v6.11.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! riot-web@0.12.7 start:res: `node scripts/copy-res.js -w`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the riot-web@0.12.7 start:res script 'node scripts/copy-res.js -w'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the riot-web package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/copy-res.js -w
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs riot-web
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls riot-web
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/riot-dev/riot-web/npm-debug.log
^C
```

And here is the corresponding [npm-debug.log](https://github.com/vector-im/riot-web/files/1408968/npm-debug.log).

### Version information

Just did a git pull on everything beforehand. 

Riot-web: 8672939f0c2482991812cd63ce72056e7c635935

Matrix-react-sdk: 65ce71e6afc84668f877dc52557ddd5081318adf

Matrix-js-sdk: 7a90096077f41398ddca4a6483b7a1b839964f23

**Comment by uhoreg** [comment]
You likely didn't follow the instructions as written.  reskindex is part of matrix-react-sdk, and it should be linked in node_modules/.bin.  But IIRC this does not happen if you have matrix-react-sdk available before you do an "npm install" in the riot-web directory.

**Comment by anoadragon453** [comment]
Alright, it was due to not including the initial `../` in the `ln -s` steps. I thought the instructions were incorrect since I couldn't autocomplete `../../matrix-react-sdk` but that was due to the link being inside `node_modules`, not the folder I was currently in which was one level above, hence why `../matrix-react-sdk` auto-completed instead.

Also had an issue with the `npm install` step getting killed due to running out of RAM. Can't wait til Dendrite :)
