### ISSUE TITLE
Peeking in rooms with groups as a guest causes errors

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#5628]
### Description

They seem non-fatal, but here it is:
```
Unhandled rejection TypeError: Cannot read property 'userId' of undefined
    at https://riot.im/develop/bundles/92ea5cbc479ab1edba70/bundle.js:46730:78
    at tryCatcher (https://riot.im/develop/bundles/92ea5cbc479ab1edba70/bundle.js:10004:24)
    at Promise._settlePromiseFromHandler (https://riot.im/develop/bundles/92ea5cbc479ab1edba70/bundle.js:150294:32)
    at Promise._settlePromise (https://riot.im/develop/bundles/92ea5cbc479ab1edba70/bundle.js:150351:19)
    at Promise._settlePromise0 (https://riot.im/develop/bundles/92ea5cbc479ab1edba70/bundle.js:150396:11)
    at Promise._settlePromises (https://riot.im/develop/bundles/92ea5cbc479ab1edba70/bundle.js:150471:19)
    at Async._drainQueue (https://riot.im/develop/bundles/92ea5cbc479ab1edba70/bundle.js:147449:17)
    at Async._drainQueues (https://riot.im/develop/bundles/92ea5cbc479ab1edba70/bundle.js:147459:11)
    at Async.drainQueues (https://riot.im/develop/bundles/92ea5cbc479ab1edba70/bundle.js:147333:15)
    at <anonymous>
```

Which is `console.error('Could not get groups for user', _this2.props.userId, err);`

### Steps to reproduce

- Go to riot.im/develop/#/login
- Click "log in as guest"
- On the homepage, pick a room with your console open
- Note the errors

Instead of trying to get groups, it should probably just assume the guest isn't in any.

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 62
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by turt2live** [comment]
It looks like this got fixed (no more angry errors trying to view HQ)
