### ISSUE TITLE
TypeError: loaderUtils.getOptions is not a function

### ISSUE THREAD

**Issue by eqyiel** [vector-im/riot-web#5749]
### Description

Trying to contribute to the riot-web package for nix.  Previously the package just used the prebuild version, but now it's built from source.  Webpack is throwing an error when I try to build riot-web from source.

Here's the repo I'm working from: https://github.com/eqyiel/riot-electron-nix/tree/upstream

It has riot-web pinned to 0.13.1, but the error remains with 0.13.2.

### Steps to reproduce

`npm install -d && npm run build`

This is called by 
`nix-build --expr 'with import <nixpkgs> {}; callPackage ./default.nix {}' --keep-failed` which results in this:

``` 
 10% 0/5 build modulesModuleBuildError: Module build failed: ModuleBuildError: Module build failed: TypeError: loaderUtils.getOptions is not a function
    at Object.module.exports (/nix/store/s1w9gbibvli76i2k65h7qiz1ga2rzii4-node-riot-web-0.13.1/lib/node_modules/riot-web/node_modules/postcss-loader/index.js:46:30)
    at DependenciesBlock.onModuleBuildFailed (/nix/store/s1w9gbibvli76i2k65h7qiz1ga2rzii4-node-riot-web-0.13.1/lib/node_modules/riot-web/node_modules/webpack-core/lib/NormalModuleMixin.js:315:19)
    at nextLoader (/nix/store/s1w9gbibvli76i2k65h7qiz1ga2rzii4-node-riot-web-0.13.1/lib/node_modules/riot-web/node_modules/webpack-core/lib/NormalModuleMixin.js:270:31)
    at /nix/store/s1w9gbibvli76i2k65h7qiz1ga2rzii4-node-riot-web-0.13.1/lib/node_modules/riot-web/node_modules/webpack-core/lib/NormalModuleMixin.js:292:15
    at runSyncOrAsync (/nix/store/s1w9gbibvli76i2k65h7qiz1ga2rzii4-node-riot-web-0.13.1/lib/node_modules/riot-web/node_modules/webpack-core/lib/NormalModuleMixin.js:173:4)
    at nextLoader (/nix/store/s1w9gbibvli76i2k65h7qiz1ga2rzii4-node-riot-web-0.13.1/lib/node_modules/riot-web/node_modules/webpack-core/lib/NormalModuleMixin.js:290:3)
    at /nix/store/s1w9gbibvli76i2k65h7qiz1ga2rzii4-node-riot-web-0.13.1/lib/node_modules/riot-web/node_modules/webpack-core/lib/NormalModuleMixin.js:259:5
    at Storage.finished (/nix/store/s1w9gbibvli76i2k65h7qiz1ga2rzii4-node-riot-web-0.13.1/lib/node_modules/riot-web/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:38:16)
    at /nix/store/s1w9gbibvli76i2k65h7qiz1ga2rzii4-node-riot-web-0.13.1/lib/node_modules/riot-web/node_modules/graceful-fs/graceful-fs.js:78:16                     
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:447:3)
    at DependenciesBlock.onModuleBuildFailed (/nix/store/s1w9gbibvli76i2k65h7qiz1ga2rzii4-node-riot-web-0.13.1/lib/node_modules/riot-web/node_modules/webpack-core/lib/NormalModuleMixin.js:315:19)
    at DependenciesBlock.<anonymous> (/nix/store/s1w9gbibvli76i2k65h7qiz1ga2rzii4-node-riot-web-0.13.1/lib/node_modules/riot-web/node_modules/webpack-core/lib/NormalModuleMixin.js:228:39)
    at context.callback (/nix/store/s1w9gbibvli76i2k65h7qiz1ga2rzii4-node-riot-web-0.13.1/lib/node_modules/riot-web/node_modules/webpack-core/lib/NormalModuleMixin.js:148:14)
    at Object.<anonymous> (/nix/store/s1w9gbibvli76i2k65h7qiz1ga2rzii4-node-riot-web-0.13.1/lib/node_modules/riot-web/node_modules/extract-text-webpack-plugin/loader.js:82:20)
    at Compiler.<anonymous> (/nix/store/s1w9gbibvli76i2k65h7qiz1ga2rzii4-node-riot-web-0.13.1/lib/node_modules/riot-web/node_modules/webpack/lib/Compiler.js:204:18)
    at Compiler.<anonymous> (/nix/store/s1w9gbibvli76i2k65h7qiz1ga2rzii4-node-riot-web-0.13.1/lib/node_modules/riot-web/node_modules/webpack/lib/Compiler.js:395:18)
    at /nix/store/s1w9gbibvli76i2k65h7qiz1ga2rzii4-node-riot-web-0.13.1/lib/node_modules/riot-web/node_modules/tapable/lib/Tapable.js:99:11
    at Compilation.<anonymous> (/nix/store/s1w9gbibvli76i2k65h7qiz1ga2rzii4-node-riot-web-0.13.1/lib/node_modules/riot-web/node_modules/webpack/lib/Compilation.js:433:11)
    at errorAndCallback (/nix/store/s1w9gbibvli76i2k65h7qiz1ga2rzii4-node-riot-web-0.13.1/lib/node_modules/riot-web/node_modules/webpack/lib/Compilation.js:340:3)
    at Compilation.<anonymous> (/nix/store/s1w9gbibvli76i2k65h7qiz1ga2rzii4-node-riot-web-0.13.1/lib/node_modules/riot-web/node_modules/webpack/lib/Compilation.js:400:12)
    at /nix/store/s1w9gbibvli76i2k65h7qiz1ga2rzii4-node-riot-web-0.13.1/lib/node_modules/riot-web/node_modules/webpack/lib/Compilation.js:123:4
    at Array.forEach (native)                                                  
    at callback (/nix/store/s1w9gbibvli76i2k65h7qiz1ga2rzii4-node-riot-web-0.13.1/lib/node_modules/riot-web/node_modules/webpack/lib/Compilation.js:122:12)
    at Compilation.<anonymous> (/nix/store/s1w9gbibvli76i2k65h7qiz1ga2rzii4-node-riot-web-0.13.1/lib/node_modules/riot-web/node_modules/webpack/lib/Compilation.js:137:11)
    at DependenciesBlock.<anonymous> (/nix/store/s1w9gbibvli76i2k65h7qiz1ga2rzii4-node-riot-web-0.13.1/lib/node_modules/riot-web/node_modules/webpack/lib/NormalModule.js:85:18)
    at DependenciesBlock.onModuleBuildFailed (/nix/store/s1w9gbibvli76i2k65h7qiz1ga2rzii4-node-riot-web-0.13.1/lib/node_modules/riot-web/node_modules/webpack-core/lib/NormalModuleMixin.js:315:10)
    at nextLoader (/nix/store/s1w9gbibvli76i2k65h7qiz1ga2rzii4-node-riot-web-0.13.1/lib/node_modules/riot-web/node_modules/webpack-core/lib/NormalModuleMixin.js:270:31)
    at /nix/store/s1w9gbibvli76i2k65h7qiz1ga2rzii4-node-riot-web-0.13.1/lib/node_modules/riot-web/node_modules/webpack-core/lib/NormalModuleMixin.js:292:15
    at runSyncOrAsync (/nix/store/s1w9gbibvli76i2k65h7qiz1ga2rzii4-node-riot-web-0.13.1/lib/node_modules/riot-web/node_modules/webpack-core/lib/NormalModuleMixin.js:173:4)
    at nextLoader (/nix/store/s1w9gbibvli76i2k65h7qiz1ga2rzii4-node-riot-web-0.13.1/lib/node_modules/riot-web/node_modules/webpack-core/lib/NormalModuleMixin.js:290:3)
    at /nix/store/s1w9gbibvli76i2k65h7qiz1ga2rzii4-node-riot-web-0.13.1/lib/node_modules/riot-web/node_modules/webpack-core/lib/NormalModuleMixin.js:259:5
    at Storage.finished (/nix/store/s1w9gbibvli76i2k65h7qiz1ga2rzii4-node-riot-web-0.13.1/lib/node_modules/riot-web/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:38:16)
    at /nix/store/s1w9gbibvli76i2k65h7qiz1ga2rzii4-node-riot-web-0.13.1/lib/node_modules/riot-web/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:447:3)
```

Possibly related: https://github.com/angular/angular-cli/issues/6994

### Version information

- **Platform**: desktop

For the desktop app:

- **OS**: NixOS

**Comment by eqyiel** [comment]
Apologies, it looks like this is a problem with node2nix: https://github.com/svanderburg/node2nix/issues/67

I don't expect this to get fixed though given that webpack 1x is EOL: https://github.com/webpack/webpack/releases/tag/v1.15.0

I'm going to close this, but I would like to know if the maintainers here would be open to receiving PRs to update the outdated dependencies in package.json?

**Comment by t3chguy** [comment]
An update that big to webpack is not merely changing the version in package json, but there are already prs for this iirc

**Comment by eqyiel** [comment]
@t3chguy thanks for telling me about the other PR, I found this: https://github.com/vector-im/riot-web/pull/4800

**Comment by sureshkolla** [comment]
do "npm install loader-utils@latest" try, because this issue will come any updates happen in NPM
