### ISSUE TITLE
Hundreds of console errors on /develop

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#5837]
### Description

```
rageshake.js:65 Caught /sync error TypeError: Cannot read property '_currentElement' of null
    at ReactCompositeComponentWrapper._updateRenderedComponent (https://riot.im/develop/bundles/bd1f6c6476181aa970b9/bundle.js:277129:54)
    at ReactCompositeComponentWrapper._performComponentUpdate (https://riot.im/develop/bundles/bd1f6c6476181aa970b9/bundle.js:277108:11)
    at ReactCompositeComponentWrapper.updateComponent (https://riot.im/develop/bundles/bd1f6c6476181aa970b9/bundle.js:277029:13)
    at ReactCompositeComponentWrapper.performUpdateIfNecessary (https://riot.im/develop/bundles/bd1f6c6476181aa970b9/bundle.js:276945:13)
    at Object.performUpdateIfNecessary (https://riot.im/develop/bundles/bd1f6c6476181aa970b9/bundle.js:26398:23)
    at runBatchedUpdates (https://riot.im/develop/bundles/bd1f6c6476181aa970b9/bundle.js:15494:22)
    at ReactReconcileTransaction.perform (https://riot.im/develop/bundles/bd1f6c6476181aa970b9/bundle.js:46887:21)
    at ReactUpdatesFlushTransaction.perform (https://riot.im/develop/bundles/bd1f6c6476181aa970b9/bundle.js:46887:21)
    at ReactUpdatesFlushTransaction.perform (https://riot.im/develop/bundles/bd1f6c6476181aa970b9/bundle.js:15433:33)
    at Object.flushBatchedUpdates (https://riot.im/develop/bundles/bd1f6c6476181aa970b9/bundle.js:15516:20)
    at ReactDefaultBatchingStrategyTransaction.closeAll (https://riot.im/develop/bundles/bd1f6c6476181aa970b9/bundle.js:46953:26)
    at ReactDefaultBatchingStrategyTransaction.perform (https://riot.im/develop/bundles/bd1f6c6476181aa970b9/bundle.js:46900:17)
    at Object.batchedUpdates (https://riot.im/develop/bundles/bd1f6c6476181aa970b9/bundle.js:279863:27)
    at Object.enqueueUpdate (https://riot.im/develop/bundles/bd1f6c6476181aa970b9/bundle.js:15544:23)
    at enqueueUpdate (https://riot.im/develop/bundles/bd1f6c6476181aa970b9/bundle.js:71005:17)
    at Object.enqueueForceUpdate (https://riot.im/develop/bundles/bd1f6c6476181aa970b9/bundle.js:71137:6)
    at Object.ReactComponent.forceUpdate (https://riot.im/develop/bundles/bd1f6c6476181aa970b9/bundle.js:116908:17)
    at Object.onRoomTimeline (https://riot.im/develop/bundles/bd1f6c6476181aa970b9/bundle.js:152048:15)
    at MatrixClient.EventEmitter.emit (https://riot.im/develop/bundles/bd1f6c6476181aa970b9/bundle.js:14016:21)
    at Reemitter._handleEvent (https://riot.im/develop/bundles/bd1f6c6476181aa970b9/bundle.js:97942:43)
    at Room.EventEmitter.emit (https://riot.im/develop/bundles/bd1f6c6476181aa970b9/bundle.js:14009:18)
    at Reemitter._handleEvent (https://riot.im/develop/bundles/bd1f6c6476181aa970b9/bundle.js:97942:43)
    at EventTimelineSet.EventEmitter.emit (https://riot.im/develop/bundles/bd1f6c6476181aa970b9/bundle.js:14009:18)
    at EventTimelineSet.addEventToTimeline (https://riot.im/develop/bundles/bd1f6c6476181aa970b9/bundle.js:102357:11)
    at EventTimelineSet.addLiveEvent (https://riot.im/develop/bundles/bd1f6c6476181aa970b9/bundle.js:102333:11)
    at Room._addLiveEvent (https://riot.im/develop/bundles/bd1f6c6476181aa970b9/bundle.js:103406:32)
    at Room.addLiveEvents (https://riot.im/develop/bundles/bd1f6c6476181aa970b9/bundle.js:103645:23)
    at SyncApi._processRoomEvents (https://riot.im/develop/bundles/bd1f6c6476181aa970b9/bundle.js:238371:11)
```

I have no idea what event it's choking on, but it's producing a lot of red. It's accompanied by:
```
bundle.js:56722 Warning: performUpdateIfNecessary: Unexpected batch number (current 92499, pending 92412)
consoleObj.(anonymous function) @ bundle.js:56722
bundle.js:56722 Warning: performUpdateIfNecessary: Unexpected batch number (current 92500, pending 92412)
consoleObj.(anonymous function) @ bundle.js:56722
bundle.js:56722 Warning: performUpdateIfNecessary: Unexpected batch number (current 92501, pending 92412)
consoleObj.(anonymous function) @ bundle.js:56722
bundle.js:56722 Warning: performUpdateIfNecessary: Unexpected batch number (current 92502, pending 92412)
consoleObj.(anonymous function) @ bundle.js:56722
bundle.js:56722 Warning: performUpdateIfNecessary: Unexpected batch number (current 92503, pending 92412)
consoleObj.(anonymous function) @ bundle.js:56722
491 log entires are not shown.
```

Log: sent (referencing this issue)   

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 62
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by turt2live** [comment]
I'm not getting this anymore, so something overnight might have fixed it?
