### ISSUE TITLE
Accepting invites on /develop leads to infinispinner

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#5841]
### Description

```
RVS update: !QPRLVrmbKPvJyNndVr:t2bot.io undefined loading? false joining? true initial? undefined shouldPeek? true
rageshake.js:65 Request to reset timeline in room  !QPRLVrmbKPvJyNndVr:t2bot.io  viewing: !QPRLVrmbKPvJyNndVr:t2bot.io
rageshake.js:65 Caught /sync error TypeError: self._loggedInView.canResetTimelineInRoom is not a function
    at MatrixClient._canResetTimelineCallback (https://riot.im/develop/bundles/c9900bfa773b9f38ad32/bundle.js:129619:40)
    at Object.opts.canResetEntireTimeline (https://riot.im/develop/bundles/c9900bfa773b9f38ad32/bundle.js:103333:23)
    at _callee3$ (https://riot.im/develop/bundles/c9900bfa773b9f38ad32/bundle.js:244512:116)
    at tryCatch (https://riot.im/develop/bundles/c9900bfa773b9f38ad32/bundle.js:246613:41)
    at Generator.invoke [as _invoke] (https://riot.im/develop/bundles/c9900bfa773b9f38ad32/bundle.js:246847:23)
    at Generator.prototype.(anonymous function) [as next] (https://riot.im/develop/bundles/c9900bfa773b9f38ad32/bundle.js:246665:22)
    at Generator.tryCatcher (https://riot.im/develop/bundles/c9900bfa773b9f38ad32/bundle.js:1638:24)
    at PromiseSpawn._promiseFulfilled (https://riot.im/develop/bundles/c9900bfa773b9f38ad32/bundle.js:62286:50)
    at https://riot.im/develop/bundles/c9900bfa773b9f38ad32/bundle.js:62390:16
    at https://riot.im/develop/bundles/c9900bfa773b9f38ad32/bundle.js:244566:47
    at tryCatcher (https://riot.im/develop/bundles/c9900bfa773b9f38ad32/bundle.js:1638:24)
    at Object.gotValue (https://riot.im/develop/bundles/c9900bfa773b9f38ad32/bundle.js:64597:19)
    at Object.gotAccum (https://riot.im/develop/bundles/c9900bfa773b9f38ad32/bundle.js:64586:26)
    at Object.tryCatcher (https://riot.im/develop/bundles/c9900bfa773b9f38ad32/bundle.js:1638:24)
    at Promise._settlePromiseFromHandler (https://riot.im/develop/bundles/c9900bfa773b9f38ad32/bundle.js:63403:32)
    at Promise._settlePromise (https://riot.im/develop/bundles/c9900bfa773b9f38ad32/bundle.js:63460:19)
    at Promise._settlePromise0 (https://riot.im/develop/bundles/c9900bfa773b9f38ad32/bundle.js:63505:11)
    at Promise._settlePromises (https://riot.im/develop/bundles/c9900bfa773b9f38ad32/bundle.js:63584:19)
    at Async._drainQueue (https://riot.im/develop/bundles/c9900bfa773b9f38ad32/bundle.js:60558:17)
    at Async._drainQueues (https://riot.im/develop/bundles/c9900bfa773b9f38ad32/bundle.js:60568:11)
    at Async.drainQueues (https://riot.im/develop/bundles/c9900bfa773b9f38ad32/bundle.js:60442:15)
    at <anonymous>
```
### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 63
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by ara4n** [comment]
this is still broken :(

**Comment by ara4n** [comment]
https://github.com/matrix-org/matrix-react-sdk/pull/1665 didn't fix it. i'm hunting a solution.

**Comment by turt2live** [comment]
@ara4n the invites might be a red herring. I'm getting the same error on startup, preventing riot from catching up on syncs since Friday.

```
Caught /sync error TypeError: self._loggedInView.canResetTimelineInRoom is not a function
    at MatrixClient._canResetTimelineCallback (https://riot.im/develop/bundles/ae1315827b1b698fedd7/bundle.js:129619:40)
    at Object.opts.canResetEntireTimeline (https://riot.im/develop/bundles/ae1315827b1b698fedd7/bundle.js:103333:23)
    at _callee3$ (https://riot.im/develop/bundles/ae1315827b1b698fedd7/bundle.js:244544:116)
    at tryCatch (https://riot.im/develop/bundles/ae1315827b1b698fedd7/bundle.js:246645:41)
    at Generator.invoke [as _invoke] (https://riot.im/develop/bundles/ae1315827b1b698fedd7/bundle.js:246879:23)
    at Generator.prototype.(anonymous function) [as next] (https://riot.im/develop/bundles/ae1315827b1b698fedd7/bundle.js:246697:22)
    at Generator.tryCatcher (https://riot.im/develop/bundles/ae1315827b1b698fedd7/bundle.js:1638:24)
    at PromiseSpawn._promiseFulfilled (https://riot.im/develop/bundles/ae1315827b1b698fedd7/bundle.js:62286:50)
    at https://riot.im/develop/bundles/ae1315827b1b698fedd7/bundle.js:62390:16
    at https://riot.im/develop/bundles/ae1315827b1b698fedd7/bundle.js:244598:47
    at tryCatcher (https://riot.im/develop/bundles/ae1315827b1b698fedd7/bundle.js:1638:24)
    at Object.gotValue (https://riot.im/develop/bundles/ae1315827b1b698fedd7/bundle.js:64597:19)
    at Object.gotAccum (https://riot.im/develop/bundles/ae1315827b1b698fedd7/bundle.js:64586:26)
    at Object.tryCatcher (https://riot.im/develop/bundles/ae1315827b1b698fedd7/bundle.js:1638:24)
    at Promise._settlePromiseFromHandler (https://riot.im/develop/bundles/ae1315827b1b698fedd7/bundle.js:63403:32)
    at Promise._settlePromise (https://riot.im/develop/bundles/ae1315827b1b698fedd7/bundle.js:63460:19)
    at Promise._settlePromise0 (https://riot.im/develop/bundles/ae1315827b1b698fedd7/bundle.js:63505:11)
    at Promise._settlePromises (https://riot.im/develop/bundles/ae1315827b1b698fedd7/bundle.js:63584:19)
    at Async._drainQueue (https://riot.im/develop/bundles/ae1315827b1b698fedd7/bundle.js:60558:17)
    at Async._drainQueues (https://riot.im/develop/bundles/ae1315827b1b698fedd7/bundle.js:60568:11)
    at Async.drainQueues (https://riot.im/develop/bundles/ae1315827b1b698fedd7/bundle.js:60442:15)
    at <anonymous>
```

**Comment by ara4n** [comment]
So the problem here is that @lukebarnard1's drag & drop stuff for LLP means that `self._loggedInView` is somehow ending up with a `DragDropContextContainer` in it rather than a LoggedInView (instead the LoggedInView is on the `.child` attribute.  This is pretty clear when you breakpoint it when it's crashing on an invite.

**Comment by ara4n** [comment]
looks like LoggedInView is now always wrapped in a DragDropContextContainer, so the fix here is just to refer to the child component via `getDecoratedComponentInstance()`.
