### ISSUE TITLE
NPE trying to join a room

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#6432]
On develop

```
Attempting to peek into room !lvIcrpsvfNrOLoGQfd:matrix.org
09:42:20.373 matrix.org/_matrix/client/r0/rooms/!lvIcrpsvfNrOLoGQfd%3Amatrix.org/initialSync?limit=20:1 GET https://matrix.org/_matrix/client/r0/rooms/!lvIcrpsvfNrOLoGQfd%3Amatrix.org/initialSync?limit=20 403 ()
09:42:24.166 rageshake.js:65 RVS update: !lvIcrpsvfNrOLoGQfd:matrix.org undefined loading? false joining? true initial? undefined shouldPeek? true
09:42:25.920 rageshake.js:65 Caught /sync error TypeError: Cannot read property 'roomId' of null
    at Object.onRoomStateEvents (https://riot.im/develop/bundles/3b2645ab2d40d7dd05b6/bundle.js:144430:49)
    at MatrixClient.EventEmitter.emit (https://riot.im/develop/bundles/3b2645ab2d40d7dd05b6/bundle.js:14693:21)
    at Reemitter._handleEvent (https://riot.im/develop/bundles/3b2645ab2d40d7dd05b6/bundle.js:104515:43)
    at RoomState.EventEmitter.emit (https://riot.im/develop/bundles/3b2645ab2d40d7dd05b6/bundle.js:14681:18)
    at https://riot.im/develop/bundles/3b2645ab2d40d7dd05b6/bundle.js:62080:15
    at Object.module.exports.forEach (https://riot.im/develop/bundles/3b2645ab2d40d7dd05b6/bundle.js:3384:10)
    at RoomState.setStateEvents (https://riot.im/develop/bundles/3b2645ab2d40d7dd05b6/bundle.js:62064:12)
    at EventTimeline.initialiseState (https://riot.im/develop/bundles/3b2645ab2d40d7dd05b6/bundle.js:22174:21)
    at SyncApi._processRoomEvents (https://riot.im/develop/bundles/3b2645ab2d40d7dd05b6/bundle.js:256510:23)
    at _callee7$ (https://riot.im/develop/bundles/3b2645ab2d40d7dd05b6/bundle.js:256124:55)
    at tryCatch (https://riot.im/develop/bundles/3b2645ab2d40d7dd05b6/bundle.js:258275:41)
    at Generator.invoke [as _invoke] (https://riot.im/develop/bundles/3b2645ab2d40d7dd05b6/bundle.js:258509:23)
    at Generator.prototype.(anonymous function) [as next] (https://riot.im/develop/bundles/3b2645ab2d40d7dd05b6/bundle.js:258327:22)
    at Generator.tryCatcher (https://riot.im/develop/bundles/3b2645ab2d40d7dd05b6/bundle.js:2090:24)
    at PromiseSpawn._promiseFulfilled (https://riot.im/develop/bundles/3b2645ab2d40d7dd05b6/bundle.js:64773:50)
    at https://riot.im/develop/bundles/3b2645ab2d40d7dd05b6/bundle.js:64877:16
    at https://riot.im/develop/bundles/3b2645ab2d40d7dd05b6/bundle.js:256166:47
    at tryCatcher (https://riot.im/develop/bundles/3b2645ab2d40d7dd05b6/bundle.js:2090:24)
    at Object.gotValue (https://riot.im/develop/bundles/3b2645ab2d40d7dd05b6/bundle.js:67084:19)
    at Object.gotAccum (https://riot.im/develop/bundles/3b2645ab2d40d7dd05b6/bundle.js:67073:26)
    at Object.tryCatcher (https://riot.im/develop/bundles/3b2645ab2d40d7dd05b6/bundle.js:2090:24)
    at Promise._settlePromiseFromHandler (https://riot.im/develop/bundles/3b2645ab2d40d7dd05b6/bundle.js:65890:32)
    at Promise._settlePromise (https://riot.im/develop/bundles/3b2645ab2d40d7dd05b6/bundle.js:65947:19)
    at Promise._settlePromise0 (https://riot.im/develop/bundles/3b2645ab2d40d7dd05b6/bundle.js:65992:11)
    at Promise._settlePromises (https://riot.im/develop/bundles/3b2645ab2d40d7dd05b6/bundle.js:66071:19)
    at Async._drainQueue (https://riot.im/develop/bundles/3b2645ab2d40d7dd05b6/bundle.js:63045:17)
    at Async._drainQueues (https://riot.im/develop/bundles/3b2645ab2d40d7dd05b6/bundle.js:63055:11)
    at Async.drainQueues (https://riot.im/develop/bundles/3b2645ab2d40d7dd05b6/bundle.js:62929:15)
```

**Comment by lukebarnard1** [comment]
I couldn't reproduce, but this is most likely a missing null-guard.
