### ISSUE TITLE
Typing "/devtools" results in a draft error

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#6436]
### Description

```
Uncaught DOMException: Failed to execute 'extend' on 'Selection': This Selection object doesn't have any Ranges.
    at addFocusToSelection (https://riot.im/develop/bundles/87fb79895c26248100ed/bundle.js:189960:18)
    at setDraftEditorSelection (https://riot.im/develop/bundles/87fb79895c26248100ed/bundle.js:189896:6)
    at DraftEditorLeaf._setSelection (https://riot.im/develop/bundles/87fb79895c26248100ed/bundle.js:185882:6)
    at DraftEditorLeaf.componentDidMount (https://riot.im/develop/bundles/87fb79895c26248100ed/bundle.js:185896:11)
    at https://riot.im/develop/bundles/87fb79895c26248100ed/bundle.js:315412:26
    at measureLifeCyclePerf (https://riot.im/develop/bundles/87fb79895c26248100ed/bundle.js:315223:13)
    at https://riot.im/develop/bundles/87fb79895c26248100ed/bundle.js:315411:12
    at CallbackQueue.notifyAll (https://riot.im/develop/bundles/87fb79895c26248100ed/bundle.js:122028:23)
    at ReactReconcileTransaction.close (https://riot.im/develop/bundles/87fb79895c26248100ed/bundle.js:320251:27)
    at ReactReconcileTransaction.closeAll (https://riot.im/develop/bundles/87fb79895c26248100ed/bundle.js:50051:26)
    at ReactReconcileTransaction.perform (https://riot.im/develop/bundles/87fb79895c26248100ed/bundle.js:49998:17)
    at ReactUpdatesFlushTransaction.perform (https://riot.im/develop/bundles/87fb79895c26248100ed/bundle.js:49985:21)
    at ReactUpdatesFlushTransaction.perform (https://riot.im/develop/bundles/87fb79895c26248100ed/bundle.js:16522:33)
    at Object.flushBatchedUpdates (https://riot.im/develop/bundles/87fb79895c26248100ed/bundle.js:16605:20)
    at ReactDefaultBatchingStrategyTransaction.closeAll (https://riot.im/develop/bundles/87fb79895c26248100ed/bundle.js:50051:26)
    at ReactDefaultBatchingStrategyTransaction.perform (https://riot.im/develop/bundles/87fb79895c26248100ed/bundle.js:49998:17)
    at Object.batchedUpdates (https://riot.im/develop/bundles/87fb79895c26248100ed/bundle.js:318626:27)
    at Object.batchedUpdates (https://riot.im/develop/bundles/87fb79895c26248100ed/bundle.js:16530:28)
    at dispatchEvent (https://riot.im/develop/bundles/87fb79895c26248100ed/bundle.js:318925:21)
```

### Steps to reproduce

- In the composer, type `/devtools`
- Press enter

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 65
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by turt2live** [comment]
@lampholder yes

```
setDraftEditorSelection.js:186 Uncaught DOMException: Failed to execute 'extend' on 'Selection': This Selection object doesn't have any Ranges.
    at addFocusToSelection (https://riot.im/develop/bundles/f316e5123e80544ce313/bundle.js:190027:18)
    at setDraftEditorSelection (https://riot.im/develop/bundles/f316e5123e80544ce313/bundle.js:189963:6)
    at DraftEditorLeaf._setSelection (https://riot.im/develop/bundles/f316e5123e80544ce313/bundle.js:185949:6)
    at DraftEditorLeaf.componentDidMount (https://riot.im/develop/bundles/f316e5123e80544ce313/bundle.js:185963:11)
    at https://riot.im/develop/bundles/f316e5123e80544ce313/bundle.js:315358:26
    at measureLifeCyclePerf (https://riot.im/develop/bundles/f316e5123e80544ce313/bundle.js:315169:13)
    at https://riot.im/develop/bundles/f316e5123e80544ce313/bundle.js:315357:12
    at CallbackQueue.notifyAll (https://riot.im/develop/bundles/f316e5123e80544ce313/bundle.js:121886:23)
    at ReactReconcileTransaction.close (https://riot.im/develop/bundles/f316e5123e80544ce313/bundle.js:320197:27)
    at ReactReconcileTransaction.closeAll (https://riot.im/develop/bundles/f316e5123e80544ce313/bundle.js:50101:26)
    at ReactReconcileTransaction.perform (https://riot.im/develop/bundles/f316e5123e80544ce313/bundle.js:50048:17)
    at ReactUpdatesFlushTransaction.perform (https://riot.im/develop/bundles/f316e5123e80544ce313/bundle.js:50035:21)
    at ReactUpdatesFlushTransaction.perform (https://riot.im/develop/bundles/f316e5123e80544ce313/bundle.js:16520:33)
    at Object.flushBatchedUpdates (https://riot.im/develop/bundles/f316e5123e80544ce313/bundle.js:16603:20)
    at ReactDefaultBatchingStrategyTransaction.closeAll (https://riot.im/develop/bundles/f316e5123e80544ce313/bundle.js:50101:26)
    at ReactDefaultBatchingStrategyTransaction.perform (https://riot.im/develop/bundles/f316e5123e80544ce313/bundle.js:50048:17)
    at Object.batchedUpdates (https://riot.im/develop/bundles/f316e5123e80544ce313/bundle.js:318572:27)
    at Object.batchedUpdates (https://riot.im/develop/bundles/f316e5123e80544ce313/bundle.js:16528:28)
    at dispatchEvent (https://riot.im/develop/bundles/f316e5123e80544ce313/bundle.js:318871:21)
```

**Comment by turt2live** [comment]
@lampholder were you able to reproduce this?

**Comment by t3chguy** [comment]
might get fixed by M's Slate stuff

**Comment by turt2live** [comment]
Lots of issues might. I think I have 8 RTE issues alone. Was just hoping to get rid of the label because acute ocd.

**Comment by lampholder** [comment]
SORRY - this bug is that it results in an error, not that that error causes any problems (beyond cluttering the console, which _is_ a problem worth fixing). 

So yes, I can totally reproduce this; sorry for sloppy triage.

**Comment by lampholder** [comment]
I'm going to add a new label, console-spam, to identify all of the issues which make our error console virtually unusable.

**Comment by dbkr** [comment]
I also get this every time I open dev tools, which means that if chrome dev tools is open, it breakpoints, which gets tedious very quickly.

**Comment by t3chguy** [comment]
Cannot repro :(

![image](https://user-images.githubusercontent.com/2403652/41343017-776b0ab0-6ef5-11e8-9b9c-ead92a3a13f6.png)

**Comment by turt2live** [comment]
I can reproduce this very easily still :(

**Comment by t3chguy** [comment]
I know it exists, I just wish I could repro it on my machine so I could fix it
I think luk3 is looking at the slate PR so hopefully we can all put this one behind us :)
