### ISSUE TITLE
Native scrollbars appear randomly, making Riot unusable

### ISSUE THREAD

**Issue by 26000** [vector-im/riot-web#6678]
### Description

Sometimes when I click on one of my rooms (IIRC occurs only with one of them), a native scrollbar appears. If there are new messages, they don't get marked as read; when I click on another room, only the tint changes, nothing happens; when I click settings, everything gets tinted except for the room body, and the settings window probably appears behind it. Only room settings work.

Sometimes when there are images in that room, they appear in their original resolution, and a horizontal native scrollbar appears.

Here are the logs:
```
FlairStore: Request group profile of +kotobank:kotobank.ch

async.js:61 Uncaught Error: Minified React error #109; visit http://facebook.github.io/react/docs/error-decoder.html?invariant=109&args[]=t for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at n (reactProdInvariant.js:29)
    at f._renderValidatedComponent (ReactCompositeComponent.js:828)
    at f.performInitialMount (ReactCompositeComponent.js:359)
    at f.mountComponent (ReactCompositeComponent.js:255)
    at Object.mountComponent (ReactReconciler.js:43)
    at f.performInitialMount (ReactCompositeComponent.js:368)
    at f.mountComponent (ReactCompositeComponent.js:255)
    at Object.mountComponent (ReactReconciler.js:43)
    at a (ReactMount.js:102)
    at r.perform (Transaction.js:141)
    at s (ReactMount.js:124)
    at Object.batchedUpdates (ReactDefaultBatchingStrategy.js:58)
    at Object.i [as batchedUpdates] (ReactUpdates.js:95)
    at Object._renderNewRootComponent (ReactMount.js:317)
    at Object._renderSubtreeIntoContainer (ReactMount.js:399)
    at Object.render (ReactMount.js:420)

event-timeline-set.js:411 Event $15257282262152lQmle:kotobank.ch already in timeline !QQofvDUFCUAYKIPUpf:kotobank.ch:2018-05-08T11:38:08.474Z

rageshake.js:66 FlairStore: Emit updateGroupProfile for +kotobank:kotobank.ch

rageshake.js:66 Unhandled rejection TypeError: Cannot read property '_currentElement' of null
    at f._updateRenderedComponent (https://chat.kotobank.ch/bundles/3de1254efca2af5ec784/bundle.js:152:31149)
    at f._performComponentUpdate (https://chat.kotobank.ch/bundles/3de1254efca2af5ec784/bundle.js:152:30973)
    at f.updateComponent (https://chat.kotobank.ch/bundles/3de1254efca2af5ec784/bundle.js:152:30251)
    at f.performUpdateIfNecessary (https://chat.kotobank.ch/bundles/3de1254efca2af5ec784/bundle.js:152:29578)
    at Object.performUpdateIfNecessary (https://chat.kotobank.ch/bundles/3de1254efca2af5ec784/bundle.js:17:9428)
    at s (https://chat.kotobank.ch/bundles/3de1254efca2af5ec784/bundle.js:14:2790)
    at r.perform (https://chat.kotobank.ch/bundles/3de1254efca2af5ec784/bundle.js:36:9379)
    at o.perform (https://chat.kotobank.ch/bundles/3de1254efca2af5ec784/bundle.js:36:9379)
    at o.perform (https://chat.kotobank.ch/bundles/3de1254efca2af5ec784/bundle.js:14:3953)
    at Object.x [as flushBatchedUpdates] (https://chat.kotobank.ch/bundles/3de1254efca2af5ec784/bundle.js:14:4122)
    at r.closeAll (https://chat.kotobank.ch/bundles/3de1254efca2af5ec784/bundle.js:36:9973)
    at r.perform (https://chat.kotobank.ch/bundles/3de1254efca2af5ec784/bundle.js:36:9462)
    at Object.batchedUpdates (https://chat.kotobank.ch/bundles/3de1254efca2af5ec784/bundle.js:153:21418)
    at Object.l [as enqueueUpdate] (https://chat.kotobank.ch/bundles/3de1254efca2af5ec784/bundle.js:14:3072)
    at r (https://chat.kotobank.ch/bundles/3de1254efca2af5ec784/bundle.js:50:8219)
    at Object.enqueueSetState (https://chat.kotobank.ch/bundles/3de1254efca2af5ec784/bundle.js:50:9360)
e.(anonymous function) @ rageshake.js:66
36ReactErrorUtils.js:49 Uncaught Error: ScrollPanel._getScrollNode called before gemini ref collected
    at Object._getScrollNode (ScrollPanel.js:671)
    at Object.onScroll (ScrollPanel.js:183)
    at Object.r (ReactErrorUtils.js:24)
    at a (EventPluginUtils.js:83)
    at Object.s [as executeDispatchesInOrder] (EventPluginUtils.js:106)
    at m (EventPluginHub.js:41)
    at h (EventPluginHub.js:52)
    at Array.forEach (<anonymous>)
    at n (forEachAccumulated.js:22)
    at Object.processEventQueue (EventPluginHub.js:252)
    at r (ReactEventEmitterMixin.js:15)
    at Object.handleTopLevel [as _handleTopLevel] (ReactEventEmitterMixin.js:25)
    at i (ReactEventListener.js:70)
    at r.perform (Transaction.js:141)
    at Object.batchedUpdates (ReactDefaultBatchingStrategy.js:60)
    at Object.i [as batchedUpdates] (ReactUpdates.js:95)
index.js:44 Uncaught TypeError: Cannot read property 'update' of null
    at Object.componentDidUpdate (index.js:44)
    at e.notifyAll (CallbackQueue.js:74)
    at r.close (ReactReconcileTransaction.js:78)
    at r.closeAll (Transaction.js:207)
    at r.perform (Transaction.js:154)
    at o.perform (Transaction.js:141)
    at o.perform (ReactUpdates.js:87)
    at Object.x [as flushBatchedUpdates] (ReactUpdates.js:170)
    at r.closeAll (Transaction.js:207)
    at r.perform (Transaction.js:154)
    at Object.batchedUpdates (ReactDefaultBatchingStrategy.js:60)
    at Object.l [as enqueueUpdate] (ReactUpdates.js:198)
    at r (ReactUpdateQueue.js:22)
    at Object.enqueueSetState (ReactUpdateQueue.js:216)
    at Object.r.setState (ReactBaseClasses.js:62)
    at Object.onAction (MatrixChat.js:616)
rageshake.js:66 updateTint from onCancelClick
rageshake.js:66 Tinter.tint from updateTint
index.js:44 Uncaught TypeError: Cannot read property 'update' of null
    at Object.componentDidUpdate (index.js:44)
    at e.notifyAll (CallbackQueue.js:74)
    at r.close (ReactReconcileTransaction.js:78)
    at r.closeAll (Transaction.js:207)
    at r.perform (Transaction.js:154)
    at o.perform (Transaction.js:141)
    at o.perform (ReactUpdates.js:87)
    at Object.x [as flushBatchedUpdates] (ReactUpdates.js:170)
    at r.closeAll (Transaction.js:207)
    at r.perform (Transaction.js:154)
    at Object.batchedUpdates (ReactDefaultBatchingStrategy.js:60)
    at Object.l [as enqueueUpdate] (ReactUpdates.js:198)
    at r (ReactUpdateQueue.js:22)
    at Object.enqueueSetState (ReactUpdateQueue.js:216)
    at Object.r.setState (ReactBaseClasses.js:62)
    at Object.onAction (MatrixChat.js:616)
ReactErrorUtils.js:49 Uncaught Error: ScrollPanel._getScrollNode called before gemini ref collected
    at Object._getScrollNode (ScrollPanel.js:671)
    at Object.onScroll (ScrollPanel.js:183)
    at Object.r (ReactErrorUtils.js:24)
    at a (EventPluginUtils.js:83)
    at Object.s [as executeDispatchesInOrder] (EventPluginUtils.js:106)
    at m (EventPluginHub.js:41)
    at h (EventPluginHub.js:52)
    at Array.forEach (<anonymous>)
    at n (forEachAccumulated.js:22)
    at Object.processEventQueue (EventPluginHub.js:252)
    at r (ReactEventEmitterMixin.js:15)
    at Object.handleTopLevel [as _handleTopLevel] (ReactEventEmitterMixin.js:25)
    at i (ReactEventListener.js:70)
    at r.perform (Transaction.js:141)
    at Object.batchedUpdates (ReactDefaultBatchingStrategy.js:60)
    at Object.i [as batchedUpdates] (ReactUpdates.js:95)
rageshake.js:66 Switching to room id <room_id>:kotobank.ch at event undefined
index.js:44 Uncaught TypeError: Cannot read property 'update' of null
    at Object.componentDidUpdate (index.js:44)
    at e.notifyAll (CallbackQueue.js:74)
    at r.close (ReactReconcileTransaction.js:78)
    at r.closeAll (Transaction.js:207)
    at r.perform (Transaction.js:154)
    at o.perform (Transaction.js:141)
    at o.perform (ReactUpdates.js:87)
    at Object.x [as flushBatchedUpdates] (ReactUpdates.js:170)
    at r.closeAll (Transaction.js:207)
    at r.perform (Transaction.js:154)
    at Object.batchedUpdates (ReactDefaultBatchingStrategy.js:60)
    at Object.l [as enqueueUpdate] (ReactUpdates.js:198)
    at r (ReactUpdateQueue.js:22)
    at Object.enqueueSetState (ReactUpdateQueue.js:216)
    at Object.r.setState (ReactBaseClasses.js:62)
    at Object.onAction (RightPanel.js:252)
rageshake.js:66 newscreen room/<room_id>:kotobank.ch
rageshake.js:66 MatrixChat.startPageChangeTimer: timer already started
e.(anonymous function) @ rageshake.js:66
rageshake.js:66 RVS update: <room_id>:kotobank.ch undefined loading? false joining? false initial? true shouldPeek? true
rageshake.js:66 updateTint from RoomView._gatherTimelinePanelRef
rageshake.js:66 Tinter.tint from updateTint
async.js:61 Uncaught Error: Minified exception occurred; use the non-minified dev environment for the full error message and additional helpful warnings.
    at r (invariant.js:35)
    at t.e.unregister (Dispatcher.js:139)
    at t.value (MessageComposerInput.js:259)
    at f.unmountComponent (ReactCompositeComponent.js:409)
    at Object.unmountComponent (ReactReconciler.js:76)
    at Object.unmountChildren (ReactChildReconciler.js:144)
    at h.unmountChildren (ReactMultiChild.js:369)
    at h.unmountComponent (ReactDOMComponent.js:992)
    at Object.unmountComponent (ReactReconciler.js:76)
    at Object.unmountChildren (ReactChildReconciler.js:144)
    at h.unmountChildren (ReactMultiChild.js:369)
    at h.unmountComponent (ReactDOMComponent.js:992)
    at Object.unmountComponent (ReactReconciler.js:76)
    at Object.unmountChildren (ReactChildReconciler.js:144)
    at h.unmountChildren (ReactMultiChild.js:369)
    at h.unmountComponent (ReactDOMComponent.js:992)
2XHR finished loading: POST "https://matrix.kotobank.ch/_matrix/client/r0/rooms/<room_id>%3Akotobank.ch/read_markers?".
339XHR finished loading: OPTIONS "<URL>".
341XHR finished loading: GET "<URL>".
indexeddb-local-backend.js?79bc:277 Persisting sync data up to  s121844_956535_5712_27812_12289_77_302_2250_18
6XHR finished loading: OPTIONS "<URL>?".
rageshake.js:66 Presence: unavailable
6XHR finished loading: PUT "<URL>?".
2rageshake.js:66 Caught /sync error TypeError: Cannot read property 'update' of null
    at Object.componentDidUpdate (https://chat.kotobank.ch/bundles/3de1254efca2af5ec784/bundle.js:72:20472)
    at e.notifyAll (https://chat.kotobank.ch/bundles/3de1254efca2af5ec784/bundle.js:73:17388)
    at r.close (https://chat.kotobank.ch/bundles/3de1254efca2af5ec784/bundle.js:153:28362)
    at r.closeAll (https://chat.kotobank.ch/bundles/3de1254efca2af5ec784/bundle.js:36:9973)
    at r.perform (https://chat.kotobank.ch/bundles/3de1254efca2af5ec784/bundle.js:36:9462)
    at o.perform (https://chat.kotobank.ch/bundles/3de1254efca2af5ec784/bundle.js:36:9379)
    at o.perform (https://chat.kotobank.ch/bundles/3de1254efca2af5ec784/bundle.js:14:3953)
    at Object.x [as flushBatchedUpdates] (https://chat.kotobank.ch/bundles/3de1254efca2af5ec784/bundle.js:14:4122)
    at r.closeAll (https://chat.kotobank.ch/bundles/3de1254efca2af5ec784/bundle.js:36:9973)
    at r.perform (https://chat.kotobank.ch/bundles/3de1254efca2af5ec784/bundle.js:36:9462)
    at Object.batchedUpdates (https://chat.kotobank.ch/bundles/3de1254efca2af5ec784/bundle.js:153:21418)
    at Object.l [as enqueueUpdate] (https://chat.kotobank.ch/bundles/3de1254efca2af5ec784/bundle.js:14:3072)
    at r (https://chat.kotobank.ch/bundles/3de1254efca2af5ec784/bundle.js:50:8219)
    at Object.enqueueSetState (https://chat.kotobank.ch/bundles/3de1254efca2af5ec784/bundle.js:50:9360)
    at Object.r.setState (https://chat.kotobank.ch/bundles/3de1254efca2af5ec784/bundle.js:74:7476)
    at Object.e.exports.u.default.createClass._updateList (https://chat.kotobank.ch/bundles/3de1254efca2af5ec784/bundle.js:142:10927)
e.(anonymous function) @ rageshake.js:66
(anonymous) @ sync.js:643
r @ runtime.js:65
(anonymous) @ runtime.js:299
e.(anonymous function) @ runtime.js:117
o @ util.js:16
l._promiseRejected @ generators.js:107
i._settlePromise @ promise.js:576
i._settlePromise0 @ promise.js:614
i._settlePromises @ promise.js:689
r._drainQueue @ async.js:133
r._drainQueues @ async.js:143
drainQueues @ async.js:17
Promise.then (async)
i @ schedule.js:18
r._queueTick @ async.js:152
a @ async.js:88
c.hasDevTools.r.settlePromises @ async.js:120
i._fulfill @ promise.js:640
i._resolveCallback @ promise.js:432
a @ promise.js:710
_onWorkerMessage @ indexeddb-remote-backend.js:148
rageshake.js:66 Presence: online
```

### Steps to reproduce

It appears randomly with that Kotobank room, dunno how to reproduce.
The only specific things for that room are Telematrix and AppService-IRC, the majority of users is from Telegram.

Log: will send after submitting this issue

![image](https://user-images.githubusercontent.com/23152347/39755934-2116622c-52b7-11e8-92d7-603aa00b87b5.png)

### Version information

- **Platform**: web (in-browser)
- **Browser**:  Chromium Version 66.0.3359.139 (Official Build) Arch Linux (64-bit)
- **OS**: Arch Linux
- **URL**: https://chat.kotobank.ch/ (v0.14.2)

_edits:_ removed duplicate logs

**Comment by lukebarnard1** [comment]
The replies feature is under heavy development and will be released properly soon.

The previous implementation (of v14.2) did suffer from bugs like this.

**Comment by 26000** [comment]
Thanks. Are there any due dates for new releases?

**Comment by t3chguy** [comment]
@26000 releases are bi-weekly (every two weeks), so next week I believe

**Comment by 26000** [comment]
@t3chguy thanks!
