### ISSUE TITLE
Unresponsive with /sync error

### ISSUE THREAD

**Issue by Half-Shot** [vector-im/riot-web#7507]
### Description
The app became unresponsive and I had to kill it.

### Steps to reproduce

- Not sure, was just typing and it froze.

This is the only standout logging I could find.
```
2018-10-16T13:58:31.361Z E Caught /sync error Error: live timeline 0 is no longer live - it has a neighbouring timeline
    at b.addLiveEvents (file:///opt/Riot/resources/webapp/bundles/b6d6a8e1f89935e9cbea/bundle.js:53:159018)
    at b._processRoomEvents (file:///opt/Riot/resources/webapp/bundles/b6d6a8e1f89935e9cbea/bundle.js:60:46893)
    at file:///opt/Riot/resources/webapp/bundles/b6d6a8e1f89935e9cbea/bundle.js:60:42422
    at C (file:///opt/Riot/resources/webapp/bundles/b6d6a8e1f89935e9cbea/bundle.js:30:34600)
    at Generator._invoke (file:///opt/Riot/resources/webapp/bundles/b6d6a8e1f89935e9cbea/bundle.js:30:34388)
    at Generator.e.(anonymous function) [as next] (file:///opt/Riot/resources/webapp/bundles/b6d6a8e1f89935e9cbea/bundle.js:30:34779)
    at Generator.c (file:///opt/Riot/resources/webapp/bundles/b6d6a8e1f89935e9cbea/bundle.js:1:140569)
    at m._promiseFulfilled (file:///opt/Riot/resources/webapp/bundles/b6d6a8e1f89935e9cbea/bundle.js:1:97592)
    at file:///opt/Riot/resources/webapp/bundles/b6d6a8e1f89935e9cbea/bundle.js:1:99619
From previous event:
    at R.j [as _captureStackTrace] (file:///opt/Riot/resources/webapp/bundles/b6d6a8e1f89935e9cbea/bundle.js:1:83589)
    at new m (file:///opt/Riot/resources/webapp/bundles/b6d6a8e1f89935e9cbea/bundle.js:1:96463)
    at b.<anonymous> (file:///opt/Riot/resources/webapp/bundles/b6d6a8e1f89935e9cbea/bundle.js:1:99556)
    at b._processSyncResponse (file:///opt/Riot/resources/webapp/bundles/b6d6a8e1f89935e9cbea/bundle.js:60:44015)
    at b.<anonymous> (file:///opt/Riot/resources/webapp/bundles/b6d6a8e1f89935e9cbea/bundle.js:60:36986)
    at C (file:///opt/Riot/resources/webapp/bundles/b6d6a8e1f89935e9cbea/bundle.js:30:34600)
    at Generator._invoke (file:///opt/Riot/resources/webapp/bundles/b6d6a8e1f89935e9cbea/bundle.js:30:34388)
    at Generator.e.(anonymous function) [as next] (file:///opt/Riot/resources/webapp/bundles/b6d6a8e1f89935e9cbea/bundle.js:30:34779)
    at Generator.c (file:///opt/Riot/resources/webapp/bundles/b6d6a8e1f89935e9cbea/bundle.js:1:140569)
    at m._promiseFulfilled (file:///opt/Riot/resources/webapp/bundles/b6d6a8e1f89935e9cbea/bundle.js:1:97592)
    at m (file:///opt/Riot/resources/webapp/bundles/b6d6a8e1f89935e9cbea/bundle.js:1:68843)
    at d (file:///opt/Riot/resources/webapp/bundles/b6d6a8e1f89935e9cbea/bundle.js:1:68729)
    at l._drainQueues (file:///opt/Riot/resources/webapp/bundles/b6d6a8e1f89935e9cbea/bundle.js:1:70237)
```

### Version information

- **Platform**: desktop

For the desktop app:

- **OS**: Ubunut
- **Version**: 0.17.0

**Comment by shkshk90** [comment]
I am using the windows desktop app.
After updating today, everynow and then riot crashes. 
it happened like 7 times in 2 hours.
I am not able to check the cause but I assume it is the same error.

**Comment by i47320673** [comment]
Seems that I have the same issue. No window showed after startup /opt/Riot/riot-web on Kubuntu 14.04 Trusty installed via repository https://riot.im/packages/debian/...
4 process with riot-web started running but nothing appear.

**Comment by lampholder** [comment]
@shkshk90 

> I am using the windows desktop app.
> After updating today, everynow and then riot crashes.
> it happened like 7 times in 2 hours.
> I am not able to check the cause but I assume it is the same error.

This sounds like https://github.com/matrix-org/riot-web-rageshakes/issues/1040


@i47320673 

> Seems that I have the same issue. No window showed after startup /opt/Riot/riot-web on Kubuntu 14.04 Trusty installed via repository https://riot.im/packages/debian/...
> 4 process with riot-web started running but nothing appear.

_Does_ this sound like the same issue? @Half-Shot reports that his app became unresponsive, but it sounds like your riot didn't get as far a appearing on the screen?

**Comment by i47320673** [comment]
As i remember 1st run after full restart OS there was empty main window frame (frame and window header). But in next run this does not show (just 4 processes in ps -fe|grep riot-web)

**Comment by Half-Shot** [comment]
@lampholder: I plucked this error out as the most likely candidate, but I have no idea what caused Riot / Electron to become unresponsive.

**Comment by shkshk90** [comment]
@lampholder I am not able to open the link that you provided.
This might not be my issue, but I am definitely seeing this issue #7512 .
I posted here before it was opened.
Thanks anyway.

**Comment by Half-Shot** [comment]
I've not seen this one in a while, can I close it?

**Comment by turt2live** [comment]
If you're not seeing it, sure. I think the latest edition of this bug is https://github.com/vector-im/riot-web/issues/8593 anyhow.
