### ISSUE TITLE
Freeze of Riot: /sync error Error: live timeline 0 is no longer live

### ISSUE THREAD

**Issue by krombel** [vector-im/riot-web#8084]
### Description

Riot freezes in some rooms

### Steps to reproduce

I don't know it just freezes my Riot when I open some rooms. In this case it is #riotx:matrix.org
It seems to happen when I open that Room. Or when I want to write something.

Logs:
```
Already have timeline for $154696594775413pkOUP:matrix.org - joining timeline !tTIucwUZLRtKnXeurb:matrix.org:2019-01-09T23:06:19.394Z to !tTIucwUZLRtKnXeurb:matrix.org:2019-01-09T23:06:00.273Z
Event $154696528479741uxpKw:maunium.net already in timeline !tTIucwUZLRtKnXeurb:matrix.org:2019-01-09T23:06:00.273Z
Event $15469652693261ywkZS:hacklab.fi already in timeline !tTIucwUZLRtKnXeurb:matrix.org:2019-01-09T23:06:00.273Z
Event $15469652611676zkLAT:matrix.vgorcum.com already in timeline !tTIucwUZLRtKnXeurb:matrix.org:2019-01-09T23:06:00.273Z
Event $154696525315204bUQuF:t2bot.io already in timeline !tTIucwUZLRtKnXeurb:matrix.org:2019-01-09T23:06:00.273Z
Caught /sync error Error: live timeline 0 is no longer live - it has a neighbouring timeline
    at b.addLiveEvents (https://riot/bundles/a2d0869af6cdc78fb649/bundle.js:53:290615)
    at b._processRoomEvents (https://riot/bundles/a2d0869af6cdc78fb649/bundle.js:60:144918)
    at https://riot/bundles/a2d0869af6cdc78fb649/bundle.js:60:140447
    at E (https://riot/bundles/a2d0869af6cdc78fb649/bundle.js:23:151703)
    at Generator._invoke (https://riot/bundles/a2d0869af6cdc78fb649/bundle.js:23:151491)
    at Generator.e.(anonymous function) [as next] (https://riot/bundles/a2d0869af6cdc78fb649/bundle.js:23:151882)
    at Generator.c (https://riot/bundles/a2d0869af6cdc78fb649/bundle.js:1:140730)
    at p._promiseFulfilled (https://riot/bundles/a2d0869af6cdc78fb649/bundle.js:1:97753)
    at https://riot/bundles/a2d0869af6cdc78fb649/bundle.js:1:99780
From previous event:
    at R.U [as _captureStackTrace] (https://riot/bundles/a2d0869af6cdc78fb649/bundle.js:1:83750)
    at new p (https://riot/bundles/a2d0869af6cdc78fb649/bundle.js:1:96624)
    at https://riot/bundles/a2d0869af6cdc78fb649/bundle.js:1:99717
    at https://riot/bundles/a2d0869af6cdc78fb649/bundle.js:53:577511
    at Object.<anonymous> (https://riot/bundles/a2d0869af6cdc78fb649/bundle.js:53:580259)
    at Object.<anonymous> (https://riot/bundles/a2d0869af6cdc78fb649/bundle.js:53:580265)
    at o (https://riot/bundles/a2d0869af6cdc78fb649/bundle.js:1:318)
    at Object.<anonymous> (https://riot/bundles/a2d0869af6cdc78fb649/bundle.js:53:522937)
    at o (https://riot/bundles/a2d0869af6cdc78fb649/bundle.js:1:318)
    at https://riot/bundles/a2d0869af6cdc78fb649/bundle.js:1:2023
    at https://riot/bundles/a2d0869af6cdc78fb649/bundle.js:1:2034
```
The decollapsed stacktrace is the following:
```
e.(anonymous function) | @ | rageshake.js:99
-- | -- | --
  | (anonymous) | @ | sync.js:946
  | E | @ | runtime.js:62
  | (anonymous) | @ | runtime.js:296
  | e.(anonymous function) | @ | runtime.js:114
  | c | @ | bluebird.js:5276
  | p._promiseRejected | @ | bluebird.js:2157
  | R._settlePromise | @ | bluebird.js:3361
  | R._settlePromise0 | @ | bluebird.js:3399
  | R._settlePromises | @ | bluebird.js:3475
  | (anonymous) | @ | bluebird.js:175
  | Promise.then (async) |   |  
  | a | @ | bluebird.js:4504
  | s.hasDevTools.l.settlePromises | @ | bluebird.js:174
  | R._reject | @ | bluebird.js:3442
  | R._rejectCallback | @ | bluebird.js:3259
  | p._continue | @ | bluebird.js:2188
  | p._promiseRejected | @ | bluebird.js:2159
  | R._settlePromise | @ | bluebird.js:3361
  | R._settlePromise0 | @ | bluebird.js:3399
  | R._settlePromises | @ | bluebird.js:3475
  | (anonymous) | @ | bluebird.js:175
  | Promise.then (async) |   |  
  | a | @ | bluebird.js:4504
  | s.hasDevTools.l.settlePromises | @ | bluebird.js:174
  | R._reject | @ | bluebird.js:3442
  | R._rejectCallback | @ | bluebird.js:3259
  | s._reject | @ | bluebird.js:3700
  | s._promiseRejected | @ | bluebird.js:3720
  | R._settlePromise | @ | bluebird.js:3361
  | R._settlePromise0 | @ | bluebird.js:3399
  | R._settlePromises | @ | bluebird.js:3475
  | (anonymous) | @ | bluebird.js:175
  | Promise.then (async) |   |  
  | a | @ | bluebird.js:4504
  | s.hasDevTools.l.settlePromises | @ | bluebird.js:174
  | R._reject | @ | bluebird.js:3442
  | R._resolveCallback | @ | bluebird.js:3241
  | R._settlePromiseFromHandler | @ | bluebird.js:3309
  | R._settlePromise | @ | bluebird.js:3354
  | R._settlePromiseCtx | @ | bluebird.js:3391
  | (anonymous) | @ | bluebird.js:165
  | Promise.then (async) |   |  
  | a | @ | bluebird.js:4504
  | s.hasDevTools.l.invoke | @ | bluebird.js:164
  | R._then | @ | bluebird.js:3046
  | c._iterate | @ | bluebird.js:4413
  | e | @ | bluebird.js:3641
  | c | @ | bluebird.js:4342
  | d | @ | bluebird.js:4444
  | t.reduce | @ | bluebird.js:4429
  | e.mapSeries | @ | bluebird.js:1667
  | (anonymous) | @ | sync.js:1297
  | E | @ | runtime.js:62
  | (anonymous) | @ | runtime.js:296
  | e.(anonymous function) | @ | runtime.js:114
  | c | @ | bluebird.js:5276
  | p._promiseFulfilled | @ | bluebird.js:2147
  | (anonymous) | @ | bluebird.js:2251
  | (anonymous) | @ | sync.js:1572
  | (anonymous) | @ | sync.js:934
  | E | @ | runtime.js:62
  | (anonymous) | @ | runtime.js:296
  | e.(anonymous function) | @ | runtime.js:114
  | c | @ | bluebird.js:5276
  | p._promiseFulfilled | @ | bluebird.js:2147
  | (anonymous) | @ | bluebird.js:165
  | Promise.then (async) |   |  
  | a | @ | bluebird.js:4504
  | s.hasDevTools.l.invoke | @ | bluebird.js:164
  | p._continue | @ | bluebird.js:2225
  | p._promiseFulfilled | @ | bluebird.js:2149
  | R._settlePromise | @ | bluebird.js:3359
  | R._settlePromise0 | @ | bluebird.js:3399
  | R._settlePromises | @ | bluebird.js:3479
  | (anonymous) | @ | bluebird.js:175
  | Promise.then (async) |   |  
  | a | @ | bluebird.js:4504
  | s.hasDevTools.l.settlePromises | @ | bluebird.js:174
  | R._fulfill | @ | bluebird.js:3425
  | R._resolveCallback | @ | bluebird.js:3217
  | R._settlePromiseFromHandler | @ | bluebird.js:3309
  | R._settlePromise | @ | bluebird.js:3354
  | R._settlePromiseCtx | @ | bluebird.js:3391
  | (anonymous) | @ | bluebird.js:165
  | Promise.then (async) |   |  
  | a | @ | bluebird.js:4504
  | s.hasDevTools.l.invoke | @ | bluebird.js:164
  | R._then | @ | bluebird.js:3046
  | R.then | @ | bluebird.js:2910
  | setSyncData | @ | indexeddb-local-backend.js:467
  | p.setSyncData | @ | indexeddb.js:277
  | (anonymous) | @ | sync.js:914
  | E | @ | runtime.js:62
  | (anonymous) | @ | runtime.js:296
  | e.(anonymous function) | @ | runtime.js:114
  | c | @ | bluebird.js:5276
  | p._promiseFulfilled | @ | bluebird.js:2147
  | R._settlePromise | @ | bluebird.js:3359
  | R._fulfillPromises | @ | bluebird.js:3454
  | R._settlePromises | @ | bluebird.js:3480
  | (anonymous) | @ | bluebird.js:175
  | Promise.then (async) |   |  
  | a | @ | bluebird.js:4504
  | s.hasDevTools.l.settlePromises | @ | bluebird.js:174
  | R._fulfill | @ | bluebird.js:3425
  | R._resolveCallback | @ | bluebird.js:3217
  | N | @ | bluebird.js:3496
  | (anonymous) | @ | http-api.js:822
  | (anonymous) | @ | http-api.js:751
  | (anonymous) | @ | index.js:294
  | o.onreadystatechange | @ | index.js:244
  | XMLHttpRequest.send (async) |   |  
  | (anonymous) | @ | index.js:218
  | t | @ | index.js:179
  | (anonymous) | @ | browser-index.js:13
  | _request | @ | http-api.js:730
  | requestOtherUrl | @ | http-api.js:610
  | request | @ | http-api.js:504
  | authedRequest | @ | http-api.js:453
  | b._doSyncRequest | @ | sync.js:1013
  | (anonymous) | @ | sync.js:878
  | E | @ | runtime.js:62
  | (anonymous) | @ | runtime.js:296
  | e.(anonymous function) | @ | runtime.js:114
  | c | @ | bluebird.js:5276
  | p._promiseFulfilled | @ | bluebird.js:2147
  | (anonymous) | @ | bluebird.js:2251
  | (anonymous) | @ | sync.js:1007
  | (anonymous) | @ | sync.js:996
  | E | @ | runtime.js:62
  | (anonymous) | @ | runtime.js:296
  | e.(anonymous function) | @ | runtime.js:114
  | c | @ | bluebird.js:5276
  | p._promiseFulfilled | @ | bluebird.js:2147
  | (anonymous) | @ | bluebird.js:165
  | Promise.then (async) |   |  
  | a | @ | bluebird.js:4504
  | s.hasDevTools.l.invoke | @ | bluebird.js:164
  | p._continue | @ | bluebird.js:2225
  | p._promiseFulfilled | @ | bluebird.js:2149
  | R._settlePromise | @ | bluebird.js:3359
  | R._settlePromise0 | @ | bluebird.js:3399
  | R._settlePromises | @ | bluebird.js:3479
  | (anonymous) | @ | bluebird.js:175
  | Promise.then (async) |   |  
  | a | @ | bluebird.js:4504
  | s.hasDevTools.l.settlePromises | @ | bluebird.js:174
  | R._fulfill | @ | bluebird.js:3425
  | R._resolveCallback | @ | bluebird.js:3217
  | p._continue | @ | bluebird.js:2198
  | p._promiseFulfilled | @ | bluebird.js:2149
  | (anonymous) | @ | bluebird.js:165
  | Promise.then (async) |   |  
  | a | @ | bluebird.js:4504
  | s.hasDevTools.l.invoke | @ | bluebird.js:164
  | p._continue | @ | bluebird.js:2225
  | p._promiseFulfilled | @ | bluebird.js:2149
  | (anonymous) | @ | bluebird.js:2251
  | (anonymous) | @ | sync.js:1572
  | (anonymous) | @ | sync.js:934
  | E | @ | runtime.js:62
  | (anonymous) | @ | runtime.js:296
  | e.(anonymous function) | @ | runtime.js:114
  | c | @ | bluebird.js:5276
  | p._promiseFulfilled | @ | bluebird.js:2147
  | (anonymous) | @ | bluebird.js:165
  | Promise.then (async) |   |  
  | a | @ | bluebird.js:4504
  | s.hasDevTools.l.invoke | @ | bluebird.js:164
  | p._continue | @ | bluebird.js:2225
  | p._promiseFulfilled | @ | bluebird.js:2149
  | R._settlePromise | @ | bluebird.js:3359
  | R._settlePromise0 | @ | bluebird.js:3399
  | R._settlePromises | @ | bluebird.js:3479
  | (anonymous) | @ | bluebird.js:175
  | Promise.then (async) |   |  
  | a | @ | bluebird.js:4504
  | s.hasDevTools.l.settlePromises | @ | bluebird.js:174
  | R._fulfill | @ | bluebird.js:3425
  | R._resolveCallback | @ | bluebird.js:3217
  | R._settlePromiseFromHandler | @ | bluebird.js:3309
  | R._settlePromise | @ | bluebird.js:3354
  | R._settlePromiseCtx | @ | bluebird.js:3391
  | (anonymous) | @ | bluebird.js:165
  | Promise.then (async) |   |  
  | a | @ | bluebird.js:4504
  | s.hasDevTools.l.invoke | @ | bluebird.js:164
  | R._then | @ | bluebird.js:3046
  | R.then | @ | bluebird.js:2910
  | setSyncData | @ | indexeddb-local-backend.js:467
  | p.setSyncData | @ | indexeddb.js:277
  | (anonymous) | @ | sync.js:914
  | E | @ | runtime.js:62
  | (anonymous) | @ | runtime.js:296
  | e.(anonymous function) | @ | runtime.js:114
  | c | @ | bluebird.js:5276
  | p._promiseFulfilled | @ | bluebird.js:2147
  | R._settlePromise | @ | bluebird.js:3359
  | R._fulfillPromises | @ | bluebird.js:3454
  | R._settlePromises | @ | bluebird.js:3480
  | (anonymous) | @ | bluebird.js:175
  | Promise.then (async) |   |  
  | a | @ | bluebird.js:4504
  | s.hasDevTools.l.settlePromises | @ | bluebird.js:174
  | R._fulfill | @ | bluebird.js:3425
  | R._resolveCallback | @ | bluebird.js:3217
  | N | @ | bluebird.js:3496
  | (anonymous) | @ | http-api.js:822
  | (anonymous) | @ | http-api.js:751
  | (anonymous) | @ | index.js:294
  | o.onreadystatechange | @ | index.js:244
  | XMLHttpRequest.send (async) |   |  
  | (anonymous) | @ | index.js:218
  | t | @ | index.js:179
  | (anonymous) | @ | browser-index.js:13
  | _request | @ | http-api.js:730
  | requestOtherUrl | @ | http-api.js:610
  | request | @ | http-api.js:504
  | authedRequest | @ | http-api.js:453
  | b._doSyncRequest | @ | sync.js:1013
  | (anonymous) | @ | sync.js:878
  | E | @ | runtime.js:62
  | (anonymous) | @ | runtime.js:296
  | e.(anonymous function) | @ | runtime.js:114
  | c | @ | bluebird.js:5276
  | p._promiseFulfilled | @ | bluebird.js:2147
  | (anonymous) | @ | bluebird.js:2251
  | (anonymous) | @ | sync.js:1007
  | (anonymous) | @ | sync.js:996
  | E | @ | runtime.js:62
  | (anonymous) | @ | runtime.js:296
  | e.(anonymous function) | @ | runtime.js:114
  | c | @ | bluebird.js:5276
  | p._promiseFulfilled | @ | bluebird.js:2147
  | (anonymous) | @ | bluebird.js:165
  | Promise.then (async) |   |  
  | a | @ | bluebird.js:4504
  | s.hasDevTools.l.invoke | @ | bluebird.js:164
  | p._continue | @ | bluebird.js:2225
  | p._promiseFulfilled | @ | bluebird.js:2149
  | R._settlePromise | @ | bluebird.js:3359
  | R._settlePromise0 | @ | bluebird.js:3399
  | R._settlePromises | @ | bluebird.js:3479
  | (anonymous) | @ | bluebird.js:175
  | Promise.then (async) |   |  
  | a | @ | bluebird.js:4504
  | s.hasDevTools.l.settlePromises | @ | bluebird.js:174
  | R._fulfill | @ | bluebird.js:3425
  | R._resolveCallback | @ | bluebird.js:3217
  | p._continue | @ | bluebird.js:2198
  | p._promiseFulfilled | @ | bluebird.js:2149
  | (anonymous) | @ | bluebird.js:165
  | Promise.then (async) |   |  
  | a | @ | bluebird.js:4504
  | s.hasDevTools.l.invoke | @ | bluebird.js:164
  | p._continue | @ | bluebird.js:2225
  | p._promiseFulfilled | @ | bluebird.js:2149
  | (anonymous) | @ | bluebird.js:2251
  | (anonymous) | @ | sync.js:1572
  | (anonymous) | @ | sync.js:934
  | E | @ | runtime.js:62
  | (anonymous) | @ | runtime.js:296
  | e.(anonymous function) | @ | runtime.js:114
  | c | @ | bluebird.js:5276
  | p._promiseFulfilled | @ | bluebird.js:2147
  | (anonymous) | @ | bluebird.js:165
  | Promise.then (async) |   |  
  | a | @ | bluebird.js:4504
  | s.hasDevTools.l.invoke | @ | bluebird.js:164
  | p._continue | @ | bluebird.js:2225
  | p._promiseFulfilled | @ | bluebird.js:2149
  | R._settlePromise | @ | bluebird.js:3359
  | R._settlePromise0 | @ | bluebird.js:3399
  | R._settlePromises | @ | bluebird.js:3479
  | (anonymous) | @ | bluebird.js:175
  | Promise.then (async) |   |  
  | a | @ | bluebird.js:4504
  | s.hasDevTools.l.settlePromises | @ | bluebird.js:174
  | R._fulfill | @ | bluebird.js:3425
  | R._resolveCallback | @ | bluebird.js:3217
  | R._settlePromiseFromHandler | @ | bluebird.js:3309
  | R._settlePromise | @ | bluebird.js:3354
  | R._settlePromiseCtx | @ | bluebird.js:3391
  | (anonymous) | @ | bluebird.js:165
  | Promise.then (async) |   |  
  | a | @ | bluebird.js:4504
  | s.hasDevTools.l.invoke | @ | bluebird.js:164
  | R._then | @ | bluebird.js:3046
  | R.then | @ | bluebird.js:2910
  | setSyncData | @ | indexeddb-local-backend.js:467
  | p.setSyncData | @ | indexeddb.js:277
  | (anonymous) | @ | sync.js:914
  | E | @ | runtime.js:62
  | (anonymous) | @ | runtime.js:296
  | e.(anonymous function) | @ | runtime.js:114
  | c | @ | bluebird.js:5276
  | p._promiseFulfilled | @ | bluebird.js:2147
  | R._settlePromise | @ | bluebird.js:3359
  | R._fulfillPromises | @ | bluebird.js:3454
  | R._settlePromises | @ | bluebird.js:3480
  | (anonymous) | @ | bluebird.js:175
  | Promise.then (async) |   |  
  | a | @ | bluebird.js:4504
  | s.hasDevTools.l.settlePromises | @ | bluebird.js:174
  | R._fulfill | @ | bluebird.js:3425
  | R._resolveCallback | @ | bluebird.js:3217
  | N | @ | bluebird.js:3496
  | (anonymous) | @ | http-api.js:822
  | (anonymous) | @ | http-api.js:751
  | (anonymous) | @ | index.js:294
  | o.onreadystatechange | @ | index.js:244
  | XMLHttpRequest.send (async) |   |  
  | (anonymous) | @ | index.js:218
  | t | @ | index.js:179
  | (anonymous) | @ | browser-index.js:13
  | _request | @ | http-api.js:730
  | requestOtherUrl | @ | http-api.js:610
  | request | @ | http-api.js:504
  | authedRequest | @ | http-api.js:453
  | b._doSyncRequest | @ | sync.js:1013
  | (anonymous) | @ | sync.js:878
  | E | @ | runtime.js:62
  | (anonymous) | @ | runtime.js:296
  | e.(anonymous function) | @ | runtime.js:114
  | c | @ | bluebird.js:5276
  | p._promiseFulfilled | @ | bluebird.js:2147
  | (anonymous) | @ | bluebird.js:2251
  | (anonymous) | @ | sync.js:1007
  | (anonymous) | @ | sync.js:996
  | E | @ | runtime.js:62
  | (anonymous) | @ | runtime.js:296
  | e.(anonymous function) | @ | runtime.js:114
  | c | @ | bluebird.js:5276
  | p._promiseFulfilled | @ | bluebird.js:2147
  | (anonymous) | @ | bluebird.js:165
  | Promise.then (async) |   |  
  | a | @ | bluebird.js:4504
  | s.hasDevTools.l.invoke | @ | bluebird.js:164
  | p._continue | @ | bluebird.js:2225
  | p._promiseFulfilled | @ | bluebird.js:2149
  | R._settlePromise | @ | bluebird.js:3359
  | R._settlePromise0 | @ | bluebird.js:3399
  | R._settlePromises | @ | bluebird.js:3479
  | (anonymous) | @ | bluebird.js:175
  | Promise.then (async) |   |  
  | a | @ | bluebird.js:4504
  | s.hasDevTools.l.settlePromises | @ | bluebird.js:174
  | R._fulfill | @ | bluebird.js:3425
  | R._resolveCallback | @ | bluebird.js:3217
  | p._continue | @ | bluebird.js:2198
  | p._promiseFulfilled | @ | bluebird.js:2149
  | R._settlePromise | @ | bluebird.js:3359
  | R._settlePromise0 | @ | bluebird.js:3399
  | R._settlePromises | @ | bluebird.js:3479
  | (anonymous) | @ | bluebird.js:175
  | Promise.then (async) |   |  
  | a | @ | bluebird.js:4504
  | s.hasDevTools.l.settlePromises | @ | bluebird.js:174
  | R._fulfill | @ | bluebird.js:3425
  | R._resolveCallback | @ | bluebird.js:3217
  | c._resolve | @ | bluebird.js:4373
  | f | @ | bluebird.js:4434
  | R._settlePromise | @ | bluebird.js:3351
  | R._settlePromise0 | @ | bluebird.js:3399
  | R._settlePromises | @ | bluebird.js:3479
  | (anonymous) | @ | bluebird.js:175
  | Promise.then (async) |   |  
  | a | @ | bluebird.js:4504
  | s.hasDevTools.l.settlePromises | @ | bluebird.js:174
  | R._fulfill | @ | bluebird.js:3425
  | R._resolveCallback | @ | bluebird.js:3217
  | R._settlePromiseFromHandler | @ | bluebird.js:3309
  | R._settlePromise | @ | bluebird.js:3354
  | R._settlePromise0 | @ | bluebird.js:3399
  | R._settlePromises | @ | bluebird.js:3479
  | (anonymous) | @ | bluebird.js:175
  | Promise.then (async) |   |  
  | a | @ | bluebird.js:4504
  | s.hasDevTools.l.settlePromises | @ | bluebird.js:174
  | R._fulfill | @ | bluebird.js:3425
  | R._resolveCallback | @ | bluebird.js:3217
  | p._continue | @ | bluebird.js:2198
  | p._promiseFulfilled | @ | bluebird.js:2149
  | (anonymous) | @ | bluebird.js:165
  | Promise.then (async) |   |  
  | a | @ | bluebird.js:4504
  | s.hasDevTools.l.invoke | @ | bluebird.js:164
  | p._continue | @ | bluebird.js:2225
  | p._promiseFulfilled | @ | bluebird.js:2149
  | (anonymous) | @ | bluebird.js:165
  | Promise.then (async) |   |  
  | a | @ | bluebird.js:4504
  | s.hasDevTools.l.invoke | @ | bluebird.js:164
  | p._continue | @ | bluebird.js:2225
  | p._promiseFulfilled | @ | bluebird.js:2149
  | (anonymous) | @ | bluebird.js:2251
  | (anonymous) | @ | sync.js:1484
  | c | @ | bluebird.js:5276
  | m | @ | bluebird.js:4467
  | p | @ | bluebird.js:4456
  | c | @ | bluebird.js:5276
  | R._settlePromiseFromHandler | @ | bluebird.js:3297
  | R._settlePromise | @ | bluebird.js:3354
  | R._settlePromiseCtx | @ | bluebird.js:3391
  | (anonymous) | @ | bluebird.js:165
```

### Version information
- **Platform**: Web
- **Browser**: reproducible in Chrome
- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc?
- **URL**: Riot 0.17.8 on a private server

**Comment by ara4n** [comment]
closing as dup of #8593
