### ISSUE TITLE
Redesign: Can't display user settings view

### ISSUE THREAD

**Issue by babolivier** [vector-im/riot-web#8126]
- **Browser**: Rambox (Electron app, thus Chrome/61.0.3163.100)
- **OS**: Arch Linux

### Description

Trying to access my user settings brings me to an infinite spinner. When doing that with the dev tools open, here's what I can see appear in the console:

```
Uncaught Error: Setting 'alwaysRetryInvites' does not appear to be a setting.
    at Function.getValueAt (https://riot.im/experimental/bundles/3d6c47dadb8656def2d4/bundle.js:136781:23)
    at Object.getInitialState (https://riot.im/experimental/bundles/3d6c47dadb8656def2d4/bundle.js:102610:44)
    at new <anonymous> (https://riot.im/experimental/bundles/3d6c47dadb8656def2d4/bundle.js:284626:54)
    at https://riot.im/experimental/bundles/3d6c47dadb8656def2d4/bundle.js:309667:18
    at measureLifeCyclePerf (https://riot.im/experimental/bundles/3d6c47dadb8656def2d4/bundle.js:309448:12)
    at ReactCompositeComponentWrapper._constructComponentWithoutOwner (https://riot.im/experimental/bundles/3d6c47dadb8656def2d4/bundle.js:309666:16)
    at ReactCompositeComponentWrapper._constructComponent (https://riot.im/experimental/bundles/3d6c47dadb8656def2d4/bundle.js:309657:19)
    at ReactCompositeComponentWrapper.mountComponent (https://riot.im/experimental/bundles/3d6c47dadb8656def2d4/bundle.js:309560:21)
    at Object.mountComponent (https://riot.im/experimental/bundles/3d6c47dadb8656def2d4/bundle.js:316820:35)
    at ReactDOMComponent.mountChildren (https://riot.im/experimental/bundles/3d6c47dadb8656def2d4/bundle.js:315655:44)
    at ReactDOMComponent._createInitialChildren (https://riot.im/experimental/bundles/3d6c47dadb8656def2d4/bundle.js:311103:32)
    at ReactDOMComponent.mountComponent (https://riot.im/experimental/bundles/3d6c47dadb8656def2d4/bundle.js:310922:12)
    at Object.mountComponent (https://riot.im/experimental/bundles/3d6c47dadb8656def2d4/bundle.js:316820:35)
    at ReactDOMComponent.mountChildren (https://riot.im/experimental/bundles/3d6c47dadb8656def2d4/bundle.js:315655:44)
    at ReactDOMComponent._createInitialChildren (https://riot.im/experimental/bundles/3d6c47dadb8656def2d4/bundle.js:311103:32)
    at ReactDOMComponent.mountComponent (https://riot.im/experimental/bundles/3d6c47dadb8656def2d4/bundle.js:310922:12)
    at Object.mountComponent (https://riot.im/experimental/bundles/3d6c47dadb8656def2d4/bundle.js:316820:35)
    at ReactDOMComponent.mountChildren (https://riot.im/experimental/bundles/3d6c47dadb8656def2d4/bundle.js:315655:44)
    at ReactDOMComponent._createInitialChildren (https://riot.im/experimental/bundles/3d6c47dadb8656def2d4/bundle.js:311103:32)
    at ReactDOMComponent.mountComponent (https://riot.im/experimental/bundles/3d6c47dadb8656def2d4/bundle.js:310922:12)
    at Object.mountComponent (https://riot.im/experimental/bundles/3d6c47dadb8656def2d4/bundle.js:316820:35)
    at ReactDOMComponent.mountChildren (https://riot.im/experimental/bundles/3d6c47dadb8656def2d4/bundle.js:315655:44)
    at ReactDOMComponent._createInitialChildren (https://riot.im/experimental/bundles/3d6c47dadb8656def2d4/bundle.js:311103:32)
    at ReactDOMComponent.mountComponent (https://riot.im/experimental/bundles/3d6c47dadb8656def2d4/bundle.js:310922:12)
    at Object.mountComponent (https://riot.im/experimental/bundles/3d6c47dadb8656def2d4/bundle.js:316820:35)
    at ReactDOMComponent.mountChildren (https://riot.im/experimental/bundles/3d6c47dadb8656def2d4/bundle.js:315655:44)
    at ReactDOMComponent._createInitialChildren (https://riot.im/experimental/bundles/3d6c47dadb8656def2d4/bundle.js:311103:32)
    at ReactDOMComponent.mountComponent (https://riot.im/experimental/bundles/3d6c47dadb8656def2d4/bundle.js:310922:12)
From previous event:
    at Object._refreshFromServer (https://riot.im/experimental/bundles/3d6c47dadb8656def2d4/bundle.js:81084:106)
    at Object.componentWillMount (https://riot.im/experimental/bundles/3d6c47dadb8656def2d4/bundle.js:81003:14)
    at https://riot.im/experimental/bundles/3d6c47dadb8656def2d4/bundle.js:309720:23
    at measureLifeCyclePerf (https://riot.im/experimental/bundles/3d6c47dadb8656def2d4/bundle.js:309448:12)
    at ReactCompositeComponentWrapper.performInitialMount (https://riot.im/experimental/bundles/3d6c47dadb8656def2d4/bundle.js:309719:9)
    at ReactCompositeComponentWrapper.mountComponent (https://riot.im/experimental/bundles/3d6c47dadb8656def2d4/bundle.js:309630:21)
    at Object.mountComponent (https://riot.im/experimental/bundles/3d6c47dadb8656def2d4/bundle.js:316820:35)
    at Object.updateChildren (https://riot.im/experimental/bundles/3d6c47dadb8656def2d4/bundle.js:309244:51)
    at ReactDOMComponent._reconcilerUpdateChildren (https://riot.im/experimental/bundles/3d6c47dadb8656def2d4/bundle.js:315625:32)
    at ReactDOMComponent._updateChildren (https://riot.im/experimental/bundles/3d6c47dadb8656def2d4/bundle.js:315729:31)
    at ReactDOMComponent.updateChildren (https://riot.im/experimental/bundles/3d6c47dadb8656def2d4/bundle.js:315716:12)
    at ReactDOMComponent._updateDOMChildren (https://riot.im/experimental/bundles/3d6c47dadb8656def2d4/bundle.js:311346:12)
    at ReactDOMComponent.updateComponent (https://riot.im/experimental/bundles/3d6c47dadb8656def2d4/bundle.js:311160:10)
    at ReactDOMComponent.receiveComponent (https://riot.im/experimental/bundles/3d6c47dadb8656def2d4/bundle.js:311122:10)
    at Object.receiveComponent (https://riot.im/experimental/bundles/3d6c47dadb8656def2d4/bundle.js:316899:22)
    at ReactCompositeComponentWrapper._updateRenderedComponent (https://riot.im/experimental/bundles/3d6c47dadb8656def2d4/bundle.js:310126:23)
    at ReactCompositeComponentWrapper._performComponentUpdate (https://riot.im/experimental/bundles/3d6c47dadb8656def2d4/bundle.js:310096:10)
    at ReactCompositeComponentWrapper.updateComponent (https://riot.im/experimental/bundles/3d6c47dadb8656def2d4/bundle.js:310017:12)
    at ReactCompositeComponentWrapper.receiveComponent (https://riot.im/experimental/bundles/3d6c47dadb8656def2d4/bundle.js:309919:10)
    at Object.receiveComponent (https://riot.im/experimental/bundles/3d6c47dadb8656def2d4/bundle.js:316899:22)
    at Object.updateChildren (https://riot.im/experimental/bundles/3d6c47dadb8656def2d4/bundle.js:309232:25)
    at ReactDOMComponent._reconcilerUpdateChildren (https://riot.im/experimental/bundles/3d6c47dadb8656def2d4/bundle.js:315625:32)
    at ReactDOMComponent._updateChildren (https://riot.im/experimental/bundles/3d6c47dadb8656def2d4/bundle.js:315729:31)
    at ReactDOMComponent.updateChildren (https://riot.im/experimental/bundles/3d6c47dadb8656def2d4/bundle.js:315716:12)
    at ReactDOMComponent._updateDOMChildren (https://riot.im/experimental/bundles/3d6c47dadb8656def2d4/bundle.js:311346:12)
    at ReactDOMComponent.updateComponent (https://riot.im/experimental/bundles/3d6c47dadb8656def2d4/bundle.js:311160:10)
    at ReactDOMComponent.receiveComponent (https://riot.im/experimental/bundles/3d6c47dadb8656def2d4/bundle.js:311122:10)
    at Object.receiveComponent (https://riot.im/experimental/bundles/3d6c47dadb8656def2d4/bundle.js:316899:22)
    at ReactCompositeComponentWrapper._updateRenderedComponent (https://riot.im/experimental/bundles/3d6c47dadb8656def2d4/bundle.js:310126:23)
    at ReactCompositeComponentWrapper._performComponentUpdate (https://riot.im/experimental/bundles/3d6c47dadb8656def2d4/bundle.js:310096:10)
    at ReactCompositeComponentWrapper.updateComponent (https://riot.im/experimental/bundles/3d6c47dadb8656def2d4/bundle.js:310017:12)

Unhandled rejection Invariant Violation: Attempted to update component `SettingsFlag` that has already been unmounted (or failed to mount).
    at invariant (https://riot.im/experimental/bundles/3d6c47dadb8656def2d4/bundle.js:288225:15)
    at ReactCompositeComponentWrapper.updateComponent (https://riot.im/experimental/bundles/3d6c47dadb8656def2d4/bundle.js:309956:52)
    at ReactCompositeComponentWrapper.receiveComponent (https://riot.im/experimental/bundles/3d6c47dadb8656def2d4/bundle.js:309919:10)
    at Object.receiveComponent (https://riot.im/experimental/bundles/3d6c47dadb8656def2d4/bundle.js:316899:22)
    at Object.updateChildren (https://riot.im/experimental/bundles/3d6c47dadb8656def2d4/bundle.js:309232:25)
    at ReactDOMComponent._reconcilerUpdateChildren (https://riot.im/experimental/bundles/3d6c47dadb8656def2d4/bundle.js:315625:32)
    at ReactDOMComponent._updateChildren (https://riot.im/experimental/bundles/3d6c47dadb8656def2d4/bundle.js:315729:31)
    at ReactDOMComponent.updateChildren (https://riot.im/experimental/bundles/3d6c47dadb8656def2d4/bundle.js:315716:12)
    at ReactDOMComponent._updateDOMChildren (https://riot.im/experimental/bundles/3d6c47dadb8656def2d4/bundle.js:311346:12)
    at ReactDOMComponent.updateComponent (https://riot.im/experimental/bundles/3d6c47dadb8656def2d4/bundle.js:311160:10)
    at ReactDOMComponent.receiveComponent (https://riot.im/experimental/bundles/3d6c47dadb8656def2d4/bundle.js:311122:10)
    at Object.receiveComponent (https://riot.im/experimental/bundles/3d6c47dadb8656def2d4/bundle.js:316899:22)
    at Object.updateChildren (https://riot.im/experimental/bundles/3d6c47dadb8656def2d4/bundle.js:309232:25)
    at ReactDOMComponent._reconcilerUpdateChildren (https://riot.im/experimental/bundles/3d6c47dadb8656def2d4/bundle.js:315625:32)
    at ReactDOMComponent._updateChildren (https://riot.im/experimental/bundles/3d6c47dadb8656def2d4/bundle.js:315729:31)
    at ReactDOMComponent.updateChildren (https://riot.im/experimental/bundles/3d6c47dadb8656def2d4/bundle.js:315716:12)
    at ReactDOMComponent._updateDOMChildren (https://riot.im/experimental/bundles/3d6c47dadb8656def2d4/bundle.js:311346:12)
    at ReactDOMComponent.updateComponent (https://riot.im/experimental/bundles/3d6c47dadb8656def2d4/bundle.js:311160:10)
    at ReactDOMComponent.receiveComponent (https://riot.im/experimental/bundles/3d6c47dadb8656def2d4/bundle.js:311122:10)
    at Object.receiveComponent (https://riot.im/experimental/bundles/3d6c47dadb8656def2d4/bundle.js:316899:22)
    at Object.updateChildren (https://riot.im/experimental/bundles/3d6c47dadb8656def2d4/bundle.js:309232:25)
    at ReactDOMComponent._reconcilerUpdateChildren (https://riot.im/experimental/bundles/3d6c47dadb8656def2d4/bundle.js:315625:32)
    at ReactDOMComponent._updateChildren (https://riot.im/experimental/bundles/3d6c47dadb8656def2d4/bundle.js:315729:31)
    at ReactDOMComponent.updateChildren (https://riot.im/experimental/bundles/3d6c47dadb8656def2d4/bundle.js:315716:12)
    at ReactDOMComponent._updateDOMChildren (https://riot.im/experimental/bundles/3d6c47dadb8656def2d4/bundle.js:311346:12)
    at ReactDOMComponent.updateComponent (https://riot.im/experimental/bundles/3d6c47dadb8656def2d4/bundle.js:311160:10)
    at ReactDOMComponent.receiveComponent (https://riot.im/experimental/bundles/3d6c47dadb8656def2d4/bundle.js:311122:10)
    at Object.receiveComponent (https://riot.im/experimental/bundles/3d6c47dadb8656def2d4/bundle.js:316899:22)
From previous event:
    at SyncApi._sync (https://riot.im/experimental/bundles/3d6c47dadb8656def2d4/bundle.js:32141:22)
    at SyncApi._callee7$ (https://riot.im/experimental/bundles/3d6c47dadb8656def2d4/bundle.js:32130:30)
    at tryCatch (https://riot.im/experimental/bundles/3d6c47dadb8656def2d4/bundle.js:47412:40)
    at Generator.invoke [as _invoke] (https://riot.im/experimental/bundles/3d6c47dadb8656def2d4/bundle.js:47646:22)
    at Generator.prototype.(anonymous function) [as next] (https://riot.im/experimental/bundles/3d6c47dadb8656def2d4/bundle.js:47464:21)
    at <anonymous>
```

For the record, when I first had the error, I manually went and cleared local storage and IndexedDB databases to log myself out and start clean, and after logging back in I still could reproduce it.

### Steps to reproduce

- Load `/experimental`
- Click on "Settings" after clicking on your display name on the top left corner

Log: not sent (since I can't do that)

**Comment by anoadragon453** [comment]
Even more interestingly, while the spinner is going, you can open a room and it'll open to the side of the still loading settings!

Looks quite cool actually.

**Comment by babolivier** [comment]
> Looks quite cool actually.

Is this early access for grid view? ;p

**Comment by turt2live** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/2443 and related PRs
