### ISSUE TITLE
NPEs in BaseAvatar breaking everything when joining rooms

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#8483]
This is reproduceable whenever i join an IRC portal room on develop, and breaks the world.

```
RVS update: !VgqLmaArcYmcJRFTsY:localhost #irc_#matthewtest2:localhost loading? false joining? true initial? true shouldPeek? true
19:49:19.849 rageshake.js:61 Warning: Failed prop type: The prop `name` is marked as required in `BaseAvatar`, but its value is `undefined`.
    in BaseAvatar (created by RoomAvatar)
    in RoomAvatar (created by RoomHeader)
    in div (created by RoomHeader)
    in div (created by RoomHeader)
    in div (created by RoomHeader)
    in RoomHeader (created by RoomView)
    in div (created by RoomView)
    in RoomView (created by LoggedInView)
    in div (created by LoggedInView)
    in DragDropContext (created by LoggedInView)
    in div (created by LoggedInView)
    in LoggedInView (created by MatrixChat)
    in MatrixChat
consoleObj.(anonymous function) @ rageshake.js:61
printWarning @ warning.js:35
warning @ warning.js:59
checkReactTypeSpec @ checkReactTypeSpec.js:80
validatePropTypes @ ReactElementValidator.js:162
createElement @ ReactElementValidator.js:216
RoomAvatar_render @ RoomAvatar.js:160
(anonymous) @ ReactCompositeComponent.js:795
measureLifeCyclePerf @ ReactCompositeComponent.js:75
_renderValidatedComponentWithoutOwnerOrContext @ ReactCompositeComponent.js:794
_renderValidatedComponent @ ReactCompositeComponent.js:821
performInitialMount @ ReactCompositeComponent.js:360
mountComponent @ ReactCompositeComponent.js:256
mountComponent @ ReactReconciler.js:45
mountChildren @ ReactMultiChild.js:236
_createInitialChildren @ ReactDOMComponent.js:703
mountComponent @ ReactDOMComponent.js:522
mountComponent @ ReactReconciler.js:45
mountChildren @ ReactMultiChild.js:236
_createInitialChildren @ ReactDOMComponent.js:703
mountComponent @ ReactDOMComponent.js:522
mountComponent @ ReactReconciler.js:45
mountChildren @ ReactMultiChild.js:236
_createInitialChildren @ ReactDOMComponent.js:703
mountComponent @ ReactDOMComponent.js:522
mountComponent @ ReactReconciler.js:45
performInitialMount @ ReactCompositeComponent.js:370
mountComponent @ ReactCompositeComponent.js:256
mountComponent @ ReactReconciler.js:45
mountChildren @ ReactMultiChild.js:236
_createInitialChildren @ ReactDOMComponent.js:703
mountComponent @ ReactDOMComponent.js:522
mountComponent @ ReactReconciler.js:45
performInitialMount @ ReactCompositeComponent.js:370
mountComponent @ ReactCompositeComponent.js:256
mountComponent @ ReactReconciler.js:45
updateChildren @ ReactChildReconciler.js:121
_reconcilerUpdateChildren @ ReactMultiChild.js:206
_updateChildren @ ReactMultiChild.js:310
updateChildren @ ReactMultiChild.js:296
_updateDOMChildren @ ReactDOMComponent.js:946
updateComponent @ ReactDOMComponent.js:760
receiveComponent @ ReactDOMComponent.js:721
receiveComponent @ ReactReconciler.js:124
_updateRenderedComponent @ ReactCompositeComponent.js:753
_performComponentUpdate @ ReactCompositeComponent.js:723
updateComponent @ ReactCompositeComponent.js:644
receiveComponent @ ReactCompositeComponent.js:545
receiveComponent @ ReactReconciler.js:124
updateChildren @ ReactChildReconciler.js:109
_reconcilerUpdateChildren @ ReactMultiChild.js:206
_updateChildren @ ReactMultiChild.js:310
updateChildren @ ReactMultiChild.js:296
_updateDOMChildren @ ReactDOMComponent.js:946
updateComponent @ ReactDOMComponent.js:760
receiveComponent @ ReactDOMComponent.js:721
receiveComponent @ ReactReconciler.js:124
_updateRenderedComponent @ ReactCompositeComponent.js:753
_performComponentUpdate @ ReactCompositeComponent.js:723
updateComponent @ ReactCompositeComponent.js:644
receiveComponent @ ReactCompositeComponent.js:545
receiveComponent @ ReactReconciler.js:124
_updateRenderedComponent @ ReactCompositeComponent.js:753
_performComponentUpdate @ ReactCompositeComponent.js:723
updateComponent @ ReactCompositeComponent.js:644
performUpdateIfNecessary @ ReactCompositeComponent.js:560
performUpdateIfNecessary @ ReactReconciler.js:156
runBatchedUpdates @ ReactUpdates.js:150
perform @ Transaction.js:143
perform @ Transaction.js:143
perform @ ReactUpdates.js:89
flushBatchedUpdates @ ReactUpdates.js:172
closeAll @ Transaction.js:209
perform @ Transaction.js:156
batchedUpdates @ ReactDefaultBatchingStrategy.js:62
enqueueUpdate @ ReactUpdates.js:200
enqueueUpdate @ ReactUpdateQueue.js:23
enqueueSetState @ ReactUpdateQueue.js:217
./node_modules/react/lib/ReactBaseClasses.js.ReactComponent.setState @ ReactBaseClasses.js:64
(anonymous) @ MatrixChat.js:96
tryCatcher @ bluebird.js:5278
Promise._settlePromiseFromHandler @ bluebird.js:3299
Promise._settlePromise @ bluebird.js:3356
Promise._settlePromiseCtx @ bluebird.js:3392
(anonymous) @ bluebird.js:167
Promise.then (async)
schedule @ bluebird.js:4506
Async.invoke @ bluebird.js:166
Promise._then @ bluebird.js:3048
Promise.done @ bluebird.js:2917
_viewRoom @ MatrixChat.js:853
onAction @ MatrixChat.js:561
_invokeCallback @ Dispatcher.js:200
dispatch @ Dispatcher.js:176
setTimeout (async)
dispatch @ dispatcher.js:52
(anonymous) @ RoomViewStore.js:177
tryCatcher @ bluebird.js:5276
Promise._settlePromiseFromHandler @ bluebird.js:3297
Promise._settlePromise @ bluebird.js:3354
Promise._fulfillPromises @ bluebird.js:3454
Promise._settlePromises @ bluebird.js:3480
(anonymous) @ bluebird.js:175
Promise.then (async)
schedule @ bluebird.js:4504
Async.settlePromises @ bluebird.js:174
Promise._fulfill @ bluebird.js:3425
Promise._resolveCallback @ bluebird.js:3217
deferResolve @ bluebird.js:3496
(anonymous) @ http-api.js:850
(anonymous) @ http-api.js:775
on_end @ index.js:294
on_state_change @ index.js:244
XMLHttpRequest.send (async)
run_xhr @ index.js:218
request @ index.js:179
(anonymous) @ browser-index.js:13
_request @ http-api.js:749
requestOtherUrl @ http-api.js:625
request @ http-api.js:510
authedRequest @ http-api.js:453
../matrix-js-sdk/lib/base-apis.js.MatrixBaseApis.getRoomIdForAlias @ base-apis.js:1068
_viewRoom @ RoomViewStore.js:175
__onDispatch @ RoomViewStore.js:78
__invokeOnDispatch @ FluxStore.js:150
(anonymous) @ FluxStore.js:81
_invokeCallback @ Dispatcher.js:200
dispatch @ Dispatcher.js:176
setTimeout (async)
dispatch @ dispatcher.js:52
runFn @ SlashCommands.js:228
run @ SlashCommands.js:51
processCommandInput @ SlashCommands.js:648
handleReturn @ MessageComposerInput.js:1082
onKeyDown @ MessageComposerInput.js:748
editorPlugin.(anonymous function) @ slate-react.es.js:4353
run @ slate.es.js:7847
(anonymous) @ slate-react.es.js:4321
call @ slate.es.js:10716
change @ slate-react.es.js:4275
onEvent @ slate-react.es.js:4320
obj.(anonymous function) @ slate-react.es.js:4259
onEvent @ slate-react.es.js:2077
obj.(anonymous function) @ slate-react.es.js:1777
boundFunc @ ReactErrorUtils.js:65
./node_modules/react-dom/lib/ReactErrorUtils.js.ReactErrorUtils.invokeGuardedCallback @ ReactErrorUtils.js:71
executeDispatch @ EventPluginUtils.js:85
executeDispatchesInOrder @ EventPluginUtils.js:108
executeDispatchesAndRelease @ EventPluginHub.js:43
executeDispatchesAndReleaseTopLevel @ EventPluginHub.js:53
forEachAccumulated @ forEachAccumulated.js:24
processEventQueue @ EventPluginHub.js:254
runEventQueueInBatch @ ReactEventEmitterMixin.js:16
handleTopLevel @ ReactEventEmitterMixin.js:27
handleTopLevelImpl @ ReactEventListener.js:72
perform @ Transaction.js:143
batchedUpdates @ ReactDefaultBatchingStrategy.js:62
batchedUpdates @ ReactUpdates.js:96
dispatchEvent @ ReactEventListener.js:147
19:49:19.853 Avatar.js:58 Uncaught TypeError: Cannot read property 'length' of undefined
    at Object.defaultAvatarUrlForString (http://localhost:8080/bundles/_dev_/bundle.js:51316:31)
    at Object._getState (http://localhost:8080/bundles/_dev_/bundle.js:88720:48)
    at Object.getInitialState (http://localhost:8080/bundles/_dev_/bundle.js:88662:21)
    at new <anonymous> (http://localhost:8080/bundles/_dev_/bundle.js:314047:54)
    at http://localhost:8080/bundles/_dev_/bundle.js:339166:18
    at measureLifeCyclePerf (http://localhost:8080/bundles/_dev_/bundle.js:338947:12)
    at ReactCompositeComponentWrapper._constructComponentWithoutOwner (http://localhost:8080/bundles/_dev_/bundle.js:339165:16)
    at ReactCompositeComponentWrapper._constructComponent (http://localhost:8080/bundles/_dev_/bundle.js:339156:19)
    at ReactCompositeComponentWrapper.mountComponent (http://localhost:8080/bundles/_dev_/bundle.js:339059:21)
    at Object.mountComponent (http://localhost:8080/bundles/_dev_/bundle.js:346319:35)
    at ReactCompositeComponentWrapper.performInitialMount (http://localhost:8080/bundles/_dev_/bundle.js:339242:34)
    at ReactCompositeComponentWrapper.mountComponent (http://localhost:8080/bundles/_dev_/bundle.js:339129:21)
    at Object.mountComponent (http://localhost:8080/bundles/_dev_/bundle.js:346319:35)
    at ReactDOMComponent.mountChildren (http://localhost:8080/bundles/_dev_/bundle.js:345154:44)
    at ReactDOMComponent._createInitialChildren (http://localhost:8080/bundles/_dev_/bundle.js:340602:32)
    at ReactDOMComponent.mountComponent (http://localhost:8080/bundles/_dev_/bundle.js:340421:12)
    at Object.mountComponent (http://localhost:8080/bundles/_dev_/bundle.js:346319:35)
    at ReactDOMComponent.mountChildren (http://localhost:8080/bundles/_dev_/bundle.js:345154:44)
    at ReactDOMComponent._createInitialChildren (http://localhost:8080/bundles/_dev_/bundle.js:340602:32)
    at ReactDOMComponent.mountComponent (http://localhost:8080/bundles/_dev_/bundle.js:340421:12)
    at Object.mountComponent (http://localhost:8080/bundles/_dev_/bundle.js:346319:35)
    at ReactDOMComponent.mountChildren (http://localhost:8080/bundles/_dev_/bundle.js:345154:44)
    at ReactDOMComponent._createInitialChildren (http://localhost:8080/bundles/_dev_/bundle.js:340602:32)
    at ReactDOMComponent.mountComponent (http://localhost:8080/bundles/_dev_/bundle.js:340421:12)
    at Object.mountComponent (http://localhost:8080/bundles/_dev_/bundle.js:346319:35)
    at ReactCompositeComponentWrapper.performInitialMount (http://localhost:8080/bundles/_dev_/bundle.js:339242:34)
    at ReactCompositeComponentWrapper.mountComponent (http://localhost:8080/bundles/_dev_/bundle.js:339129:21)
    at Object.mountComponent (http://localhost:8080/bundles/_dev_/bundle.js:346319:35)
From previous event:
    at Object._viewRoom (http://localhost:8080/bundles/_dev_/bundle.js:73886:17)
    at Object.onAction (http://localhost:8080/bundles/_dev_/bundle.js:73605:22)
    at MatrixDispatcher._invokeCallback (http://localhost:8080/bundles/_dev_/bundle.js:169946:24)
    at MatrixDispatcher.dispatch (http://localhost:8080/bundles/_dev_/bundle.js:169922:14)
defaultAvatarUrlForString @ Avatar.js:58
_getState @ BaseAvatar.js:118
BaseAvatar_getInitialState @ BaseAvatar.js:25
BaseAvatar @ factory.js:839
(anonymous) @ ReactCompositeComponent.js:294
measureLifeCyclePerf @ ReactCompositeComponent.js:75
_constructComponentWithoutOwner @ ReactCompositeComponent.js:293
_constructComponent @ ReactCompositeComponent.js:284
mountComponent @ ReactCompositeComponent.js:186
mountComponent @ ReactReconciler.js:45
performInitialMount @ ReactCompositeComponent.js:370
mountComponent @ ReactCompositeComponent.js:256
mountComponent @ ReactReconciler.js:45
mountChildren @ ReactMultiChild.js:236
_createInitialChildren @ ReactDOMComponent.js:703
mountComponent @ ReactDOMComponent.js:522
mountComponent @ ReactReconciler.js:45
mountChildren @ ReactMultiChild.js:236
_createInitialChildren @ ReactDOMComponent.js:703
mountComponent @ ReactDOMComponent.js:522
mountComponent @ ReactReconciler.js:45
mountChildren @ ReactMultiChild.js:236
_createInitialChildren @ ReactDOMComponent.js:703
mountComponent @ ReactDOMComponent.js:522
mountComponent @ ReactReconciler.js:45
performInitialMount @ ReactCompositeComponent.js:370
mountComponent @ ReactCompositeComponent.js:256
mountComponent @ ReactReconciler.js:45
mountChildren @ ReactMultiChild.js:236
_createInitialChildren @ ReactDOMComponent.js:703
mountComponent @ ReactDOMComponent.js:522
mountComponent @ ReactReconciler.js:45
performInitialMount @ ReactCompositeComponent.js:370
mountComponent @ ReactCompositeComponent.js:256
mountComponent @ ReactReconciler.js:45
updateChildren @ ReactChildReconciler.js:121
_reconcilerUpdateChildren @ ReactMultiChild.js:206
_updateChildren @ ReactMultiChild.js:310
updateChildren @ ReactMultiChild.js:296
_updateDOMChildren @ ReactDOMComponent.js:946
updateComponent @ ReactDOMComponent.js:760
receiveComponent @ ReactDOMComponent.js:721
receiveComponent @ ReactReconciler.js:124
_updateRenderedComponent @ ReactCompositeComponent.js:753
_performComponentUpdate @ ReactCompositeComponent.js:723
updateComponent @ ReactCompositeComponent.js:644
receiveComponent @ ReactCompositeComponent.js:545
receiveComponent @ ReactReconciler.js:124
updateChildren @ ReactChildReconciler.js:109
_reconcilerUpdateChildren @ ReactMultiChild.js:206
_updateChildren @ ReactMultiChild.js:310
updateChildren @ ReactMultiChild.js:296
_updateDOMChildren @ ReactDOMComponent.js:946
updateComponent @ ReactDOMComponent.js:760
receiveComponent @ ReactDOMComponent.js:721
receiveComponent @ ReactReconciler.js:124
_updateRenderedComponent @ ReactCompositeComponent.js:753
_performComponentUpdate @ ReactCompositeComponent.js:723
updateComponent @ ReactCompositeComponent.js:644
receiveComponent @ ReactCompositeComponent.js:545
receiveComponent @ ReactReconciler.js:124
_updateRenderedComponent @ ReactCompositeComponent.js:753
_performComponentUpdate @ ReactCompositeComponent.js:723
updateComponent @ ReactCompositeComponent.js:644
performUpdateIfNecessary @ ReactCompositeComponent.js:560
performUpdateIfNecessary @ ReactReconciler.js:156
runBatchedUpdates @ ReactUpdates.js:150
perform @ Transaction.js:143
perform @ Transaction.js:143
perform @ ReactUpdates.js:89
flushBatchedUpdates @ ReactUpdates.js:172
closeAll @ Transaction.js:209
perform @ Transaction.js:156
batchedUpdates @ ReactDefaultBatchingStrategy.js:62
enqueueUpdate @ ReactUpdates.js:200
enqueueUpdate @ ReactUpdateQueue.js:23
enqueueSetState @ ReactUpdateQueue.js:217
./node_modules/react/lib/ReactBaseClasses.js.ReactComponent.setState @ ReactBaseClasses.js:64
(anonymous) @ MatrixChat.js:96
tryCatcher @ bluebird.js:5278
Promise._settlePromiseFromHandler @ bluebird.js:3299
Promise._settlePromise @ bluebird.js:3356
Promise._settlePromiseCtx @ bluebird.js:3392
(anonymous) @ bluebird.js:167
setTimeout (async)
Async.throwLater @ bluebird.js:118
Async.fatalError @ bluebird.js:108
Promise._reject @ bluebird.js:3439
Promise._rejectCallback @ bluebird.js:3260
Promise._settlePromiseFromHandler @ bluebird.js:3308
Promise._settlePromise @ bluebird.js:3356
Promise._settlePromiseCtx @ bluebird.js:3392
(anonymous) @ bluebird.js:167
Promise.then (async)
schedule @ bluebird.js:4506
Async.invoke @ bluebird.js:166
Promise._then @ bluebird.js:3048
Promise.done @ bluebird.js:2917
_viewRoom @ MatrixChat.js:853
onAction @ MatrixChat.js:561
_invokeCallback @ Dispatcher.js:200
dispatch @ Dispatcher.js:176
setTimeout (async)
dispatch @ dispatcher.js:52
(anonymous) @ RoomViewStore.js:177
tryCatcher @ bluebird.js:5276
Promise._settlePromiseFromHandler @ bluebird.js:3297
Promise._settlePromise @ bluebird.js:3354
Promise._fulfillPromises @ bluebird.js:3454
Promise._settlePromises @ bluebird.js:3480
(anonymous) @ bluebird.js:175
Promise.then (async)
schedule @ bluebird.js:4504
Async.settlePromises @ bluebird.js:174
Promise._fulfill @ bluebird.js:3425
Promise._resolveCallback @ bluebird.js:3217
deferResolve @ bluebird.js:3496
(anonymous) @ http-api.js:850
(anonymous) @ http-api.js:775
on_end @ index.js:294
on_state_change @ index.js:244
XMLHttpRequest.send (async)
run_xhr @ index.js:218
request @ index.js:179
(anonymous) @ browser-index.js:13
_request @ http-api.js:749
requestOtherUrl @ http-api.js:625
request @ http-api.js:510
authedRequest @ http-api.js:453
../matrix-js-sdk/lib/base-apis.js.MatrixBaseApis.getRoomIdForAlias @ base-apis.js:1068
_viewRoom @ RoomViewStore.js:175
__onDispatch @ RoomViewStore.js:78
__invokeOnDispatch @ FluxStore.js:150
(anonymous) @ FluxStore.js:81
_invokeCallback @ Dispatcher.js:200
dispatch @ Dispatcher.js:176
setTimeout (async)
dispatch @ dispatcher.js:52
runFn @ SlashCommands.js:228
run @ SlashCommands.js:51
processCommandInput @ SlashCommands.js:648
handleReturn @ MessageComposerInput.js:1082
onKeyDown @ MessageComposerInput.js:748
editorPlugin.(anonymous function) @ slate-react.es.js:4353
run @ slate.es.js:7847
(anonymous) @ slate-react.es.js:4321
call @ slate.es.js:10716
change @ slate-react.es.js:4275
onEvent @ slate-react.es.js:4320
obj.(anonymous function) @ slate-react.es.js:4259
onEvent @ slate-react.es.js:2077
obj.(anonymous function) @ slate-react.es.js:1777
boundFunc @ ReactErrorUtils.js:65
./node_modules/react-dom/lib/ReactErrorUtils.js.ReactErrorUtils.invokeGuardedCallback @ ReactErrorUtils.js:71
executeDispatch @ EventPluginUtils.js:85
executeDispatchesInOrder @ EventPluginUtils.js:108
executeDispatchesAndRelease @ EventPluginHub.js:43
executeDispatchesAndReleaseTopLevel @ EventPluginHub.js:53
forEachAccumulated @ forEachAccumulated.js:24
processEventQueue @ EventPluginHub.js:254
runEventQueueInBatch @ ReactEventEmitterMixin.js:16
handleTopLevel @ ReactEventEmitterMixin.js:27
handleTopLevelImpl @ ReactEventListener.js:72
perform @ Transaction.js:143
batchedUpdates @ ReactDefaultBatchingStrategy.js:62
batchedUpdates @ ReactUpdates.js:96
dispatchEvent @ ReactEventListener.js:147
19:49:20.053 rageshake.js:61 Caught /sync error Invariant Violation: Attempted to update component `BaseAvatar` that has already been unmounted (or failed to mount).
    at invariant (http://localhost:8080/bundles/_dev_/bundle.js:317646:15)
    at ReactCompositeComponentWrapper.updateComponent (http://localhost:8080/bundles/_dev_/bundle.js:339455:52)
    at ReactCompositeComponentWrapper.receiveComponent (http://localhost:8080/bundles/_dev_/bundle.js:339418:10)
    at Object.receiveComponent (http://localhost:8080/bundles/_dev_/bundle.js:346398:22)
    at ReactCompositeComponentWrapper._updateRenderedComponent (http://localhost:8080/bundles/_dev_/bundle.js:339625:23)
    at ReactCompositeComponentWrapper._performComponentUpdate (http://localhost:8080/bundles/_dev_/bundle.js:339595:10)
    at ReactCompositeComponentWrapper.updateComponent (http://localhost:8080/bundles/_dev_/bundle.js:339516:12)
    at ReactCompositeComponentWrapper.receiveComponent (http://localhost:8080/bundles/_dev_/bundle.js:339418:10)
    at Object.receiveComponent (http://localhost:8080/bundles/_dev_/bundle.js:346398:22)
    at Object.updateChildren (http://localhost:8080/bundles/_dev_/bundle.js:338731:25)
    at ReactDOMComponent._reconcilerUpdateChildren (http://localhost:8080/bundles/_dev_/bundle.js:345124:32)
    at ReactDOMComponent._updateChildren (http://localhost:8080/bundles/_dev_/bundle.js:345228:31)
    at ReactDOMComponent.updateChildren (http://localhost:8080/bundles/_dev_/bundle.js:345215:12)
    at ReactDOMComponent._updateDOMChildren (http://localhost:8080/bundles/_dev_/bundle.js:340845:12)
    at ReactDOMComponent.updateComponent (http://localhost:8080/bundles/_dev_/bundle.js:340659:10)
    at ReactDOMComponent.receiveComponent (http://localhost:8080/bundles/_dev_/bundle.js:340621:10)
    at Object.receiveComponent (http://localhost:8080/bundles/_dev_/bundle.js:346398:22)
    at Object.updateChildren (http://localhost:8080/bundles/_dev_/bundle.js:338731:25)
    at ReactDOMComponent._reconcilerUpdateChildren (http://localhost:8080/bundles/_dev_/bundle.js:345124:32)
    at ReactDOMComponent._updateChildren (http://localhost:8080/bundles/_dev_/bundle.js:345228:31)
    at ReactDOMComponent.updateChildren (http://localhost:8080/bundles/_dev_/bundle.js:345215:12)
    at ReactDOMComponent._updateDOMChildren (http://localhost:8080/bundles/_dev_/bundle.js:340845:12)
    at ReactDOMComponent.updateComponent (http://localhost:8080/bundles/_dev_/bundle.js:340659:10)
    at ReactDOMComponent.receiveComponent (http://localhost:8080/bundles/_dev_/bundle.js:340621:10)
    at Object.receiveComponent (http://localhost:8080/bundles/_dev_/bundle.js:346398:22)
    at Object.updateChildren (http://localhost:8080/bundles/_dev_/bundle.js:338731:25)
    at ReactDOMComponent._reconcilerUpdateChildren (http://localhost:8080/bundles/_dev_/bundle.js:345124:32)
    at ReactDOMComponent._updateChildren (http://localhost:8080/bundles/_dev_/bundle.js:345228:31)
From previous event:
    at http://localhost:8080/bundles/_dev_/bundle.js:34749:46
From previous event:
    at SyncApi._callee10$ (http://localhost:8080/bundles/_dev_/bundle.js:34548:74)
    at tryCatch (http://localhost:8080/bundles/_dev_/bundle.js:49757:40)
    at Generator.invoke [as _invoke] (http://localhost:8080/bundles/_dev_/bundle.js:49991:22)
    at Generator.prototype.(anonymous function) [as next] (http://localhost:8080/bundles/_dev_/bundle.js:49809:21)
From previous event:
    at SyncApi._processSyncResponse (http://localhost:8080/bundles/_dev_/bundle.js:34837:22)
    at SyncApi._callee7$ (http://localhost:8080/bundles/_dev_/bundle.js:34185:60)
    at tryCatch (http://localhost:8080/bundles/_dev_/bundle.js:49757:40)
    at Generator.invoke [as _invoke] (http://localhost:8080/bundles/_dev_/bundle.js:49991:22)
    at Generator.prototype.(anonymous function) [as next] (http://localhost:8080/bundles/_dev_/bundle.js:49809:21)
```

**Comment by ara4n** [comment]
i am reproducing this reliably when I try to join an IRC-bridged room (using local HS and irc bridge).  The flow is:

 * /join #irc_#foo:localhost
 * watch infinite spinner; room never joins
 * hit refresh
 * joins okay. type things into the room - they instantly disappear from the timeline; log fills with the error above
 * hit refresh again
 * now it works :/

**Comment by bwindels** [comment]
odd, I would have thought https://github.com/matrix-org/matrix-react-sdk/pull/2601 would have fixed this.

**Comment by ara4n** [comment]
yup, looks like this is fixed now.
