### ISSUE TITLE
Unhandled exception Error: Object has been destroyed

### ISSUE THREAD

**Issue by shirishag75** [vector-im/riot-web#8767]
```
 data between origins
Loading path: /opt/Riot/resources/origin_migrator/source.html
No session to migrate from old origin
Attempting to migrate data between origins
Loading path: /opt/Riot/resources/origin_migrator/source.html
No session to migrate from old origin
Unhandled exception Error: Object has been destroyed
    at EventEmitter.ipcMain.on (/opt/Riot/resources/app.asar/src/originMigrator.js:49:27)
    at EventEmitter.emit (events.js:187:15)
    at WebContents.<anonymous> (/opt/Riot/resources/electron.asar/browser/api/web-contents.js:335:13)
    at WebContents.emit (events.js:182:13)
```

```
Package: riot-web
Version: 1.0.1
Severity: normal

-- System Information:
Debian Release: buster/sid
  APT prefers testing
  APT policy: (990, 'testing'), (500, 'unstable-debug'), (500, 'testing-debug'), (500, 'unstable'), (1, 'experimental-debug'), (1, 'experimental')
Architecture: amd64 (x86_64)

Kernel: Linux 4.19.0-2-amd64 (SMP w/4 CPU cores)
Locale: LANG=en_IN, LC_CTYPE=en_IN (charmap=UTF-8), LANGUAGE=en_IN:en (charmap=UTF-8)
Shell: /bin/sh linked to /bin/dash
Init: systemd (via /run/systemd/system)
LSM: AppArmor: enabled

Versions of packages riot-web depends on:
ii  gconf-service     3.2.6-5
ii  gconf2            3.2.6-5
ii  libappindicator1  0.4.92-7
ii  libnotify4        0.7.7-4
ii  libnss3           2:3.42-1
ii  libxss1           1:1.2.3-1
ii  libxtst6          2:1.2.3-1

riot-web recommends no packages.

riot-web suggests no packages.

-- no debconf information

```

I will not be sending any logs till https://github.com/vector-im/riot-web/issues/8687 is fixed.

**Comment by jryans** [comment]
Does Riot continue to function after this point, or is it broken?

**Comment by lampholder** [comment]
I don't think there's enough here to usefully make progress so I'm going to close.

**Comment by shirishag75** [comment]
it basically broke but I didn't see it happening often. Sorry I overlooked it @jryans
