### ISSUE TITLE
rooms stuck loading with riot-web stable and develop

### ISSUE THREAD

**Issue by bbigras** [vector-im/riot-web#8958]
### Description

The rooms wont load fully. I see some old messages but the spinner is stuck.

### Steps to reproduce

- just open a room

Describe how what happens differs from what you expected.

Log: in a minute    

![image](https://user-images.githubusercontent.com/24027/53443448-bc383f00-39d9-11e9-8ec5-83b93ddbd4b7.png)

### Version information

- Chrome Version 72.0.3626.81 (Build officiel) (64 bits)
- NixOS
- url: /app and /develop

**Comment by bbigras** [comment]
I can't upload the logs. There's an infinite spinner there too.

Disabling all my Chrome extension didn't seem to change anything.

My Chrome might be slightly outdated btw but I would be surprised if it was an issue.

**Comment by jryans** [comment]
Thanks for the report! Do you notice any errors in the DevTools Console tab?

**Comment by bbigras** [comment]
Yes but according to @turt2live on #riot-web:matrix.org, the error is "masked".

```
rageshake.js:61 Error decrypting event (id=$1550343836309011aUUDA:matrix.org): TypeError: Cannot read property 'message' of undefined
    at MegolmDecryption._callee6$ (https://riot.im/develop/bundles/90e9f01f2841cbf558dd/bundle.js:12426:42)
    at tryCatch (https://riot.im/develop/bundles/90e9f01f2841cbf558dd/bundle.js:49900:40)
    at Generator.invoke [as _invoke] (https://riot.im/develop/bundles/90e9f01f2841cbf558dd/bundle.js:50134:22)
    at Generator.prototype.(anonymous function) [as throw] (https://riot.im/develop/bundles/90e9f01f2841cbf558dd/bundle.js:49952:21)
From previous event:
    at MegolmDecryption.decryptEvent (https://riot.im/develop/bundles/90e9f01f2841cbf558dd/bundle.js:12490:22)
    at Crypto../matrix-js-sdk/lib/crypto/index.js.Crypto.decryptEvent (https://riot.im/develop/bundles/90e9f01f2841cbf558dd/bundle.js:15643:16)
    at MatrixEvent._callee$ (https://riot.im/develop/bundles/90e9f01f2841cbf558dd/bundle.js:25338:66)
From previous event:
    at MatrixEvent._decryptionLoop (https://riot.im/develop/bundles/90e9f01f2841cbf558dd/bundle.js:25428:26)
    at MatrixEvent.<anonymous> (https://riot.im/develop/bundles/90e9f01f2841cbf558dd/bundle.js:25282:44)
From previous event:
    at MatrixEvent.attemptDecryption (https://riot.im/develop/bundles/90e9f01f2841cbf558dd/bundle.js:25287:25)
    at mapper (https://riot.im/develop/bundles/90e9f01f2841cbf558dd/bundle.js:6710:19)
    at https://riot.im/develop/bundles/90e9f01f2841cbf558dd/bundle.js:35147:16
    at Array.map (<anonymous>)
    at SyncApi../matrix-js-sdk/lib/sync.js.SyncApi._mapSyncEventsFormat (https://riot.im/develop/bundles/90e9f01f2841cbf558dd/bundle.js:35143:23)
    at _callee9$ (https://riot.im/develop/bundles/90e9f01f2841cbf558dd/bundle.js:34743:71)
    at tryCatch (https://riot.im/develop/bundles/90e9f01f2841cbf558dd/bundle.js:49900:40)
    at Generator.invoke [as _invoke] (https://riot.im/develop/bundles/90e9f01f2841cbf558dd/bundle.js:50134:22)
    at Generator.prototype.(anonymous function) [as next] (https://riot.im/develop/bundles/90e9f01f2841cbf558dd/bundle.js:49952:21)
From previous event:
    at https://riot.im/develop/bundles/90e9f01f2841cbf558dd/bundle.js:34892:46
From previous event:
    at SyncApi._callee10$ (https://riot.im/develop/bundles/90e9f01f2841cbf558dd/bundle.js:34691:74)
    at tryCatch (https://riot.im/develop/bundles/90e9f01f2841cbf558dd/bundle.js:49900:40)
    at Generator.invoke [as _invoke] (https://riot.im/develop/bundles/90e9f01f2841cbf558dd/bundle.js:50134:22)
    at Generator.prototype.(anonymous function) [as next] (https://riot.im/develop/bundles/90e9f01f2841cbf558dd/bundle.js:49952:21)
From previous event:
    at SyncApi._processSyncResponse (https://riot.im/develop/bundles/90e9f01f2841cbf558dd/bundle.js:34980:22)
    at SyncApi._callee6$ (https://riot.im/develop/bundles/90e9f01f2841cbf558dd/bundle.js:34203:60)
    at tryCatch (https://riot.im/develop/bundles/90e9f01f2841cbf558dd/bundle.js:49900:40)
    at Generator.invoke [as _invoke] (https://riot.im/develop/bundles/90e9f01f2841cbf558dd/bundle.js:50134:22)
    at Generator.prototype.(anonymous function) [as next] (https://riot.im/develop/bundles/90e9f01f2841cbf558dd/bundle.js:49952:21)
From previous event:
    at SyncApi._syncFromCache (https://riot.im/develop/bundles/90e9f01f2841cbf558dd/bundle.js:34233:22)
    at https://riot.im/develop/bundles/90e9f01f2841cbf558dd/bundle.js:34126:29
From previous event:
    at SyncApi../matrix-js-sdk/lib/sync.js.SyncApi.sync (https://riot.im/develop/bundles/90e9f01f2841cbf558dd/bundle.js:34124:12)
    at MatrixClient.<anonymous> (https://riot.im/develop/bundles/90e9f01f2841cbf558dd/bundle.js:6362:23)
From previous event:
    at MatrixClient.startClient (https://riot.im/develop/bundles/90e9f01f2841cbf558dd/bundle.js:6366:23)
    at MatrixClientPeg._callee$ (https://riot.im/develop/bundles/90e9f01f2841cbf558dd/bundle.js:56704:74)
    at tryCatch (https://riot.im/develop/bundles/90e9f01f2841cbf558dd/bundle.js:259328:40)
    at Generator.invoke [as _invoke] (https://riot.im/develop/bundles/90e9f01f2841cbf558dd/bundle.js:259562:22)
    at Generator.prototype.(anonymous function) [as next] (https://riot.im/develop/bundles/90e9f01f2841cbf558dd/bundle.js:259380:21)
    at Generator.tryCatcher (https://riot.im/develop/bundles/90e9f01f2841cbf558dd/bundle.js:160893:23)
    at PromiseSpawn._promiseFulfilled (https://riot.im/develop/bundles/90e9f01f2841cbf558dd/bundle.js:158026:49)
    at Promise._settlePromise (https://riot.im/develop/bundles/90e9f01f2841cbf558dd/bundle.js:159096:26)
    at Promise._settlePromise0 (https://riot.im/develop/bundles/90e9f01f2841cbf558dd/bundle.js:159136:10)
    at Promise._settlePromises (https://riot.im/develop/bundles/90e9f01f2841cbf558dd/bundle.js:159216:18)
    at https://riot.im/develop/bundles/90e9f01f2841cbf558dd/bundle.js:156114:25
```

**Comment by turt2live** [comment]
(that error is "fixed" by https://github.com/matrix-org/matrix-js-sdk/pull/847 - the underlying cause is unknown)

**Comment by bbigras** [comment]
> (that error is "fixed" by [matrix-org/matrix-js-sdk#847](https://github.com/matrix-org/matrix-js-sdk/pull/847) - the underlying cause is unknown)

Oh yeah sorry I missed that message in #riot-web:matrix.org.

**Comment by bbigras** [comment]
```
Error decrypting event (id=$1550343836309011aUUDA:matrix.org): DecryptionError[msg: Unknown Error: Error is undefined, session: U2UAUxzyrCVHPbtbjP3WaUR9+kfn6luFSWNTAJY3d0Y|tgUbrN+rsbMzjH6T3wtKKLxpQdEldUrhaxydx4N9nLc]

consoleObj.(anonymous function) | @ | rageshake.js:61
-- | -- | --
  | _callee$ | @ | event.js:453
  | tryCatch | @ | runtime.js:62
  | invoke | @ | runtime.js:296
  | prototype.(anonymous function) | @ | runtime.js:114
  | tryCatcher | @ | bluebird.js:5276
  | PromiseSpawn._promiseRejected | @ | bluebird.js:2157
  | Promise._settlePromise | @ | bluebird.js:3361
  | Promise._settlePromise0 | @ | bluebird.js:3399
  | Promise._settlePromises | @ | bluebird.js:3475
  | (anonymous) | @ | bluebird.js:175
  | Promise.then (async) |   |  
  | schedule | @ | bluebird.js:4504
  | Async.settlePromises | @ | bluebird.js:174
  | Promise._reject | @ | bluebird.js:3442
  | Promise._rejectCallback | @ | bluebird.js:3259
  | PromiseSpawn._continue | @ | bluebird.js:2188
  | PromiseSpawn._promiseRejected | @ | bluebird.js:2159
  | Promise._settlePromise | @ | bluebird.js:3361
  | Promise._settlePromise0 | @ | bluebird.js:3399
  | Promise._settlePromises | @ | bluebird.js:3475
  | (anonymous) | @ | bluebird.js:175
  | Promise.then (async) |   |  
  | schedule | @ | bluebird.js:4504
  | Async.settlePromises | @ | bluebird.js:174
  | Promise._reject | @ | bluebird.js:3442
  | Promise._rejectCallback | @ | bluebird.js:3259
  | PromiseSpawn._continue | @ | bluebird.js:2188
  | PromiseSpawn._promiseRejected | @ | bluebird.js:2159
  | Promise._settlePromise | @ | bluebird.js:3361
  | Promise._settlePromise0 | @ | bluebird.js:3399
  | Promise._settlePromises | @ | bluebird.js:3475
  | (anonymous) | @ | bluebird.js:175
  | Promise.then (async) |   |  
  | schedule | @ | bluebird.js:4504
  | Async.settlePromises | @ | bluebird.js:174
  | Promise._reject | @ | bluebird.js:3442
  | Promise._settlePromise | @ | bluebird.js:3369
  | Promise._settlePromise0 | @ | bluebird.js:3399
  | Promise._settlePromises | @ | bluebird.js:3475
  | (anonymous) | @ | bluebird.js:175
  | Promise.then (async) |   |  
  | schedule | @ | bluebird.js:4504
  | Async.settlePromises | @ | bluebird.js:174
  | Promise._reject | @ | bluebird.js:3442
  | Promise._rejectCallback | @ | bluebird.js:3259
  | (anonymous) | @ | bluebird.js:3271
  | txn.onabort | @ | indexeddb-crypto-store-backend.js:699
```

**Comment by bbigras** [comment]
sorry about the repost.

```
Error decrypting event (id=$1550343836309011aUUDA:matrix.org): DecryptionError[msg: Unknown Error: Error is undefined, session: <redacted>]

consoleObj.(anonymous function) | @ | rageshake.js:61
-- | -- | --
  | _callee$ | @ | event.js:453
  | tryCatch | @ | runtime.js:62
  | invoke | @ | runtime.js:296
  | prototype.(anonymous function) | @ | runtime.js:114
  | tryCatcher | @ | bluebird.js:5276
  | PromiseSpawn._promiseRejected | @ | bluebird.js:2157
  | Promise._settlePromise | @ | bluebird.js:3361
  | Promise._settlePromise0 | @ | bluebird.js:3399
  | Promise._settlePromises | @ | bluebird.js:3475
  | (anonymous) | @ | bluebird.js:175
  | Promise.then (async) |   |  
  | schedule | @ | bluebird.js:4504
  | Async.settlePromises | @ | bluebird.js:174
  | Promise._reject | @ | bluebird.js:3442
  | Promise._rejectCallback | @ | bluebird.js:3259
  | PromiseSpawn._continue | @ | bluebird.js:2188
  | PromiseSpawn._promiseRejected | @ | bluebird.js:2159
  | Promise._settlePromise | @ | bluebird.js:3361
  | Promise._settlePromise0 | @ | bluebird.js:3399
  | Promise._settlePromises | @ | bluebird.js:3475
  | (anonymous) | @ | bluebird.js:175
  | Promise.then (async) |   |  
  | schedule | @ | bluebird.js:4504
  | Async.settlePromises | @ | bluebird.js:174
  | Promise._reject | @ | bluebird.js:3442
  | Promise._rejectCallback | @ | bluebird.js:3259
  | PromiseSpawn._continue | @ | bluebird.js:2188
  | PromiseSpawn._promiseRejected | @ | bluebird.js:2159
  | Promise._settlePromise | @ | bluebird.js:3361
  | Promise._settlePromise0 | @ | bluebird.js:3399
  | Promise._settlePromises | @ | bluebird.js:3475
  | (anonymous) | @ | bluebird.js:175
  | Promise.then (async) |   |  
  | schedule | @ | bluebird.js:4504
  | Async.settlePromises | @ | bluebird.js:174
  | Promise._reject | @ | bluebird.js:3442
  | Promise._settlePromise | @ | bluebird.js:3369
  | Promise._settlePromise0 | @ | bluebird.js:3399
  | Promise._settlePromises | @ | bluebird.js:3475
  | (anonymous) | @ | bluebird.js:175
  | Promise.then (async) |   |  
  | schedule | @ | bluebird.js:4504
  | Async.settlePromises | @ | bluebird.js:174
  | Promise._reject | @ | bluebird.js:3442
  | Promise._rejectCallback | @ | bluebird.js:3259
  | (anonymous) | @ | bluebird.js:3271
  | txn.onabort | @ | indexeddb-crypto-store-backend.js:699
```

**Comment by lampholder** [comment]
So did we have two errors - the error and the error-masking-the-error? And the error-masking-the-error was fixed - does that mean we still have this problem with stuck rooms?

**Comment by bbigras** [comment]
The second time I posted the error was after I "updated" Riot develop. I still had the infinite spinner but the error was in a different form so I guess [matrix-org/matrix-js-sdk#847](https://github.com/matrix-org/matrix-js-sdk/pull/847) changed it. That was last night.

This morning the rooms are loading correctly so I guess it's fixed.

**Comment by bbigras** [comment]
I just got the problem again.

**Comment by bbigras** [comment]
```
Error decrypting event (id=$1550344128310187eIYld:matrix.org): DecryptionError[msg: Unknown Error: Error is undefined, session: <redacted>]
consoleObj.(anonymous function) @ rageshake.js:61
_callee$ @ event.js:453
tryCatch @ runtime.js:62
invoke @ runtime.js:296
prototype.(anonymous function) @ runtime.js:114
tryCatcher @ bluebird.js:5276
PromiseSpawn._promiseRejected @ bluebird.js:2157
Promise._settlePromise @ bluebird.js:3361
Promise._settlePromise0 @ bluebird.js:3399
Promise._settlePromises @ bluebird.js:3475
(anonymous) @ bluebird.js:175
Promise.then (async)
schedule @ bluebird.js:4504
Async.settlePromises @ bluebird.js:174
Promise._reject @ bluebird.js:3442
Promise._rejectCallback @ bluebird.js:3259
PromiseSpawn._continue @ bluebird.js:2188
PromiseSpawn._promiseRejected @ bluebird.js:2159
Promise._settlePromise @ bluebird.js:3361
Promise._settlePromise0 @ bluebird.js:3399
Promise._settlePromises @ bluebird.js:3475
(anonymous) @ bluebird.js:175
Promise.then (async)
schedule @ bluebird.js:4504
Async.settlePromises @ bluebird.js:174
Promise._reject @ bluebird.js:3442
Promise._rejectCallback @ bluebird.js:3259
PromiseSpawn._continue @ bluebird.js:2188
PromiseSpawn._promiseRejected @ bluebird.js:2159
Promise._settlePromise @ bluebird.js:3361
Promise._settlePromise0 @ bluebird.js:3399
Promise._settlePromises @ bluebird.js:3475
(anonymous) @ bluebird.js:175
Promise.then (async)
schedule @ bluebird.js:4504
Async.settlePromises @ bluebird.js:174
Promise._reject @ bluebird.js:3442
Promise._settlePromise @ bluebird.js:3369
Promise._settlePromise0 @ bluebird.js:3399
Promise._settlePromises @ bluebird.js:3475
(anonymous) @ bluebird.js:175
Promise.then (async)
schedule @ bluebird.js:4504
Async.settlePromises @ bluebird.js:174
Promise._reject @ bluebird.js:3442
Promise._rejectCallback @ bluebird.js:3259
(anonymous) @ bluebird.js:3271
txn.onabort @ indexeddb-crypto-store-backend.js:699
```

**Comment by turt2live** [comment]
@bbigras just to rule out https://github.com/vector-im/riot-web/issues/6120 - how close percentage-wise is your disk to being full? If it's 90% full, it might the cause of the problem here. 

I assume sending rageshakes ("Submit Debug Logs" from the Help & About settings tab) still doesn't work for you?

**Comment by bbigras** [comment]
Oh. That must be the problem. My disk is 100% full right now (649MB free). And I'm pretty sure it was the case yesterday too.

Yeah "Submit Debug Logs" doesn't seems to work.

**Comment by turt2live** [comment]
I'd try clearing up some space and seeing if that helps the app get going. It might need a page refresh after some space is cleared to actually start working.

**Comment by bbigras** [comment]
Yes it seems the problem is gone with more free space. That was probably why the problem "resolved itself" yesterday. I had to free up space.

Is there a way to detect that from the browser (I would be surprised)? or maybe just show better errors messages.

**Comment by turt2live** [comment]
Not really, unfortunately. https://github.com/vector-im/riot-web/issues/6120 describes a bit more as to what is going on though.

**Comment by bbigras** [comment]
Ok thanks and sorry for the noise.

**Comment by turt2live** [comment]
It's no noise at all :)

Weird behaviour isn't expected and we should absolutely be fixing it.
