### ISSUE TITLE
Key session sharing might be able to break sending messages?

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#9214]
Two errors found in the logs. Report came in as being unable to send messages (remains grey, no further feedback or errors).

* `https://riot.im/develop/bundles/6a84fc91051669a6304d/bundle.js:17670:57` is https://github.com/matrix-org/matrix-js-sdk/blob/f8985dbb39c6bbb449861c0e161c38ae3ac0ae7e/src/crypto/olmlib.js#L180
* `https://riot.im/develop/bundles/6a84fc91051669a6304d/bundle.js:17675:57` is https://github.com/matrix-org/matrix-js-sdk/blob/f8985dbb39c6bbb449861c0e161c38ae3ac0ae7e/src/crypto/olmlib.js#L248

```
2019-03-18T14:24:30.551Z W No one-time keys (alg=signed_curve25519) for device @REDACTED:REDACTED
2019-03-18T14:24:30.563Z W %cUnhandled rejection TypeError: Cannot read property 'resolve' of undefined
    at _loop3 (https://riot.im/develop/bundles/6a84fc91051669a6304d/bundle.js:17670:57)
    at _loop2 (https://riot.im/develop/bundles/6a84fc91051669a6304d/bundle.js:17684:45)
    at Object._callee2$ (https://riot.im/develop/bundles/6a84fc91051669a6304d/bundle.js:17699:33)
From previous event:
    at Object.ensureOlmSessionsForDevices (https://riot.im/develop/bundles/6a84fc91051669a6304d/bundle.js:17728:22)
    at Crypto._callee20$ (https://riot.im/develop/bundles/6a84fc91051669a6304d/bundle.js:16620:62)
    at tryCatch (https://riot.im/develop/bundles/6a84fc91051669a6304d/bundle.js:50316:40)
    at Generator.invoke [as _invoke] (https://riot.im/develop/bundles/6a84fc91051669a6304d/bundle.js:50550:22)
    at Generator.prototype.(anonymous function) [as next] (https://riot.im/develop/bundles/6a84fc91051669a6304d/bundle.js:50368:21)
From previous event:
    at Crypto._onToDeviceBadEncrypted (https://riot.im/develop/bundles/6a84fc91051669a6304d/bundle.js:16702:23)
    at Crypto.../../ReactSDKDevelop/workspace/matrix-js-sdk/lib/crypto/index.js.Crypto._onToDeviceEvent (https://riot.im/develop/bundles/6a84fc91051669a6304d/bundle.js:16259:18)
    at MatrixEvent.<anonymous> (https://riot.im/develop/bundles/6a84fc91051669a6304d/bundle.js:16263:24)
    at MatrixEvent.g (https://riot.im/develop/bundles/6a84fc91051669a6304d/bundle.js:324440:16)
    at MatrixEvent../node_modules/events/events.js.EventEmitter.emit (https://riot.im/develop/bundles/6a84fc91051669a6304d/bundle.js:324371:20)
    at MatrixEvent._callee$ (https://riot.im/develop/bundles/6a84fc91051669a6304d/bundle.js:25785:34)
    at tryCatch (https://riot.im/develop/bundles/6a84fc91051669a6304d/bundle.js:50316:40)
    at Generator.invoke [as _invoke] (https://riot.im/develop/bundles/6a84fc91051669a6304d/bundle.js:50550:22)
    at Generator.prototype.(anonymous function) [as throw] (https://riot.im/develop/bundles/6a84fc91051669a6304d/bundle.js:50368:21)
From previous event:
    at MatrixEvent._decryptionLoop (https://riot.im/develop/bundles/6a84fc91051669a6304d/bundle.js:25798:26)
    at MatrixEvent.<anonymous> (https://riot.im/develop/bundles/6a84fc91051669a6304d/bundle.js:25618:44)
From previous event:
    at MatrixEvent.attemptDecryption (https://riot.im/develop/bundles/6a84fc91051669a6304d/bundle.js:25623:25)
    at mapper (https://riot.im/develop/bundles/6a84fc91051669a6304d/bundle.js:6737:19)
    at Array.map (<anonymous>)
    at SyncApi._callee10$ (https://riot.im/develop/bundles/6a84fc91051669a6304d/bundle.js:35037:51)
    at tryCatch (https://riot.im/develop/bundles/6a84fc91051669a6304d/bundle.js:50316:40)
    at Generator.invoke [as _invoke] (https://riot.im/develop/bundles/6a84fc91051669a6304d/bundle.js:50550:22)
    at Generator.prototype.(anonymous function) [as next] (https://riot.im/develop/bundles/6a84fc91051669a6304d/bundle.js:50368:21)
From previous event:
    at SyncApi._processSyncResponse (https://riot.im/develop/bundles/6a84fc91051669a6304d/bundle.js:35396:22)
    at SyncApi._callee7$ (https://riot.im/develop/bundles/6a84fc91051669a6304d/bundle.js:34744:60)
    at tryCatch (https://riot.im/develop/bundles/6a84fc91051669a6304d/bundle.js:50316:40)
    at Generator.invoke [as _invoke] (https://riot.im/develop/bundles/6a84fc91051669a6304d/bundle.js:50550:22)
    at Generator.prototype.(anonymous function) [as next] (https://riot.im/develop/bundles/6a84fc91051669a6304d/bundle.js:50368:21) color: red
```

```
2019-03-18T16:11:09.532Z I No more outgoing room key requests
2019-03-18T16:11:13.738Z I m.room_key_request from @SELF:REDACTED for !REDACTED / REDACTED (id m1552925464517.40)
2019-03-18T16:11:13.786Z I device is already verified: sharing keys
2019-03-18T16:11:13.956Z I sharing keys for session REDACTED|REDACTED with device @SELF:REDACTED
2019-03-18T16:11:14.139Z I Using sessionid REDACTED for device @SELF:REDACTED
2019-03-18T16:11:22.712Z W Error decrypting event (id=undefined): DecryptionError[msg: Bad Encrypted Message, sender: REDACTED, err: Error: Error decrypting prekey message with existing session id REDACTED: OLM.BAD_MESSAGE_MAC]
2019-03-18T16:11:24.839Z I Started new sessionid REDACTED for device @SELF:REDACTED
2019-03-18T16:11:24.859Z W %cUnhandled rejection TypeError: Cannot read property 'resolve' of undefined
    at https://riot.im/develop/bundles/6a84fc91051669a6304d/bundle.js:17675:57
From previous event:
    at _loop3 (https://riot.im/develop/bundles/6a84fc91051669a6304d/bundle.js:17674:117)
    at _loop2 (https://riot.im/develop/bundles/6a84fc91051669a6304d/bundle.js:17684:45)
    at Object._callee2$ (https://riot.im/develop/bundles/6a84fc91051669a6304d/bundle.js:17699:33)
From previous event:
    at Object.ensureOlmSessionsForDevices (https://riot.im/develop/bundles/6a84fc91051669a6304d/bundle.js:17728:22)
    at Crypto._callee20$ (https://riot.im/develop/bundles/6a84fc91051669a6304d/bundle.js:16620:62)
    at tryCatch (https://riot.im/develop/bundles/6a84fc91051669a6304d/bundle.js:50316:40)
    at Generator.invoke [as _invoke] (https://riot.im/develop/bundles/6a84fc91051669a6304d/bundle.js:50550:22)
    at Generator.prototype.(anonymous function) [as next] (https://riot.im/develop/bundles/6a84fc91051669a6304d/bundle.js:50368:21)
From previous event:
    at Crypto._onToDeviceBadEncrypted (https://riot.im/develop/bundles/6a84fc91051669a6304d/bundle.js:16702:23)
    at Crypto.../../ReactSDKDevelop/workspace/matrix-js-sdk/lib/crypto/index.js.Crypto._onToDeviceEvent (https://riot.im/develop/bundles/6a84fc91051669a6304d/bundle.js:16259:18)
    at MatrixEvent.<anonymous> (https://riot.im/develop/bundles/6a84fc91051669a6304d/bundle.js:16263:24)
    at MatrixEvent.g (https://riot.im/develop/bundles/6a84fc91051669a6304d/bundle.js:324440:16)
    at MatrixEvent../node_modules/events/events.js.EventEmitter.emit (https://riot.im/develop/bundles/6a84fc91051669a6304d/bundle.js:324371:20)
    at MatrixEvent._callee$ (https://riot.im/develop/bundles/6a84fc91051669a6304d/bundle.js:25785:34)
    at tryCatch (https://riot.im/develop/bundles/6a84fc91051669a6304d/bundle.js:50316:40)
    at Generator.invoke [as _invoke] (https://riot.im/develop/bundles/6a84fc91051669a6304d/bundle.js:50550:22)
    at Generator.prototype.(anonymous function) [as throw] (https://riot.im/develop/bundles/6a84fc91051669a6304d/bundle.js:50368:21)
From previous event:
    at MatrixEvent._decryptionLoop (https://riot.im/develop/bundles/6a84fc91051669a6304d/bundle.js:25798:26)
    at MatrixEvent.<anonymous> (https://riot.im/develop/bundles/6a84fc91051669a6304d/bundle.js:25618:44)
From previous event:
    at MatrixEvent.attemptDecryption (https://riot.im/develop/bundles/6a84fc91051669a6304d/bundle.js:25623:25)
    at mapper (https://riot.im/develop/bundles/6a84fc91051669a6304d/bundle.js:6737:19)
    at Array.map (<anonymous>)
    at SyncApi._callee10$ (https://riot.im/develop/bundles/6a84fc91051669a6304d/bundle.js:35037:51)
    at tryCatch (https://riot.im/develop/bundles/6a84fc91051669a6304d/bundle.js:50316:40)
    at Generator.invoke [as _invoke] (https://riot.im/develop/bundles/6a84fc91051669a6304d/bundle.js:50550:22)
    at Generator.prototype.(anonymous function) [as next] (https://riot.im/develop/bundles/6a84fc91051669a6304d/bundle.js:50368:21)
From previous event:
    at SyncApi._processSyncResponse (https://riot.im/develop/bundles/6a84fc91051669a6304d/bundle.js:35396:22)
    at SyncApi._callee7$ (https://riot.im/develop/bundles/6a84fc91051669a6304d/bundle.js:34744:60)
From previous event:
    at SyncApi._sync (https://riot.im/develop/bundles/6a84fc91051669a6304d/bundle.js:34817:22)
    at https://riot.im/develop/bundles/6a84fc91051669a6304d/bundle.js:34918:16 color: red
```

**Comment by uhoreg** [comment]
`https://riot.im/develop/bundles/6a84fc91051669a6304d/bundle.js:17670:57` actually seems to be https://github.com/matrix-org/matrix-js-sdk/blob/f8985dbb39c6bbb449861c0e161c38ae3ac0ae7e/src/crypto/olmlib.js#L240
