### ISSUE TITLE
Exception when attempting to decrypt message

### ISSUE THREAD

**Issue by erikjohnston** [vector-im/riot-web#9798]
Broadly, I have a room where my riot web can successfully decrypt messages before and after a chunk that I can't decrypt. My mobile can, but when I request keys I get the following error:

```
bundle.js:153085 Unhandled rejection TypeError: Cannot read property 'roomId' of null
    at Object.onEventDecrypted (https://riot.im/develop/bundles/d6abb6fdf2bcc3f12b64/bundle.js:86122:60)
    at MatrixClient.emit (https://riot.im/develop/bundles/d6abb6fdf2bcc3f12b64/bundle.js:334223:7)
    at Reemitter._handleEvent (https://riot.im/develop/bundles/d6abb6fdf2bcc3f12b64/bundle.js:318:42)
    at MatrixEvent.emit (https://riot.im/develop/bundles/d6abb6fdf2bcc3f12b64/bundle.js:334223:7)
    at MatrixEvent._callee$ (https://riot.im/develop/bundles/d6abb6fdf2bcc3f12b64/bundle.js:26294:34)
From previous event:
    at MatrixEvent._decryptionLoop (https://riot.im/develop/bundles/d6abb6fdf2bcc3f12b64/bundle.js:26307:26)
    at MatrixEvent.<anonymous> (https://riot.im/develop/bundles/d6abb6fdf2bcc3f12b64/bundle.js:26127:44)
From previous event:
    at MatrixEvent.attemptDecryption (https://riot.im/develop/bundles/d6abb6fdf2bcc3f12b64/bundle.js:26132:25)
    at mapper (https://riot.im/develop/bundles/d6abb6fdf2bcc3f12b64/bundle.js:7126:19)
    at Array.map (<anonymous>)
    at SyncApi._callee10$ (https://riot.im/develop/bundles/d6abb6fdf2bcc3f12b64/bundle.js:36456:51)
    at tryCatch (https://riot.im/develop/bundles/d6abb6fdf2bcc3f12b64/bundle.js:51893:40)
    at Generator.invoke [as _invoke] (https://riot.im/develop/bundles/d6abb6fdf2bcc3f12b64/bundle.js:52127:22)
    at Generator.prototype.<computed> [as next] (https://riot.im/develop/bundles/d6abb6fdf2bcc3f12b64/bundle.js:51945:21)
From previous event:
    at SyncApi._processSyncResponse (https://riot.im/develop/bundles/d6abb6fdf2bcc3f12b64/bundle.js:36824:22)
    at SyncApi._callee7$ (https://riot.im/develop/bundles/d6abb6fdf2bcc3f12b64/bundle.js:36156:60)
    at tryCatch (https://riot.im/develop/bundles/d6abb6fdf2bcc3f12b64/bundle.js:51893:40)
    at Generator.invoke [as _invoke] (https://riot.im/develop/bundles/d6abb6fdf2bcc3f12b64/bundle.js:52127:22)
    at Generator.prototype.<computed> [as next] (https://riot.im/develop/bundles/d6abb6fdf2bcc3f12b64/bundle.js:51945:21)
```

- **Platform**: web
- **Browser**: Chrome
- **OS**:  Ubuntu, Arch Linux
- **URL**: riot.im/develop

**Comment by bwindels** [comment]
looks like it's either `onEventDecrypted` in `RoomBreadcrumbs` or `TimelinePanel`
