### ISSUE TITLE
Invalid Identity Server Discovery Response

### ISSUE THREAD

**Issue by non-Jedi** [vector-im/riot-web#9955]
### Description

When refreshing https://riot.im/develop, I still get the symptoms from #9835 sometimes.

![error-loading-riot](https://user-images.githubusercontent.com/17915621/58900513-4bd24580-86cd-11e9-9754-a784d041f6b5.png)

Following is a paste from my console as requested:

```

rageshake.js:61 To fix line numbers in Chrome: Meatball menu → Settings → Blackboxing → Add /rageshake\.js$
rageshake.js:61 Removing logs:  
Array(1)
rageshake.js:61 Removed 1 old logs.
rageshake.js:61 Using WebAssembly Olm
rageshake.js:61 set language to en-us
rageshake.js:61 Using Web platform
/develop/config.riot.im.json Failed to load resource: the server responded with a status of 404 ()
rageshake.js:61 Vector starting at https://riot.im/develop/#/room/#watercooler:half-shot.uk
rageshake.js:61 Verifying homeserver configuration
rageshake.js:61 Config uses a default_hs_url - constructing a default_server_config using this information
rageshake.js:61 Config uses a default_server_config - validating object
rageshake.js:61 Invalid /versions response
rageshake.js:61 Error: Homeserver URL does not appear to be a valid Matrix homeserver
    at newTranslatableError (languageHandler.js:44)
    at Function.buildValidatedConfigFromDiscovery (AutoDiscoveryUtils.js:74)
    at _callee3$ (index.js:459)
    at tryCatch (runtime.js:64)
    at Generator.invoke [as _invoke] (runtime.js:298)
    at Generator.prototype.(/develop/anonymous function) [as next] (https://riot.im/develop/bundles/1946b4e…/bundle.js:312633:21)
    at Generator.tryCatcher (bluebird.js:5278)
    at PromiseSpawn._promiseFulfilled (bluebird.js:2149)
    at Promise._settlePromise (bluebird.js:3361)
    at Promise._settlePromise0 (bluebird.js:3400)
    at Promise._settlePromises (bluebird.js:3481)
    at _drainQueueStep (bluebird.js:192)
    at _drainQueue (bluebird.js:185)
    at Async._drainQueues (bluebird.js:201)
    at Async.drainQueues (bluebird.js:71)
rageshake.js:61 A session was found - suppressing config error and using the session's homeserver
rageshake.js:61 Using pre-existing hsUrl and isUrl:  
Object
hsUrl
:
"https://matrix.thebeckmeyers.xyz"
isUrl
:
"https://vector.im"
__proto__
:
Object
rageshake.js:61 Invalid /api/v1 response
rageshake.js:61 Error: Invalid identity server discovery response
    at newTranslatableError (https://riot.im/develop/bundles/1946b4e…/bundle.js:151526:17)
    at Function.buildValidatedConfigFromDiscovery (https://riot.im/develop/bundles/1946b4e…/bundle.js:164204:69)
    at Function._callee$ (https://riot.im/develop/bundles/1946b4e…/bundle.js:164145:85)
    at tryCatch (https://riot.im/develop/bundles/1946b4e…/bundle.js:168543:40)
    at Generator.invoke [as _invoke] (https://riot.im/develop/bundles/1946b4e…/bundle.js:168777:22)
    at Generator.prototype.(anonymous function) [as next] (https://riot.im/develop/bundles/1946b4e…/bundle.js:168595:21)
From previous event:
    at Function.validateServerConfigWithStaticUrls (https://riot.im/develop/bundles/1946b4e…/bundle.js:164156:29)
    at _callee3$ (https://riot.im/develop/bundles/1946b4e…/bundle.js:383213:84)
    at tryCatch (https://riot.im/develop/bundles/1946b4e…/bundle.js:312581:40)
    at Generator.invoke [as _invoke] (https://riot.im/develop/bundles/1946b4e…/bundle.js:312815:22)
    at Generator.prototype.(anonymous function) [as next] (https://riot.im/develop/bundles/1946b4e…/bundle.js:312633:21)
    at Generator.tryCatcher (https://riot.im/develop/bundles/1946b4e…/bundle.js:318386:23)
    at PromiseSpawn._promiseFulfilled (https://riot.im/develop/bundles/1946b4e…/bundle.js:315519:49)
    at Promise._settlePromise (https://riot.im/develop/bundles/1946b4e…/bundle.js:316589:26)
    at Promise._settlePromise0 (https://riot.im/develop/bundles/1946b4e…/bundle.js:316629:10)
    at Promise._settlePromises (https://riot.im/develop/bundles/1946b4e…/bundle.js:316709:18)
    at _drainQueueStep (https://riot.im/develop/bundles/1946b4e…/bundle.js:313622:12)
    at _drainQueue (https://riot.im/develop/bundles/1946b4e…/bundle.js:313615:9)
    at Async._drainQueues (https://riot.im/develop/bundles/1946b4e…/bundle.js:313631:5)
    at Async.drainQueues (https://riot.im/develop/bundles/1946b4e…/bundle.js:313501:14)
```

### Steps to reproduce

- Refresh https://riot.im/develop until error page shows

### Version information

- **Platform**: web (in-browser)

For the web app:

- **Browser**: qutebrowser v1.6.2 (Backend: QtWebEngine (Chromium 65.0.3325.230))
- **OS**: Void Linux
- **URL**: riot.im/develop

**Comment by turt2live** [comment]
Heavily related to the solution of https://github.com/vector-im/riot-web/issues/9828

**Comment by heitorPB** [comment]
I came here to report this bug but you were faster :P

Not sure if it is related, but I also get a lot of errors with the "normal" riot.im app:
![connect](https://user-images.githubusercontent.com/13461702/58909038-767dc780-86e8-11e9-84ef-27ea4d445b33.png)

**Comment by turt2live** [comment]
@heitorPB that is unrelated, and likely a problem between you and the server rather than a bug in riot.

**Comment by turt2live** [comment]
I'm actually going to close this in favour of https://github.com/vector-im/riot-web/issues/9828 because the fix for 9828 will magically resolve this problem - the case won't exist anymore.
